install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("kableExtra")
install.packages("cowplot")
install.packages("RColorBrewer")
install.packages("pheatmap")
install.packages("kableExtra")
install.packages("viridis")

BiocManager::install("edgeR")
BiocManager::install("Glimma")
BiocManager::install("limma")
BiocManager::install("DESeq2")