```{r}
comparisonlevelscontrol <- c("control_bldg", "control_lay",  "control_inc.d3",  
                          "control_inc.d9",   "control_inc.d17",  
                          "control_hatch", "control_n5", "control_n9")

comparisonlevelsbldg <- c( "bldg_lay",  "bldg_inc.d3",  
                             "bldg_inc.d9", "bldg_inc.d17",  
                             "bldg_hatch", "bldg_n5", "bldg_n9")


comparisonlabelscharnobldg <- c("lay\ninc3", 
                          "inc3\ninc9", "inc.d9\ninc17", 
                          "inc17\nhatch" , "hatch\nn5", "n5\nn9")

comparisonlabelscontrol <- c("bldg\ncontrol" ,"lay\ncontrol", "inc3\ncontrol", 
                                "inc9\ncontrol", "inc17\ncontrol", 
                                "hatch\ncontrol" , "n5\ncontrol", "n9\ncontrol")

comparisonlabelsbldg <- c("lay\nbldg", "inc3\nbldg", 
                                "inc9\nbldg", "inc17\nbldg", 
                                "hatch\nbldg" , "n5\nbldg", "n9\nbldg")

comparisonlevelsremoval <- c("inc.d3_m.inc.d3", "inc.d9_m.inc.d9", 
                             "inc.d17_m.inc.d17", "hatch_m.n2")

comparisonlablelsremoval <- c("m.inc.d3", "m.inc.d9", 
                              "m.inc.d17", "m.n2")

comparisonlevelsreplace <- c("hatch_early", "inc.d17_prolong",  "hatch_prolong", 
                             "extend_hatch", "n5_extend")

comparisonlablelssreplace <- c("hatch\nearly", "inc.d17\nprolong",  "hatch\nprolong", 
                             "extend\nhatch", "n5\nextend")

```

## Treatment specific DEGs 

```{r suppltables}
allDEG <- read_csv("../results/03_allDEG.csv") %>%
  mutate(tissue = factor(tissue, levels = tissuelevel),
         direction = factor(direction, levels = alllevels))

# for figure
DEGchar <- allDEG %>% 
  filter(comparison %in% comparisonlevelschar) %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelschar))

# for suppl figures
DEGcontrol <- allDEG %>% 
  filter(grepl("control", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelscontrol))

DEGbldg <- allDEG %>% 
  filter(grepl("bldg", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelsbldg))  %>%
  drop_na()
```

## Sex and Tissue -related DEGs

```{r DEGs, message=F}

## other DEG stuff

pitsex <- read_csv("../results/DEseq2/sex/pituitary_female_male_DEGs.csv")
gonsex <- read_csv("../results/DEseq2/sex/gonad_female_male_DEGs.csv")

hyppit <- read_csv("../results/DEseq2/tissue/hypothalamus_pituitary_DEGs.csv") 
hypgon <- read_csv("../results/DEseq2/tissue/hypothalamus_gonad_DEGs.csv")
pitgon <- read_csv("../results/DEseq2/tissue/pituitary_gonad_DEGs.csv")

hyppit$direction <- factor(hyppit$direction, levels = c("hypothalamus", "pituitary"))
hypgon$direction <- factor(hypgon$direction, levels = c("hypothalamus",  "gonad"))
pitgon$direction <- factor(pitgon$direction, levels = c( "pituitary", "gonad"))

```

```{r barplots}

b2 <- sexbarplots(hyppit, 0, 8100) + labs(subtitle = " ", y = "DEGs w/ + LFC") +
  theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
  scale_x_discrete(labels=c("hypothalamus" = "hyp", "pituitary" = "pit" ))
b3 <- sexbarplots(hypgon, 0, 8100) + labs(subtitle = " " ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(), 
        axis.ticks = element_blank(), axis.title.y = element_blank()) +
    scale_x_discrete(labels=c("hypothalamus" = "hyp",  "gonad" = "gon"))
b4 <- sexbarplots(pitgon, 0, 8100) + labs(subtitle = " " ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank()) +
    scale_x_discrete(labels=c(  "pituitary" = "pit", "gonad" = "gon"))

    

c3 <- sexbarplots(pitsex, 0, 8100) + labs(subtitle = "pituitary" ) + 
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank())
c4 <- sexbarplots(gonsex, 0, 8100) + labs(subtitle = "gonads" ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank())
bc <- plot_grid(b1,b2,b3,b4, c1,c2,c3,c4, nrow = 1, rel_widths = c(1.5,1.1,0.9,0.9,1.5,1.1,0.9,0.9),
                labels = c("A", "", "", "", "B")_size = 8)
```


## suppl fig 1 controls versus bldg

```{r supplfig-1, fig.width=5, fig.height=5}


s1c <- makebargraphsuppl(DEGcontrol, "pituitary","DEGs w/ + LFC", 0, 5000)  +  
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        strip.text.x = element_blank())    + 
  labs(subtitle = "pituitary") 
s1e <- makebargraphsuppl(DEGcontrol, "gonad","DEGs w/ + LFC", 0, 5000) +  
  theme(strip.text.x = element_blank()) +
  scale_x_discrete(labels = comparisonlabelscontrol) +
  labs(subtitle = "gonads") 
  

 
s1d <- makebargraphsuppl(DEGbldg, "pituitary",NULL, 0, 1000)  +  
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        strip.text.x = element_blank())   
s1f <- makebargraphsuppl(DEGbldg, "gonad",NULL, 0, 1000) +  
  theme(strip.text.x = element_blank()) +
  scale_x_discrete(labels = comparisonlabelsbldg) 

s1 <- plot_grid(s1a, s1b, 
          s1c, s1d, 
          s1e, s1f, nrow = 3,
          rel_heights = c(1,0.9,1.3),
          labels = c("A", "B")_size = 8, rel_widths = c(1.1,1))


sa <- png::readPNG("../figures/images/fig_supplfig-1.png")
sa <- ggdraw() +  draw_image(sa, scale = 1)

supplfig1 <- plot_grid(s1, sa, ncol = 1, rel_heights = c(2,0.7))
supplfig1

# for volcano plots

pitinc <- DEGchar %>% filter(tissue == "pituitary", comparison == "inc.d9_inc.d17") 
goninc <- DEGchar %>% filter(tissue == "gonad", comparison == "lay_inc.d3") 

s2a <- plot.volcano("hypothalamus", sexlevels,  "hatch_n5") + facet_wrap(~sex) + 
  labs(subtitle = "hypothalamus", title = "Volcano plots") 
s2c <- plot.volcano("pituitary", sexlevels,  "inc.d9_inc.d17") + 
  facet_wrap(~sex) + 
  labs(subtitle = "pitutiary") + 
  theme(legend.title = element_blank(), strip.text = element_blank())
s2e <- plot.volcano("gonad", sexlevels,  "lay_inc.d3") + facet_wrap(~sex) + 
  labs( x = "Log-fold change (LFC)", subtitle = "gonads") + 
  theme(legend.title = element_blank(), strip.text = element_blank())

s2b <- makebargraph(hyphatch, "hypothalamus","Total DEGs with +LFC", 0, 1800)  + 
  labs(subtitle = " ", title = "Bar graphs") + scale_x_discrete(labels = "hatch\nvs n5")
s2d <- makebargraph(pitinc, "pituitary","Total DEGs with +LFC", 0, 1800) + 
  labs(subtitle = " ") + scale_x_discrete(labels = "inc.d9 vs\ninc.d17") + 
  theme(strip.text = element_blank())
s2f <- makebargraph(goninc, "gonad","Total DEGs with +LFC", 0, 1800) + 
  labs(subtitle = " ", x = "stages compared") + scale_x_discrete(labels = "lay vs\ninc.d3") + 
  theme(strip.text = element_blank())
supplfig2 <- plot_grid(s2a, s2b, s2c, s2d, s2e, s2f,
          rel_widths = c(2,1), rel_heights = c(1.1,1,1.1), ncol = 2,
          labels = c("A", "B")_size = 8)
supplfig2
```

```{r}
suppltable1 <- DEGchar %>%
  arrange( tissue, sex, direction, gene)
head(suppltable1)
write_csv(suppltable1, "../results/suppltable1.csv")

suppltable2 <- rbind(DEGcontrol, DEGbldg)  %>%
  arrange( tissue, sex, direction, gene)
head(suppltable2)
write_csv(suppltable2, "../results/suppltable2.csv")

```


```{r}
## prlpit
PRLpit <- candidatevsd %>% 
  filter(gene == "PRL", tissue == "pituitary")

# list of pvalue and DEGs
allDEG <- read_csv("../results/06_allDEG.csv")  %>%
  mutate(direction = factor(direction, levels = hypothesislevels))

# DEGs infor for PRL and external
hilodf <- allDEG %>%
  filter(comparison == "lo_hi")  %>%
  arrange(padj) 
hilogenes <- hilodf %>%  top_n(20) %>% pull(gene)

eggchickdf <- allDEG %>%
  filter(!comparison %in% c("lo_hi", "nest_eggs", "nest_chicks"))  %>%
  arrange(padj)  
eggchickgenes <- eggchickdf %>%  top_n(20) %>% pull(gene)


## data-driven PRL genes
pithilo <- makecorrdf("female", "pituitary", hilogenes)
pitWGCNA <- makecorrdf("female", "pituitary", WGCNAgenes[32:52])


## https://www.gynecologiconcology-online.net/article/S0090-8258(19)30069-1/fulltext
cancergenes <- makecorrdf("female", "pituitary", c(shaidgenes,suszynskaagenes, "PRL"))


## for scatter correlation (not currently usesed)
candidatevsdwide <- candidatevsd  %>%
    pivot_wider(names_from = gene, values_from = counts) 
pitwide <- subsetcandidatevsdwide(sexlevels, "pituitary")

## number of genes total vs plotted

eggchickdf %>% filter(tissue == "pituitary") %>% nrow()
hilodf %>% filter(tissue == "pituitary") %>% nrow()
length(WGCNAgenes)


b1 <- png::readPNG("../figures/images/fig_fig3b.png")
b1 <- ggdraw() +  draw_image(b1, scale = 1)

b2 <- makenewbargraph("pituitary", "female","eggs_chicks", 0, 4000) + labs(subtitle = "female")  + labs(title = " ") +
  scale_x_discrete(labels = "eggs vs. chicks")
b3 <- makenewbargraph("pituitary", "male", "eggs_chicks", 0, 4000)  + labs(subtitle = "male")  + labs(title = " ") +
  theme(axis.title.y = element_blank(), axis.ticks.y = element_blank(), 
        axis.text.y = element_blank(), axis.line.y = element_blank()) +
  scale_x_discrete(labels = "eggs vs. chicks")
b4 <- makenewbargraph("pituitary", "male", "lo_hi", 0, 4000)  +
  scale_x_discrete(labels = "lo vs. hi PRL")
b5 <- makenewbargraph("pituitary", "female", "lo_hi", 0, 4000)   + 
  theme(axis.title.y = element_blank(), axis.ticks.y = element_blank(), 
        axis.text.y = element_blank(), axis.line.y = element_blank()) +
  scale_x_discrete(labels = "lo vs. hi PRL")
b25 <- plot_grid(b2,b3,b4,b5, nrow = 2, rel_widths = c(1.2,1), rel_heights = c(1.2,1))

b6 <-  plottopDEGs(eggchickdf, "female",  "LFC eggs vs. chicks", "Top 10 female DEGs") + labs(title = " ")
b7 <-  plottopDEGs(eggchickdf, "male",  "LFC eggs vs. chicks", "Top 10 male DEGs") + labs(title = " ")
b8 <-  plottopDEGs(hilodf, "female",  "LFC lo vs. hi PRL", NULL)
b9 <-  plottopDEGs(hilodf, "male",  "LFC lo vs. hi PRL", NULL)
b15 <- plot_grid(b1,b25,nrow = 1, rel_widths = c(1.2,1))
b69 <- plot_grid(b6,b7,b8,b9, align = "v" , rel_heights = c(1.2,1))
b <- plot_grid(b15,b69s = c("C")_size = 8, rel_widths = c(1.2,1))

c1 <- plotcorrplot(pithilo, NULL) + theme(legend.position = "none") + labs(subtitle = "Top 20 DEGs, low vs. high PRL") 
c2 <- plotcorrplot(pitWGCNA, NULL) + theme(legend.position = "none") + labs(subtitle = "20 genes in WGCNA module with PRL") 
c3 <- plotcorrplot(cancergenes, NULL) + theme(legend.position = "right") + labs(subtitle = "Breast, ovary, & piuitary cancer genes", color = "Correlation")
c <- plot_grid(c1,c2,c3, nrow = 1s = c("D")_size = 8, rel_widths = c(1,1,1.3))

fig3 <- plot_grid(a, b, c, nrow = 3, rel_heights = c(1.2,2,1.8))
fig3
```


## tsne


```{r tSNE}

# removal
hyptsne <- subsetmaketsne("hypothalamus", removallevels, sexlevels)
pittsne <- subsetmaketsne("pituitary", removallevels, sexlevels)
gontsne <- subsetmaketsne("gonads", removallevels, sexlevels)

pittsne <- addgroupings(pittsne)

t4 <- plottsneelipsev2(pittsne, pittsne$treatment, allcolors) +  labs(title = "pituitary ", subtitle = "parental stage and manipulations") +
  facet_wrap(~sex) 
t5 <- plottsneelipsev2(pittsne, pittsne$extint, colorhypothesis) +  labs(title = "  ", subtitle = "external enviornment")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank())
t6 <- plottsneelipsev2(pittsne, pittsne$earlylate, colorhypothesis) +  labs(title = "  ", subtitle = "internal clock")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank())
t456 <- plot_grid(t4, t5, t6, nrow = 1, rel_widths = c(1.1,1,1))
t456

# replacement
hyptsne <- subsetmaketsne("hypothalamus", timinglevels, sexlevels)
pittsne <- subsetmaketsne("pituitary", timinglevels, sexlevels)
gontsne <- subsetmaketsne("gonads", timinglevels, sexlevels)

pittsne <- addgroupings(pittsne)

t4 <- plottsneelipsev2(pittsne, pittsne$treatment, allcolors) +  labs(title = "pituitary ", subtitle = "parental stage and manipulations") +
  facet_wrap(~sex) 
t5 <- plottsneelipsev2(pittsne, pittsne$extint, colorhypothesis) +  labs(title = "  ", subtitle = "external enviornment")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank())
t6 <- plottsneelipsev2(pittsne, pittsne$earlylate, colorhypothesis) +  labs(title = "  ", subtitle = "internal clock")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank())
t456 <- plot_grid(t4, t5, t6, nrow = 1, rel_widths = c(1.1,1,1))
t456

```


## Candidate Correlations - SUppl fig 1


```{r correlations}
hyp1 <- makecorrdf("female", "hypothalamus", litNotGOknown)  
pit1 <- makecorrdf("female", "pituitary", litNotGOknown)  
gon1 <- makecorrdf("female", "gonad", litNotGOknown)  

hyp2 <- makecorrdf("male", "hypothalamus", litNotGOknown)  
pit2 <- makecorrdf("male", "pituitary", litNotGOknown)  
gon2 <- makecorrdf("male", "gonad", litNotGOknown) 


hyp3 <- makecorrdf("female", "hypothalamus", GOgenes)  
pit3 <- makecorrdf("female", "pituitary", GOgenes)  
gon3 <- makecorrdf("female", "gonad", GOgenes)  

hyp4 <- makecorrdf("male", "hypothalamus", GOgenes)  
pit4 <- makecorrdf("male", "pituitary", GOgenes)  
gon4 <- makecorrdf("male", "gonad", GOgenes)  
```


```{r supplfig-2, fig.width=7.25, fig.height=7.25}

b1 <- plotcorrplot(hyp1, "females") + labs(y = "Hypothalamus", title = "Parental Care Literature")  + 
  scale_x_discrete(position = "top")   + theme(axis.text.x = element_text(vjust = -0.25))
b2 <- plotcorrplot(pit1, NULL)  + labs(y = "Pituitary") + 
  theme(axis.text.x = element_blank())
b3 <- plotcorrplot(gon1, NULL)  + labs(y = "Gonad") + theme(axis.text.x = element_text(vjust = 0.25))
 
b4 <- plotcorrplot(hyp2, "males") + labs( title =  " ") + theme( axis.text.y = element_blank(), axis.text.x = element_text(vjust = -0.25)) +
  scale_x_discrete(position = "top") 
b5 <- plotcorrplot(pit2, NULL)    + 
  theme(axis.text.x = element_blank(), axis.text.y = element_blank())
b6 <- plotcorrplot(gon2, NULL)  + theme( axis.text.y = element_blank(), axis.text.x = element_text(vjust = 0.25))


b7 <- plotcorrplot(hyp3, "females") + labs( title = "Parental Care GO") + 
   scale_x_discrete(position = "top") + theme(axis.text.x = element_text(vjust = -0.25))
b8 <- plotcorrplot(pit3, NULL)   + 
  theme(axis.text.x = element_blank())
b9 <- plotcorrplot(gon3, NULL)  + theme(axis.text.x = element_text(vjust = 0.25))

b10 <- plotcorrplot(hyp4, "males") + labs( title =  " ") + 
  theme(axis.text.y = element_blank(),
        axis.text.x = element_text(vjust = -0.25)) + scale_x_discrete(position = "top") 
b11 <- plotcorrplot(pit4, NULL)    + 
  theme(axis.text.x = element_blank() , axis.text.y = element_blank())
b12 <- plotcorrplot(gon4, NULL)   + theme( axis.text.y = element_blank(), axis.text.x = element_text(vjust = 0.25))

forlegend <- plotcorrplot(gon4, NULL) + theme(legend.position = "bottom") + labs(color = "Correlation")
mylegend <- get_legend(forlegend)

allcorplots <- plot_grid(b1,b4,b7,b10,
          b2,b5,b8,b11,
          b3,b6,b9,b12, rel_heights = c(1.4,1,1.2),
          labels = c("A", " ", "B")_size = 8, rel_widths = c(1.4,1.2,1.2,1))

supplfig2 <- plot_grid(allcorplots, mylegend, ncol = 1, rel_heights = c(1,0.1))
supplfig2


```


## Figure

```{r fig2, fig.width = 7.25, fig.height = 7.25}



c1 <- scattercorrelations(FH, FH$DRD1, "DRD1", FH$HTR2C, "HTR2C", "#969696" ) +  labs(title = " ", subtitle = " " )  
c3 <- scattercorrelations(FP, FP$AVPR1A, "AVPR1A", FP$CRHR1,  "CRHR1", "#969696")  + labs(title = " ", subtitle = " ") 
c5 <- scattercorrelations(FG, FG$PGR, "PGR",  FG$ESR1,  "ESR1", "#969696")   + labs(title = " ", subtitle = " ") 

c2 <- scattercorrelations(MH, MH$DRD1, "DRD1", MH$HTR2C, "HTR2C", "#525252")  + labs(title = " ", subtitle = " " )  
c4 <- scattercorrelations(MP, MP$AVPR1A,  "AVPR1A",  MP$CRHR1, "CRHR1", "#525252")  + labs(title = " ", subtitle = " " ) 
c6 <- scattercorrelations(MG, MG$PGR, "PGR", MG$ESR1, "ESR1", "#525252")   + labs(title = " ", subtitle = " " ) 
```


```{r newfig}

plot3candidates <- function(hypgene, pitgene, gongene){
  
  a1 <- newcandidateboxplot("hypothalamus", hypgene, "female", "female hypothalamus", "sequential") 
  a2 <- externalboxplots("hypothalamus", hypgene, "female", " ", "external") 
  a3 <- newcandidateboxplot("hypothalamus", hypgene, "male", "male hypothalamus", "sequential")
  a4 <- externalboxplots( "hypothalamus", hypgene, "female", " ", "external")
  
  hypplots <- plot_grid(a1,a2, a3, a4, rel_widths = c(2,1,2,1), nrow = 1)
  
  b1 <- newcandidateboxplot("pituitary", pitgene, "female", "female pituitary", "sequential")
  b2 <- externalboxplots("pituitary", pitgene, "female", " ", "external") 
  b3 <- newcandidateboxplot("pituitary", pitgene, "male", "male pituitary", "sequential")
  b4 <- externalboxplots( "pituitary", pitgene, "female", " ", "external")
  
  pitplots <- plot_grid(b1,b2, b3, b4, rel_widths = c(2,1,2,1), nrow = 1)
  
  c1 <- newcandidateboxplot("gonad", gongene, "female", "female gonad", "sequential") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  c2 <- externalboxplots("gonad", gongene, "female", " ", "external") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  c3 <- newcandidateboxplot("gonad", gongene, "male", "male gonad", "sequential") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  c4 <- externalboxplots( "gonad", gongene, "female", " ", "external") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  gonplots <- plot_grid(c1,c2, c3, c4, rel_widths = c(2,1,2,1), nrow = 1)
  
  fig2alt <- plot_grid(hypplots, pitplots, gonplots, nrow = 3,
                       labels = "AUTO"_size = 8,
                       rel_heights = c(1,1,1.2))
  print(fig2alt)
  
    
}

plot3candidates("COMT","PRL","AVPR1A")
plot3candidates("PRL","PRL", "PRL")
plot3candidates("PRL","FSH", "ESR1")
```




# Table 1. Candidate genes and differentially expressed genes



## Genes of interest

```{r candidategenes}
parentalcaregenes <- read_csv("../metadata/03_parentalcaregenes.csv") %>% select(-X1)
candidategenes <- parentalcaregenes %>% pull(gene) 
candidategenes

GOgenes <- parentalcaregenes %>% distinct(GO)  %>% drop_na() %>% pull(GO)
GOgenes

literaturegenes <- parentalcaregenes %>% 
  distinct(literature) %>% 
  drop_na() %>% 
  pull(literature)
literaturegenes

litNotGO <-  literaturegenes[!literaturegenes %in% GOgenes]
litNotGOknown <- litNotGO[!litNotGO %in% c("ADRA2A", "MEST", "SLC6A4")]
litNotGOknown
```


## Differentially expressed genes (DEGs)

```{r}
# summary DEG results from DESeq2
allDEGS <- read_csv("../results/suppltable1.csv") %>%
   mutate(posneg = ifelse(lfc >= 0, "+", "-"),
         sex = recode(sex, "female" = "F", "male" = "M" ),
         tissue = recode(tissue, 
                         "hypothalamus" = "H",
                         "pituitary" = "P", "gonad" = "G"),
         comparison = recode(comparison, 
                         "bldg_lay" = "Bldg2Lay",
                         "lay_inc.d3" = "Lay2Inc3", 
                         "inc.d3_inc.d9" = "Inc3toInc9",
                         "inc.d9_inc.d17" = "Inc9toInc17",
                         "inc.d17_hatch" = "In17toHatch",
                         "hatch_n5" = "Hatch2N5",
                         "n5_n9" = "N5toN9"),
         group = paste(sex, tissue, sep = "")) %>%
  mutate(res = paste("(", posneg, ")", sep = "")) %>%
  mutate(compres = paste(comparison, res, sep = "")) %>%
  select(gene, group, compres) 
allDEGS

DEGsbytissue <- function(whichtissueshorthand, whichsex){
  
  df <- allDEGS %>%
  filter(grepl(whichtissueshorthand, group),
         grepl(whichsex,group)) %>%
  group_by(group,gene) %>%
  summarize(results = str_c(compres, collapse = "; ")) %>%
  mutate(n = (str_count(results, pattern = ";"))+1) %>%
  arrange(desc(n))  %>%
  filter(n>1)
  #group_by(comparisons) %>%
  #summarize(genes = str_c(gene, collapse = "; "))  

  print(head(df))
  return(df)
  
}

hmDEGs <- DEGsbytissue("H", "M")
pmDEGs <- DEGsbytissue("P", "M")
gmDEGs <- DEGsbytissue("G", "M")

hfDEGs <- DEGsbytissue("H", "F")
pfDEGs <- DEGsbytissue("P", "F")
gfDEGs <- DEGsbytissue("G", "F")

maleDEGs <- rbind(hmDEGs, pmDEGs) %>%
  rbind(., gmDEGs)
maleDEGs

femaleDEGs <- rbind(hfDEGs, pfDEGs) %>%
  rbind(., gfDEGs)
femaleDEGs

summarizedDEGs <- rbind(femaleDEGs,maleDEGs) %>%
  group_by(group, results) %>%
  summarize(genes = str_c(gene, collapse = "; ")) 
summarizedDEGs


```




```{r writefiles}
write.csv(summarizedDEGs,"../results/summarizedDEGsv2.csv")

```


```{r}
e <- makebargraphv3(DEGbldg, "pituitary", "No. of DEGs\n (-)decreased  increased (+)", comparisonlabelsbldg) +
  labs(subtitle = "pituitary")
f <- makebargraphv3(DEGchar, "pituitary", NULL,comparisonlabelscharnobldg) +
  labs(subtitle = "pituitary")

g <- makebargraphv3(DEGbldg, "gonad", "No. of DEGs\n (-)decreased  increased (+)", comparisonlabelsbldg) +
  labs(subtitle = "gonads")
h <- makebargraphv3(DEGchar, "gonad", NULL, comparisonlabelscharnobldg) +
  labs(subtitle = "gonads")

ab <- plot_grid(b,a,rel_widths = c(2.5,1), 
                labels = c("A", "B")_size = 8, hjust = 0)
cd <- plot_grid(c,d,rel_widths = c(1.1,1), align = "h",
                labels = c("C", "D")_size = 8, hjust = 0)
ef <- plot_grid(e,f,rel_widths = c(1.1,1), align = "h")
gh <- plot_grid(g,h,rel_widths = c(1.1,1), align = "h")

fig <- plot_grid(ab,cd,ef, gh, ncol = 1)
fig
```


