---
title: "01_limma_voom"
output: md_document
---

DESeq2 is _not_ recommended for experiments with more than 100 samples ([see Mike Love's post](https://mikelove.wordpress.com/2016/09/28/deseq2-or-edger/)), so I decided to try the limma package. I followed [this tutorial](https://www.bioconductor.org/packages/devel/workflows/vignettes/RNAseq123/inst/doc/limmaWorkflow.html).

```{r}
library(limma)
library(Glimma)
library(edgeR)
library(kableExtra)
library(cowplot)
library(ggplot2)

knitr::opts_chunk$set(fig.path = '../figures/',cache=TRUE)

```

First, I read in the data I processed in 00_datawrangling.Rmd.

```{r read}
# import "colData" which contains sample information and "countData" which contains read counts
colData <- read.csv("../results/00_colData_characterization.csv", header = T, row.names = 1)
countData <- read.csv("../results/00_countData_characterization.csv", header = T, row.names = 1)
head(colData)
geneinfo <- read.csv("../results/00_geneinfo.csv", row.names = 1)
```

Then, I followed the steps from <https://github.com/macmanes-lab/RockDove/blob/master/parental_care/parental_analysis.Rmd>.

```{r edgeR}
# create a large DGEList with 3 elements
parentalobject <- DGEList(counts=countData, genes=geneinfo, group=colData$group)

# transform raw counts to countspermillion
cpms <- cpm(parentalobject)

# calculate number of lowly lowly expressed genes and remove them
table(rowSums(parentalobject$counts==0)==10)
keep_genes <- rowSums(cpms >= 1) >= 10
dge <- parentalobject[keep_genes, ]

# specific the design
parentaldesign <- model.matrix(~ colData$group )
colnames(parentaldesign) <- levels(colData$group)

# The TMM normalization
parentalobject <- calcNormFactors(parentalobject)
parentalobject <- estimateCommonDisp(parentalobject)
parentalobject <- estimateTagwiseDisp(parentalobject)
parentalobject <- estimateDisp(parentalobject, parentaldesign)
parentalobject <- estimateGLMCommonDisp(parentalobject, parentaldesign, verbose=TRUE)
parentalobject <- estimateGLMTrendedDisp(parentalobject, parentaldesign)
parentalobject <- estimateGLMTagwiseDisp(parentalobject, parentaldesign)

#  perform likelihood ratio test and thresholded testing
fit <- glmFit( parentalobject, parentaldesign, robust=T)
tr <- glmTreat(fit, lfc = 1)
topTags(tr)
```


# plotMDS (multidimential scaling)

```{r plotMDS}
plotMDS(parentalobject, cex = 0.5)
```

```{r plotMDS-colored}
levels(colData$tissue)
col.tissue <- c("#7570b3","#d95f02", "#1b9e77")[colData$tissue]
plotMDS(parentalobject,col=col.tissue)
legend("bottomright",fill=c("#7570b3","#d95f02", "#1b9e77"),legend=levels(colData$tissue))
title("Colored by Tissue")

levels(colData$treatment)
col.treatment <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6")[colData$treatment]
plotMDS(parentalobject,col=col.treatment)
legend("bottomright",fill=c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6"),legend=levels(colData$treatment))
title("Colored by Treatment")

levels(colData$sex)
col.sex <- c("#5ab4ac","#d8b365")[colData$sex]
plotMDS(parentalobject,col=col.sex)
legend("bottomright",fill=c("#5ab4ac","#d8b365"),legend=levels(colData$sex))
title("Colored by Sex")
```
```{r plotMDS-colorshape}
colData$sexTissue <- paste(colData$sex, colData$tissue, sep = "_")

plotMDS(parentalobject,col=col.treatment, labels = colData$sexTissue)
legend("bottomright",fill=c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6"),legend=levels(colData$treatment))
title("Colored by Treatment")
```

# specify contrasts and make MA plots (currently only a subset)

```{r 01-contrasts}
# view all levels
levels(colData$group)

# subset of conrasts - sex specific comparing hatch to lay
my.contrasts <- makeContrasts(
	         FG_HL = female.gonad.hatch - female.gonad.lay,
	         FH_HL = female.hypothalamus.hatch - female.hypothalamus.lay,
	         FP_HL = female.pituitary.hatch - female.pituitary.lay,
	         MP_HL = male.pituitary.hatch - male.pituitary.lay,
	         MH_HL = male.hypothalamus.hatch - male.hypothalamus.lay,
	         MG_HL = male.gonad.hatch - male.gonad.lay,	         
levels=parentaldesign)

cont <- "FG_HL"
summary(decideTestsDGE(
	glmTreat(fit, contrast=my.contrasts[,cont], lfc = 1), 
	adjust.method="fdr", p.value=0.01))
kable(topTags(glmTreat(fit, contrast=my.contrasts[,cont]), n=5), digits=2, lfc = 1)
plotMD(glmTreat(fit, contrast=my.contrasts[,cont], lfc=1), main='Female gonad lay to hatch', frame.plot=F)

cont <- "FH_HL"
summary(decideTestsDGE(
	glmTreat(fit, contrast=my.contrasts[,cont], lfc = 1), 
	adjust.method="fdr", p.value=0.01))
kable(topTags(glmTreat(fit, contrast=my.contrasts[,cont]), n=5), digits=2, lfc = 1)
plotMD(glmTreat(fit, contrast=my.contrasts[,cont], lfc=1), main='Female hypothalamus lay to hatch', frame.plot=F)


cont <- "FP_HL"
summary(decideTestsDGE(
	glmTreat(fit, contrast=my.contrasts[,cont], lfc = 1), 
	adjust.method="fdr", p.value=0.01))
kable(topTags(glmTreat(fit, contrast=my.contrasts[,cont]), n=5), digits=2, lfc = 1)
plotMD(glmTreat(fit, contrast=my.contrasts[,cont], lfc=1), main='Female pituitary lay to hatch', frame.plot=F)


cont <- "MG_HL"
summary(decideTestsDGE(
	glmTreat(fit, contrast=my.contrasts[,cont], lfc = 1), 
	adjust.method="fdr", p.value=0.01))
#kable(topTags(glmTreat(fit, contrast=my.contrasts[,cont]), n=5), digits=2, lfc = 1)
plotMD(glmTreat(fit, contrast=my.contrasts[,cont], lfc=1), main='Male gonad lay to hatch', frame.plot=F)

cont <- "MH_HL"
summary(decideTestsDGE(
	glmTreat(fit, contrast=my.contrasts[,cont], lfc = 1), 
	adjust.method="fdr", p.value=0.01))
kable(topTags(glmTreat(fit, contrast=my.contrasts[,cont]), n=5), digits=2, lfc = 1)
plotMD(glmTreat(fit, contrast=my.contrasts[,cont], lfc=1), main='Male hypothalamus lay to hatch', frame.plot=F)


cont <- "MP_HL"
summary(decideTestsDGE(
	glmTreat(fit, contrast=my.contrasts[,cont], lfc = 1), 
	adjust.method="fdr", p.value=0.01))
kable(topTags(glmTreat(fit, contrast=my.contrasts[,cont]), n=5), digits=2, lfc = 1)
plotMD(glmTreat(fit, contrast=my.contrasts[,cont], lfc=1), main='Male pituitary lay to hatch', frame.plot=F)
```

# volcano plots

```{r volcanoplots}
# from http://www.compbio.dundee.ac.uk/user/pschofield/Projects/teaching_pg/workshops/biocDGE.html#maplots

lrt <- glmLRT(fit,coef=2)
topTags(lrt)

tt <- topTags(lrt,n=10000)$table

ggplot(data=tt) + geom_point(aes(x=logFC,y=-log(FDR),color=logCPM)) +
  scale_colour_gradientn(colours=c("#000000" ,"#FF0000" ))
```