---
title: "07_DESeq_ALL"
output: md_document
---

```{r setup, message=F, comment=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(DESeq2)
library(cowplot)
library(RColorBrewer)
library(pheatmap)
library(kableExtra)
library(viridis)

library("BiocParallel")
register(MulticoreParam(4))

# load custom functions  
source("../R/functions.R") 

knitr::opts_chunk$set(fig.path = '../figures/ALL/', cache=TRUE)
```


```{r readfiles}
# import "colData" which contains sample information and "countData" which contains read counts
counts <- read.csv("../results/00_countData_characterization.csv", row.names = 1, header = T)

samples <- read.csv("../metadata/00_colData_characterization.csv", row.names = 1, header = T)
geneinfo <- read.csv("../metadata//00_geneinfo.csv", row.names = 1, header = T)

head(samples)
```

```{r factors} 
samples$treatment <- factor(samples$treatment, levels = 
                              c("control", "bldg", "lay", "inc.d3", "inc.d9", 
                                "inc.d17", "hatch", "n5", "n9"))
summary(samples)
```


```{r dds}
dds <- DESeqDataSetFromMatrix(countData = counts,
                              colData = samples,
                              design = ~ sex * tissue * treatment )

dds <- estimateSizeFactors(dds)
dds

# here filtering on moderate counts in 10 samples out of totla
nsamp <- 24
keep <- rowSums(counts(dds, normalized=TRUE) >= 10) >= nsamp
table(keep)

dds <- dds[keep,] 
dds

dds <- DESeq(dds, parallel = TRUE) # Differential expression analysis
```

```{r vsd}
vsd <- vst(dds, blind=FALSE) # variance stabilized 
write.csv(assay(vsd), "../results/01_vsd_characterization.csv")
```

```{r pca}
# create the dataframe using my function pcadataframe
pcadata <- pcadataframe(vsd, intgroup=c("treatment", "tissue", "sex"), returnData=TRUE)
percentVar <- round(100 * attr(pcadata, "percentVar"))
percentVar

pca12 <- ggplot(pcadata, aes(PC1, PC2, color = tissue, shape = sex, alpha = treatment)) + 
  geom_point(size = 2) +
  stat_ellipse(type = "t") +
  xlab(paste0("PC1: ", percentVar[1],"% variance")) +
  ylab(paste0("PC2: ", percentVar[2],"% variance")) +
  theme_cowplot(font_size = 8, line_size = 0.25) +
  labs(subtitle = eachgroup)
pca12

summary(aov(PC1 ~ treatment, data=pcadata))
TukeyHSD(aov(PC1 ~ treatment, data=pcadata), which = "treatment")

summary(aov(PC2 ~ treatment, data=pcadata))
TukeyHSD(aov(PC2 ~ treatment, data=pcadata), which = "treatment")

pca34 <- ggplot(pcadata, aes(PC3, PC4, color = tissue, shape = sex, alpha = treatment)) + 
  geom_point(size = 2) +
  stat_ellipse(type = "t") +
  xlab(paste0("PC3: ", percentVar[3],"% variance")) +
  ylab(paste0("PC4: ", percentVar[4],"% variance")) +
  theme_cowplot(font_size = 8, line_size = 0.25) +
  labs(subtitle = eachgroup)
pca34

summary(aov(PC3 ~ treatment, data=pcadata))
TukeyHSD(aov(PC3 ~ treatment, data=pcadata), which = "treatment")


summary(aov(PC4 ~ treatment, data=pcadata))
TukeyHSD(aov(PC4 ~ treatment, data=pcadata), which = "treatment")
```
