---
title: "02_limma_hyp_grouped"
output: md_document
---


```{r}
library(tidyverse)
library(limma)
library(Glimma)
library(edgeR)
library(kableExtra)
library(cowplot)

# load custom functions  
source("../R/functions.R")  

knitr::opts_chunk$set(fig.path = '../figures/hyp_grouped/',cache=TRUE)
```


This anlaysis will _exclude_ the control timepoint but _combine_ incubation and nestling timepoints.


```{r read}
# import "colData" which contains sample information and "countData" which contains read counts
colData <- read.csv("../results/00_colData_characterization.csv", header = T, row.names = 1)
countData <- read.csv("../results/00_countData_characterization.csv", header = T, row.names = 1)
geneinfo <- read.csv("../results/00_geneinfo.csv", row.names = 1)
```

```{r}
# making new groups
colData$group <- NULL
colData$tempgroup <- ifelse(colData$treatment == "bldg", "bldg",
                  ifelse(colData$treatment == "control", "control",
                   ifelse(colData$treatment == "hatch", "hatch",
                    ifelse(grepl("inc", colData$treatment), "inc",
                     ifelse(colData$treatment == "lay", "lay", "nestl")))))
colData$tempgroup <- as.factor(colData$tempgroup)

colData$group <- paste(colData$sex, colData$tempgroup, sep = "")
colData$group <- as.factor(colData$group)
str(colData$group)
```

```{r filter}
colData <- colData %>%
  dplyr::filter(grepl('hypothalamus', tissue)) %>%
  dplyr::filter(treatment != "control") %>%
  #dplyr::filter(sex == "female") %>%
  droplevels()
row.names(colData) <- colData$V1

# print sample sizes
colData %>% select(group, tissue)  %>%  summary()

savecols <- as.character(colData$V1) 
savecols <- as.vector(savecols) 
countData <- countData %>% dplyr::select(one_of(savecols)) 

# check that row and col lenghts are equal
ncol(countData) == nrow(colData)
```



```{r edgeR}
# create a large DGEList with 3 elements
parentalobject <- DGEList(counts=countData, genes=geneinfo, group=colData$group)

# transform raw counts to countspermillion
cpms <- cpm(parentalobject)

# calculate number of lowly lowly expressed genes and remove them
table(rowSums(parentalobject$counts==0)==10)
keep_genes <- rowSums(cpms >= 1) >= 10
dge <- parentalobject[keep_genes, ]

# specific the design
parentaldesign <- model.matrix(~ colData$group )
colnames(parentaldesign) <- levels(colData$group)

# The TMM normalization
parentalobject <- calcNormFactors(parentalobject)
parentalobject <- estimateCommonDisp(parentalobject)
parentalobject <- estimateTagwiseDisp(parentalobject)
parentalobject <- estimateDisp(parentalobject, parentaldesign)
parentalobject <- estimateGLMCommonDisp(parentalobject, parentaldesign, verbose=TRUE)
parentalobject <- estimateGLMTrendedDisp(parentalobject, parentaldesign)
parentalobject <- estimateGLMTagwiseDisp(parentalobject, parentaldesign)

#  perform likelihood ratio test and thresholded testing
fit <- glmFit( parentalobject, parentaldesign, robust=T)
tr <- glmTreat(fit, lfc = 1)
topTags(tr)
head(tr$table)
```


# plotMDS (multidimential scaling)

```{r plotMDS}
levels(colData$group)
col.group <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99",
               "#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99")[colData$group]
myfill <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99",
            "#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99")

plotMDS(parentalobject, cex = 0.5, labels = colData$group, col=col.group)
title("MDS 1v2")
plotMDS(parentalobject, cex = 0.5, labels = colData$group, col=col.group, dim=c(3,4))
title("MDS 3v4")
plotMDS(parentalobject, cex = 0.5, labels = colData$group, col=col.group, dim=c(5,6))
title("MDS 5v6")
```

For color coding, I used this tutorial for guidance <https://combine-australia.github.io/RNAseq-R/06-rnaseq-day1.html>.


# specify contrasts and make MA plots

```{r MDSplots}
# view all levels
levels(colData$group)

# subset of conrasts - sex specific comparing hatch to lay
my.contrasts <- makeContrasts(
	         femaleBL = femalebldg - femalelay,
	         femaleLI = femalelay - femaleinc,
	         femaleIH = femaleinc - femalehatch,
	         femaleHN = femalehatch -  femalenestl,
	         femaleBL = femalebldg - femaleinc,
	         femaleBL = femalebldg - femalehatch,
	         femaleBL = femalebldg - femalenestl,
	         femaleLH = femalelay - femalehatch,
	         femaleLN = femalelay - femalenestl,
	         femaleHN = femalehatch - femalenestl,
	         
	         maleBL = malebldg - malelay,
	         maleLI = malelay - maleinc,
	         maleIH = maleinc - malehatch,
	         maleHN = malehatch -  malenestl,
	         maleBL = malebldg - maleinc,
	         maleBL = malebldg - malehatch,
	         maleBL = malebldg - malenestl,
	         maleLH = malelay - malehatch,
	         maleLN = malelay - malenestl,
	         maleHN = malehatch - malenestl,
	         
	         fm_B = femalebldg - malebldg,
	         fm_L = femalelay - malelay,
	         fm_I = femaleinc - maleinc,
	         fm_H = femalehatch - malehatch,
	         fm_N = femalenestl - malenestl,
levels=parentaldesign)

# create a list with all the two way contrasts
mycontrasts <- colnames(my.contrasts)

# use the printplotcontrasts function to print summary stats and a volcano plot

for(i in mycontrasts){
  printplotcontrasts(i)
}
```


```{r volcanoplots}
for(i in mycontrasts){
  plotVolcanos(i) 
}
```

