---
title: "01_pca"
output: md_document
---

```{r setup}
library(tidyverse)
library(ggfortify) # for PCA analysis
library(cluster)
library(cowplot)
library(stringr)
library(gridExtra)
library(grid)

source("../R/themes.R")  # load custom themes and color palletes

knitr::opts_chunk$set(echo = TRUE, cache = T, fig.path = '../figures/pca/')
```

```{r rawdata}
samples <- read.csv("../metadata/00_samples.csv", header = T, row.names = 1)
counts <- read.csv("../results/00_counts.csv", header = T, row.names = 1)
geneinfo <- read.csv("../metadata/00_geneinfo.csv", row.names = 1, header = T)

samples$treatment <- factor(samples$treatment, levels = 
                             c("control", "bldg", "lay",
                               "inc.d3", "inc.d9", "inc.d17", 
                               "hatch", "n5",  "n9",
                               "m.inc.d3", "m.inc.d8","m.inc.d9",
                               "m.inc.d17","m.n2" ,"prolong", "extend"))
samples$tissue <- factor(samples$tissue, levels = 
                             c("hypothalamus", "pituitary", "gonad" ))

samples$lastday <- ifelse(grepl("m.inc.d3|m.inc.d9|m.inc.d17|m.n2", samples$treatment), "empty nest", 
                    ifelse(grepl("m.inc.d8|hatch|extend", samples$treatment),"chicks hatch",      
                     ifelse(grepl("n5", samples$treatment),"chicks early",
                     ifelse(grepl("n9", samples$treatment),"chicks later",
                     ifelse(grepl("control", samples$treatment),"control",
                     ifelse(grepl("bldg", samples$treatment),"nest building",
                     ifelse(grepl("prolong", samples$treatment),"eggs delay",
                      ifelse(grepl("lay", samples$treatment),"eggs lay",
                      ifelse(grepl("inc.d3", samples$treatment),"eggs early",
                     ifelse(grepl("inc.d9", samples$treatment),"eggs middle",
                    ifelse(grepl("inc.d17", samples$treatment),"eggs later", NA)))))))))))

samples$penultimate <-  ifelse(grepl("extend", samples$treatment),"eggs delay",  
                          ifelse(grepl("m.n2", samples$treatment),"chicks hatch",
                     ifelse(grepl("n5", samples$treatment),"chicks early",
                     ifelse(grepl("n9", samples$treatment),"chicks later",
                     ifelse(grepl("control", samples$treatment),"control",
                     ifelse(grepl("bldg|lay", samples$treatment),"nest building",
                     ifelse(grepl("prolong", samples$treatment),"eggs delay",
                      ifelse(grepl("inc.d3|m.inc.d3", samples$treatment),"eggs early",
                     ifelse(grepl("inc.d9|m.inc.d9|m.inc.d8", samples$treatment),"eggs middle",
                    ifelse(grepl("inc.d17|hatch", samples$treatment),"eggs later", NA))))))))))

samples$xlabel <- samples$treatment

levels(samples$xlabel) <-  c("control", "nest.building", "egg.lay",
                               "eggs.early", "eggs.early.remove", 
                               "eggs.mid", "eggs.mid.hatch", "eggs.mid.remove",
                               "eggs.end", "eggs.end.remove",
                               "chicks.hatch",  "chicks.hatch.remove"  ,
                               "chicks.mid", "eggs.delay", "eggs.delay.hatch", "chicks.end")


samples$lastday <- factor(samples$lastday, levels =  c("control", "nest building", "eggs lay",
                               "eggs early", "eggs middle",  "eggs later","eggs delay",
                               "chicks hatch", "chicks early",  "chicks later", "empty nest"))

samples$penultimate <- factor(samples$penultimate, levels =  c("control", "nest building",
                               "eggs early",  "eggs middle",  "eggs later",  "eggs delay",
                               "chicks hatch", "chicks early",  "chicks later"))


```

```{r raw}
# https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_pca.html

# pca
pca <- prcomp(t(counts))

p <- autoplot(pca, data = samples, alpha = 'tissue', shape = "sex")


rawPCA112 <- p + labs(subtitle = "Raw counts") +
  scale_colour_discrete(name = "tissue", labels = c("hypothalamus", "pituitary", "gonad")) +
  scale_shape_discrete(name = "sex", labels = c("female", "male")) +
  #xlab(stringr::str_replace(p$labels$x, "PC", "Principle Component ")) +
  #ylab(stringr::str_replace(p$labels$y, "PC", "Principle Component ")) +
  theme_rmh() + guides(alpha = guide_legend(order = 1), 
              shape = guide_legend(order = 2)) +
  stat_ellipse(aes(linetype = sex, colour = tissue)) 
rawPCA112

```

## with normalize edgeR data

```{r normalized}

pseudocounts <- read.csv("../results/01_pseudo.counts.csv", row.names = 1)
#head(pseudocounts)
pca <- prcomp(t(pseudocounts))

p <- autoplot(pca, data = samples, colour = 'tissue', shape = "sex")
p

edgRpca12 <- p + labs(subtitle = "Normalized counts from edgeR") +
  scale_colour_discrete(name = "tissue", labels = c("hypothalamus", "pituitary", "gonad")) +
  scale_shape_manual(name = "sex", labels = c("female", "male"), values = c(21,19)) +
  theme_rmh() + guides(color = guide_legend(order = 1), 
              shape = guide_legend(order = 2)) +
  stat_ellipse(aes(linetype = sex, colour = tissue))
edgRpca12
```

```{r sidebyside}

sidebyside <- plot_grid(rawPCA112 + theme(legend.position = "none"),
                        edgRpca12,
                        rel_widths = c(0.4,0.6))
sidebyside

```


