---
title: "04_DESeq_sexes_manipulate"
output: md_document
---

```{r setup, include = FALSE}

library(tidyverse)
library(DESeq2)
library(cowplot)
library(pheatmap)
library(viridis)
library(forcats)
library(caret) # LDA analysis
library(MASS) # LDA analysis
library(ggtext) # for pretty plots
library(ctsGE)

library(BiocParallel)
register(MulticoreParam(6))

source("../R/functions.R")  # load custom functions 
source("../R/themes.R")  # load custom themes and color palletes

knitr::opts_chunk$set(fig.path = '../figures/manipulation/', cache = TRUE,  message=F, comment=FALSE, warning=FALSE)
```

## DEseq2 analysis on characterization. Looking at treatment AND sex for each tissue

```{r readfiles}
# import "colData" which contains sample information and "countData" which contains read counts
c.colData <- read.csv("../metadata/00_colData_manipluation.csv", header = T, row.names = 1)
c.countData <- read.csv("../results/00_countData_manipluation.csv", header = T, row.names = 1)
geneinfo <- read.csv("../metadata/00_geneinfo.csv", row.names = 1)

# set treatment levels


# craete variable that will be critical for subset later on
c.colData$sextissue <- as.factor(paste(c.colData$sex, c.colData$tissue, sep = "_"))

# rename some factors
levels(c.colData$treatment)
# "extend"    "m.inc.d17" "m.inc.d3"  "m.inc.d8"  "m.inc.d9"  "m.n2"      "prolong" 
c.colData <- c.colData %>%
    mutate(treatment = fct_recode(treatment,
                            "extend" = "extend",
                            "prolong" = "prolong",
                            "early" = "m.inc.d8",
                            "remove.d03" = "m.inc.d3",
                            "remove.d09" = "m.inc.d9",
                            "remove.d17" = "m.inc.d17",
                            "remove.d20" = "m.n2"))

c.colData$treatment <- factor(c.colData$treatment, levels = maniplevels)
levels(c.colData$treatment)

# drop columsn that are bad for model AND not needed for later joining
c.colData$bird <- NULL
c.colData$tissue <- NULL
c.colData$study <- NULL
c.colData$group <- NULL
head(c.colData)
str(c.colData)
```



```{r dds}
dds.hypothalamus <- subsetDESeq2(c.colData,  c.countData, c("female_hypothalamus","male_hypothalamus") )
dds.pituitary <- subsetDESeq2(c.colData,  c.countData, c("female_pituitary", "male_pituitary" ) )
dds.gonad <- subsetDESeq2(c.colData,  c.countData, c("female_gonad", "male_gonad") )
```


## total degs

This one won't work yet because I have a filter step that slims the data to a subset of the characterization data. 

```{r totalDEGs, results = 'hide', eval = F, echo = T}
DEGs.pituitary <- returntotalDEGs(dds.pituitary)
plottotalDEGs(DEGs.pituitary, "Male & Female Pituitary DEGs")
```

## Variance stabilized data

```{r vsd}
vsd.hyp <- vst(dds.hypothalamus, blind=FALSE) 
vsd.pit <- vst(dds.pituitary, blind=FALSE) 
vsd.gon <- vst(dds.gonad, blind=FALSE) 

vsd.hyp.df <- vsd.dataframe(vsd.hyp) 
vsd.pit.df <- vsd.dataframe(vsd.pit) 
vsd.gon.df <- vsd.dataframe(vsd.gon) 
```

## PCA

```{r pca}
hypPCA <- returnPCAs2(vsd.hyp)
plotPC12(hypPCA, "Hypothalamus")

pitPCA <- returnPCAs2(vsd.pit)
plotPC12(pitPCA, "Pituitary")

gonPCA <- returnPCAs2(vsd.gon)
plotPC12(gonPCA, "Gonad")
```


## Linear discriminant analysis (LDA)

http://www.sthda.com/english/articles/36-classification-methods-essentials/146-discriminant-analysis-essentials-in-r/


```{r LDAdfs}
# prep col data for LDA
colDataHyp <- subsetcolData2(c.colData, c("female_hypothalamus", "male_hypothalamus"))
colDataPit <- subsetcolData2(c.colData, c("female_pituitary", "male_pituitary"))
colDataGon <- subsetcolData2(c.colData, c("female_gonad", "male_gonad"))

# LDA for treatment (7 groups)
LDA.hyp1 <- LDAdata.treatment(vsd.hyp, colDataHyp)
LDA.pit1 <- LDAdata.treatment(vsd.pit, colDataPit)
LDA.gon1 <- LDAdata.treatment(vsd.gon, colDataGon)

```

```{r LDA, fig.width = 9}

# figures for both of the above

# treatment
a <- LDAplot.manipulation(LDA.hyp1 , "Hypothalamus model 1", "parental state ~ .  0.185 pred. acc.",
                        "LD1, F = 3.7984170", "LD2, F = 3.0810558")

b <- LDAplot.manipulation(LDA.pit1 ,  "Pituitary model 1", "parental state ~ .  0.407 pred. acc.",
                        "LD1, F = 6.188592", "LD2, F = 3.604309")

c <- LDAplot.manipulation(LDA.gon1 , "Gonad model 1", "parental state ~ .  has 0.154 pred. acc.",
                        "LD1, F = 4.066997", "LD2, F = 2.782389")

c <- c + theme(legend.direction = "horizontal")
mylegend <- get_legend(c)

temp <- plot_grid(a + theme(legend.position = "none"),
                  b + theme(legend.position = "none"),
                  c + theme(legend.position = "none"), nrow = 1)


plot_grid(temp, mylegend, nrow = 2, rel_heights = c(1,0.3))

```

## plot genes in a  PRL WGCNA module

```{r wgcna, eval = T, echo = F}
plotWGCNAcandidatesManip(vsd.pit, c("NP_990797.2", "NP_001090992.1", "NP_990136.1", "NP_001035179.1"), colDataPit, "PRL, VIPR1, TH & AR expression, Pituitary")

plotWGCNAcandidatesManip(vsd.hyp, c("NP_001170780.1", "NP_001090992.1", "NP_001014970.1"), colDataHyp, "VIP expression, Hypothalamus")



plotWGCNAcandidatesManip(vsd.pit,c("NP_990797.2","NP_001004392.2", "NP_001004403.1", "NP_001006255.2", "NP_001006274.1",
                           "NP_989500.1", "XP_001234815.2", "XP_015149152.1", "XP_416110.5"),
                    colDataPit, "Part of 9 genes in the same WGCNA module as PRL in the characterization study")

plotWGCNAcandidatesManip(vsd.pit,
                    c("XP_428110.3","NP_001004392.2",  "XP_015142961.1", "XP_015139636.1",
                      "XP_015137408.1", "XP_004938696.1", "NP_990620.1", "NP_001170793.2", "XP_015132722.1"),
                    colDataPit, "Part of 9 genes in the same WGCNA module as PRLR in the characterization study")

plotWGCNAcandidatesManip(vsd.pit, c("NP_989957.1", "NP_001120784.1", "NP_001120786.1",
                               "NP_001131120.1", "NP_001186037.1", "NP_989871.1",
                               "NP_990797.2", "XP_015132722.1", "XP_015132722.1", "NP_001090992.1"), colDataPit, "Pitutary: CISH, SOCS, PRL, PRLR")

plotWGCNAcandidatesManip(vsd.hyp, c("NP_989957.1", "NP_001120784.1", "NP_001120786.1",
                               "NP_001131120.1", "NP_001186037.1", "NP_989871.1",
                               "NP_990797.2", "XP_015132722.1", "NP_001090992.1"), colDataHyp, "Hypothalamus: CISH, SOCS, PRL, PRLR")

plotWGCNAcandidatesManip(vsd.gon, c("NP_989957.1", "NP_001120784.1", "NP_001120786.1",
                               "NP_001131120.1", "NP_001186037.1", "NP_989871.1",
                               "NP_990797.2", "XP_015132722.1", "NP_001090992.1"), colDataGon, "Gonad: CISH, SOCS, PRL, PRLR")
```

## genes that were in the WGCNA module with PRL twice!

```{r, sharedmodule, fig.height= 8}
PRL_associated <- read.csv("../results/08_PRL_associated.csv", header = T)
PRL_manipulated <- read.csv("../results/08_PRL_manipulated.csv", header = T)

str(PRL_associated)
str(PRL_manipulated)
PRLjoin <- inner_join(PRL_associated, PRL_manipulated, by = "entrezid")

PRLboth <- PRLjoin$entrezid
PRLboth


plotWGCNAcandidatesManip(vsd.pit, PRLboth, colDataPit, "PRL char and manip WGNA shared modules")

prl36 <-  PRL_manipulated$entrezid[252:271]
plotWGCNAcandidatesManip(vsd.pit, prl36, colDataPit, "PRL-RIPK3 pattern in the PRL module")
```
  