---
title: "04_DESeq2"
author: "Rayna M Harris"
date: "5/12/2020"
output: md_document
---

```{r setup}
library(tidyverse)
library(DESeq2)

library(BiocParallel)
register(MulticoreParam(6))

source("../R/themes.R")
source("../R/functions.R")
```


### Hypothesis-related data wrangle

- PRL WGCNA
- hi v lo PRL
- extral environment


```{r data}
countData <- read.csv("../results/00_counts.csv", header = T, row.names = 1)

## sample info
colData <- read_csv("../metadata/00_colData.csv") %>%
  mutate(tissue = factor(tissue, levels = tissuelevels),
         treatment = factor(treatment, levels = alllevels)) %>%
  mutate(sextissue = as.factor(paste(sex,tissue, sep = "_"))) %>%
  column_to_rownames(var = "X1") %>%
  mutate("samples" = V1) 
head(colData)

## calcualte hi lo PRL, add to col Data
PRLvsd <- read_csv("../results/03_candidatevsd.csv") %>%
  filter(gene == "PRL", tissue == "pituitary") 
PRLvsd %>%
  group_by(sex) %>%
  summarize(avecounts = mean(counts))
PRLvsd <- PRLvsd %>%
  mutate(hiloPRL = ifelse(counts >= 18.5, "hi", "lo")) %>%
  mutate(bird = sapply(strsplit(samples, '\\_'), "[", 1)) %>%
  select(bird, hiloPRL) 
colData <- left_join(colData, PRLvsd, by = "bird")   
unique(colData$hiloPRL)

## add external hypothesis

colData <- colData %>%
  mutate(external = fct_collapse(treatment,
                                 eggs = c("lay", "inc.d3", "inc.d9", "inc.d17", "prolong"),
                                 chicks = c("hatch", "n5", "n9", "extend" , "early" ),
                                 nest = c("bldg", "m.inc.d3",  "m.inc.d9",  "m.inc.d17",  "m.n2"),
                                 control = c("control"))) %>%
  drop_na()


colD
```





## Hypothesis

```{r hypothesis, eval = F, message = F, warning = F}

createDEGdfhypothesis <- function(variable, up, down, mytissue){
  
  res <- results(dds, contrast = c(variable, up, down), 
                 independentFiltering = T, alpha = 0.1)
  
  DEGs <- data.frame(gene = row.names(res),
                        padj = res$padj, 
                        logpadj = -log10(res$padj),
                        lfc = res$log2FoldChange,
                        sextissue = mytissue)
  DEGs <- na.omit(DEGs)
  DEGs <- DEGs %>%
    dplyr::mutate(direction = ifelse(DEGs$lfc > 0 & DEGs$padj < 0.1, 
                                     yes = up, no = ifelse(DEGs$lfc < 0 & DEGs$padj < 0.1, 
                                                           yes = down, no = "NS"))) %>% 
    dplyr::arrange(desc(lfc)) 
  
  DEGs$direction <- factor(DEGs$direction, levels = c(down, "NS", up)) 
  
  # write DEGsframe of only significant genes
  DEGs <- DEGs %>% dplyr::filter(direction != "NS")
  #print(str(DEGs))
  
  partialfilename = paste("_", down, "_", up, sep = "")
  myfilename = paste0("../results/DESeq2/hypothesis/", mytissue, partialfilename, "_DEGs.csv")
  
  write.csv(DEGs, myfilename, row.names = F)
  # return DEGs frome with all data, included NS genes
  #print(head(DEGs))
}  

for(i in levels(colData$sextissue)){
  
  newcolData <- subsetcolData2(colData, i)
  
  # save counts that match colData
  savecols <- as.character(newcolData$V1) 
  savecols <- as.vector(savecols) 
  
  newcountData <- countData %>% dplyr::select(one_of(savecols)) 
  
  dds <- DESeqDataSetFromMatrix(countData = newcountData,
                                colData = newcolData,
                                design = ~ hiloPRL + external )
  dds <- dds[rowSums(counts(dds) > 1) >= 10]  # filter more than sample with less 0 counts
  print(dds)
  print(dim(dds))
  dds <- DESeq(dds, parallel = TRUE) # Differential expression analysis
  
  vsd <- as.data.frame(assay(varianceStabilizingTransformation(dds, blind=FALSE)))
  
  myfilename = paste0("../results/DEseq2/hypothesis/", i, "_vsd.csv")
  write.csv(vsd, myfilename)
  
  createDEGdfhypothesis("hiloPRL", "hi", "lo", i)
  createDEGdfhypothesis("external", "chicks", "eggs", i)
  createDEGdfhypothesis("external", "chicks", "nest", i)
  createDEGdfhypothesis("external", "eggs", "nest", i)

}

```


```{r}
write.csv(colData, "../metadata/04_colData.csv", row.names = F)
```




