---
title: "04_DESeq_sexes"
output: md_document
---

```{r setup, message=F, comment=FALSE, warning=FALSE, results='hide'}

library(tidyverse)
library(DESeq2)
library(cowplot)
library(RColorBrewer)
library(pheatmap)
library(kableExtra)
library(viridis)
library(forcats)

library("BiocParallel")
register(MulticoreParam(4))

source("../R/functions.R")  # load custom functions 
source("../R/themes.R")  # load custom themes and color palletes

knitr::opts_chunk$set(fig.path = '../figures/sexes/', cache = TRUE)
```

## Starting with all the data

```{r readfiles}
# import "colData" which contains sample information and "countData" which contains read counts
a.colData <- read.csv("../metadata/00_samples.csv", header = T, row.names = 1)
a.countData <- read.csv("../results/00_counts.csv", header = T, row.names = 1)
geneinfo <- read.csv("../metadata/00_geneinfo.csv", row.names = 1)

# set levels
levels(a.colData$treatment)

a.colData$treatment <- factor(a.colData$treatment, levels = 
                             c("control", "bldg", "lay",
                               "inc.d3", "inc.d9", "inc.d17",
                               "hatch", "n5", "n9",
                              
                               "m.inc.d3", "m.inc.d8", "m.inc.d9",
                               "m.inc.d17",  "m.n2"  ,
                                "prolong", "extend" ))
                               
a.colData$sextissue <- as.factor(paste(a.colData$sex, a.colData$tissue, sep = "_"))

a.colData$lastday <- ifelse(grepl("m.inc.d3|m.inc.d9|m.inc.d17|m.n2", a.colData$treatment), "empty nest", 
                    ifelse(grepl("m.inc.d8|hatch|extend", a.colData$treatment),"chicks hatch",      
                     ifelse(grepl("n5", a.colData$treatment),"chicks early",
                     ifelse(grepl("n9", a.colData$treatment),"chicks later",
                     ifelse(grepl("control", a.colData$treatment),"control",
                     ifelse(grepl("bldg", a.colData$treatment),"nest building",
                     ifelse(grepl("prolong", a.colData$treatment),"eggs delay",
                      ifelse(grepl("lay", a.colData$treatment),"eggs lay",
                      ifelse(grepl("inc.d3", a.colData$treatment),"eggs early",
                     ifelse(grepl("inc.d9", a.colData$treatment),"eggs middle",
                    ifelse(grepl("inc.d17", a.colData$treatment),"eggs later", NA)))))))))))

a.colData$penultimate <-  ifelse(grepl("extend", a.colData$treatment),"eggs delay",  
                          ifelse(grepl("m.n2", a.colData$treatment),"chicks hatch",
                     ifelse(grepl("n5", a.colData$treatment),"chicks early",
                     ifelse(grepl("n9", a.colData$treatment),"chicks later",
                     ifelse(grepl("control", a.colData$treatment),"control",
                     ifelse(grepl("bldg|lay", a.colData$treatment),"nest building",
                     ifelse(grepl("prolong", a.colData$treatment),"eggs delay",
                      ifelse(grepl("inc.d3|m.inc.d3", a.colData$treatment),"eggs early",
                     ifelse(grepl("inc.d9|m.inc.d9|m.inc.d8", a.colData$treatment),"eggs middle",
                    ifelse(grepl("inc.d17|hatch", a.colData$treatment),"eggs later", NA))))))))))

a.colData$xlabel <- a.colData$treatment

levels(a.colData$xlabel) <-  c("control", "nest.building", "egg.lay",
                               "eggs.early", "eggs.early.remove", 
                               "eggs.mid", "eggs.mid.hatch", "eggs.mid.remove",
                               "eggs.end", "eggs.end.remove",
                               "chicks.hatch",  "chicks.hatch.remove"  ,
                               "chicks.mid", "eggs.delay", "eggs.delay.hatch", "chicks.end")


a.colData$lastday <- factor(a.colData$lastday, levels =  c("control", "nest building", "eggs lay",
                               "eggs early", "eggs middle",  "eggs later","eggs delay",
                               "chicks hatch", "chicks early",  "chicks later", "empty nest"))

a.colData$penultimate <- factor(a.colData$penultimate, levels =  c("control", "nest building",
                               "eggs early",  "eggs middle",  "eggs later",  "eggs delay",
                               "chicks hatch", "chicks early",  "chicks later"))

summary(a.colData[c(7,3,4,5,8,9, 10,11)])
```

## Run DESeq on all subsets of the data


```{r dds, cache = T}
dds.female_hypothalamus <- subsetDESeq(a.colData, a.countData, "female_hypothalamus")
dds.female_pituitary <- subsetDESeq(a.colData, a.countData, "female_pituitary" )
dds.female_gonad <- subsetDESeq(a.colData, a.countData, "female_gonad" )
dds.male_hypothalamus <- subsetDESeq(a.colData, a.countData, "male_hypothalamus" )
dds.male_pituitary <- subsetDESeq(a.colData, a.countData, "male_pituitary"  )
dds.male_gondad <- subsetDESeq(a.colData, a.countData, "male_gonad")
```


## Calculate and plot total DEGs


```{r returntotalDEGs, eval = T}
DEGs.female_hypothalamus <- returntotalDEGs(dds.female_hypothalamus)
DEGs.female_pituitary <- returntotalDEGs(dds.female_pituitary)
DEGs.female_gonad <- returntotalDEGs(dds.female_gonad)
DEGs.male_hypothalamus <- returntotalDEGs(dds.male_hypothalamus)
DEGs.male_pituitary <- returntotalDEGs(dds.male_pituitary)
DEGs.male_gondad <- returntotalDEGs(dds.male_gondad)

```

```{r plottotalDEGs, eval = T}
a <- plottotalDEGs(DEGs.female_hypothalamus, "female hypothalamus")
b <- plottotalDEGs(DEGs.female_pituitary, "female pituitary: hatch and day before are most unique")
c <- plottotalDEGs(DEGs.female_gonad, "female gonad")
d <- plottotalDEGs(DEGs.male_hypothalamus, "male hypothalamus: many parental contrasts yield 0 DEGs")
e <- plottotalDEGs(DEGs.male_pituitary, "male pituitary: peaks at hatch")
f <- plottotalDEGs(DEGs.male_gondad, "male gonad: most parental contrasts yield 0 DEGs")

myDEGs <- plot_grid(a + theme_noaxislabels,
          d + theme_siggenes,
          b + theme_noaxislabels,
          e + theme_noaxislabels,
          c + theme_noaxislabels,
          f + theme_noaxislabels,
          nrow = 3) 
myDEGs

pdf("../figures/sexes/plottotalDEGs-1.pdf", width = 12, height = 10)
plot(myDEGs)
dev.off()
```

## Plot only a subset of DEGs that relate to hypotheses


```{r characterization}
g <- plotserialDEGs(DEGs.female_hypothalamus, "Female hypothalamus", "#00A08A")
h <- plotserialDEGs(DEGs.female_pituitary, "Female pituitary", "#00A08A")
i <- plotserialDEGs(DEGs.female_gonad, "Female gonad", "#00A08A")
j <- plotserialDEGs(DEGs.male_hypothalamus, "Male hypothalamus", "#F98400")
k <- plotserialDEGs(DEGs.male_pituitary, "Male pituitary", "#F98400")
l <- plotserialDEGs(DEGs.male_gondad, "Male gonad", "#F98400")

mybarplots <- plot_grid(g, h , i , j ,k , l, nrow = 2) 
mybarplots

pdf("../figures/sexes/characterization-1.pdf", width = 10, height = 6)
plot(mybarplots)
dev.off()
```

```{r manipulationVcontrol}
versuscontrol <- c("control.m.inc.d3" , "control.m.inc.d8", "control.m.inc.d9", "control.m.inc.d17", 
                      "control.m.n2", "control.prolong", "control.extend")

manipulationVcontrol <- function(DEGs, mysubtitle, myfill){
  
  # subset to look within one tissue in one sex
  DEGs <- DEGs %>%
    dplyr::mutate(comparison = row.names(.)) %>%
    dplyr::filter(comparison %in% versuscontrol) 
  
  DEGs$comparison <- factor(DEGs$comparison, levels = versuscontrol)
  
  mybarplot <- ggplot(DEGs, aes(comparison)) +
    geom_bar(aes(weight = V3), fill = myfill) +
    theme_minimal(base_size = 8) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(subtitle = mysubtitle, y = "Number of DEGs", x = NULL) +
    #ylim(0, 5105) +
    geom_line(aes(x=comparison, y=V3, group = 1))

  return(mybarplot)
}

g <- manipulationVcontrol(DEGs.female_hypothalamus, "Female hypothalamus", "#00A08A")
h <- manipulationVcontrol(DEGs.female_pituitary, "Female pituitary", "#00A08A")
i <- manipulationVcontrol(DEGs.female_gonad, "Female gonad", "#00A08A")
j <- manipulationVcontrol(DEGs.male_hypothalamus, "Male hypothalamus", "#F98400")
k <- manipulationVcontrol(DEGs.male_pituitary, "Male pituitary", "#F98400")
l <- manipulationVcontrol(DEGs.male_gondad, "Male gonad", "#F98400")

mybarplots <- plot_grid(g, h , i , j ,k , l, nrow = 2) 
mybarplots

pdf("../figures/sexes/manipulationVcontrol-1.pdf", width = 10, height = 6)
plot(mybarplots)
dev.off()

```





## Calculate and plot principal components

```{r returnPCAs, eval=T}
pcas.female_hypothalamus <- returnPCAs(dds.female_hypothalamus)
pcas.female_pituitary <- returnPCAs(dds.female_pituitary)      
pcas.female_gonad <- returnPCAs(dds.female_gonad)
pcas.male_hypothalamus <- returnPCAs(dds.male_hypothalamus)
pcas.male_pituitary <- returnPCAs(dds.male_pituitary)
pcas.male_gondad <- returnPCAs(dds.male_gondad)
```

```{r pca, eval=T}
p1 <- plotPC1(pcas.female_hypothalamus, "female hypothalamus", "26% PC1 variance explained") 
p2 <- plotPC1(pcas.female_pituitary, "female pituitary", "11% PC1 variance explained")   
p3 <- plotPC1(pcas.female_gonad, "female gonad", "37% PC1 variance explained") 
p4 <- plotPC1(pcas.male_hypothalamus, "male hypothalamus", "28% PC1 variance explained") 
p5 <- plotPC1(pcas.male_pituitary, "male pituitary" , "11% PC1 variance explained") 
p6 <- plotPC1(pcas.male_gondad, "male gonad", "14% PC1 variance explained") 

mylegend <- get_legend(p1)

allPC1s <- plot_grid(p1 + theme_nolegend + ylim(c(-35,35)), 
                     p4 + theme_nolegend + ylim(c(-35,35)), 
                     p2 + theme_nolegend + ylim(c(-35,35)),
                     p5 + theme_nolegend + ylim(c(-35,35)),
                     p3 + theme_nolegend + ylim(c(-35,35)) ,
                     p6 + theme_nolegend + ylim(c(-35,35)) ,
                     ncol = 2)

pc1 <- plot_grid(allPC1s, mylegend,  nrow = 2, rel_heights = c(1.0, 0.15))
pc1

pdf("../figures/sexes/pca-1.pdf", width = 12, height = 14)
plot(pc1)
dev.off()

p11 <- plotPC2(pcas.female_hypothalamus, "female hypothalamus", "9% PC2 variance explained") 
p12 <- plotPC2(pcas.female_pituitary, "female pituitary", "8% PC2 variance explained")   
p13 <- plotPC2(pcas.female_gonad, "female gonad", "12 PC2 variance explained") 
p14 <- plotPC2(pcas.male_hypothalamus, "male hypothalamus", "9% PC2 variance explained") 
p15 <- plotPC2(pcas.male_pituitary, "male pituitary" , "9% PC2 variance explained") 
p16 <- plotPC2(pcas.male_gondad, "male gonad", "10% PC2 variance explained") 


allPC2 <- plot_grid(p11 + theme_nolegend + ylim(c(-35,35)), 
                     p14 + theme_nolegend + ylim(c(-35,35)), 
                     p12 + theme_nolegend + ylim(c(-35,35)),
                     p15 + theme_nolegend + ylim(c(-35,35)),
                     p13 + theme_nolegend + ylim(c(-35,35)) ,
                     p16 + theme_nolegend + ylim(c(-35,35)) ,
                     ncol = 2)

pc2 <- plot_grid(allPC2, mylegend,  nrow = 2, rel_heights = c(1.0, 0.15))
pc2

pdf("../figures/sexes/pca-2.pdf", width = 12, height = 14)
plot(pc2)
dev.off()


```

## heamap with minimum pvalue

```{r pheatmap, eval = F}
makepheatmap(dds.female_hypothalamus, a.colData, "female hypothalamus")
makepheatmap(dds.female_pituitary, "female pituitary")
makepheatmap(dds.female_gonad, "female gonad")
makepheatmap(dds.male_hypothalamus, "male hypothalamus")
makepheatmap(dds.male_pituitary, "male pituitary")
makepheatmap(dds.male_gondad, "male gonad")        
```

## make col data for candidate genes and heatmaps

```{r coldata, eval =T}
colData.female_hypothalamus <- subsetcolData(a.colData,  "female_hypothalamus")
colData.female_pituitary <- subsetcolData(a.colData,  "female_pituitary" )
colData.female_gonad <- subsetcolData(a.colData,  "female_gonad" )
colData.male_hypothalamus <- subsetcolData(a.colData,  "male_hypothalamus" )
colData.male_pituitary <- subsetcolData(a.colData,  "male_pituitary"  )
colData.male_gondad <- subsetcolData(a.colData,  "male_gonad")
```


## candidate genes

```{r candidates, eval =F}
plotcandidates(dds.female_hypothalamus, colData.female_hypothalamus, "female hypothalamus")
plotcandidates(dds.female_pituitary, colData.female_pituitary,  "female pituitary")
plotcandidates(dds.female_gonad, colData.female_gonad,  "female gonad")
plotcandidates(dds.male_hypothalamus, colData.male_hypothalamus, "male hypothalamus")
plotcandidates(dds.male_pituitary,  colData.male_pituitary, "male pituitary")
plotcandidates(dds.male_gondad, colData.male_hypothalamus , "male gonad")
```


## new heat maps

```{r correlationheatmaps, eval = F}
plotcorrelationheatmaps(dds.female_hypothalamus, colData.female_hypothalamus ,"female hypothalamus: hatch, nest bldg., lay and day-before-hatch cluster")
plotcorrelationheatmaps(dds.female_pituitary, colData.female_pituitary, "female pituitary: clustering suggests an internal clock effect")
plotcorrelationheatmaps(dds.female_gonad, colData.female_gonad,  "female gonad: highly correlated across incubation and early nestling care")
plotcorrelationheatmaps(dds.male_hypothalamus, colData.male_hypothalamus, "male hypothalamus: 100% correlated across most parental care stages")
plotcorrelationheatmaps(dds.male_pituitary, colData.male_pituitary, "male pituitary: non-parental males are most different")
plotcorrelationheatmaps(dds.male_gondad, colData.male_gondad, "male gonad: non-parental males are most different")
```
