---
title: "04_limma_gon_F"
output: md_document
---

This anlaysis will _exclude_ the control timepoint and will example males and females separately.

```{r}
library(tidyverse)
library(limma)
library(Glimma)
library(edgeR)
library(kableExtra)
library(cowplot)

# load custom functions
source("../R/functions.R") 

knitr::opts_chunk$set(fig.path = '../figures/gon_F/',cache=TRUE)
```

# Females first

```{r read}
# import "colData" which contains sample information and "countData" which contains read counts
colData <- read.csv("../results/00_colData_characterization.csv", header = T, row.names = 1)
countData <- read.csv("../results/00_countData_characterization.csv", header = T, row.names = 1)
geneinfo <- read.csv("../results/00_geneinfo.csv", row.names = 1)
```

```{r filter}
colData <- colData %>%
  dplyr::filter(grepl('gonad', tissue)) %>%
  dplyr::filter(treatment != "control") %>%
  dplyr::filter(sex == "female") %>%
  droplevels()
row.names(colData) <- colData$V1

# print sample sizes
colData %>% select(treatment, tissue)  %>%  summary()

savecols <- as.character(colData$V1) 
savecols <- as.vector(savecols) 
countData <- countData %>% dplyr::select(one_of(savecols)) 

# check that row and col lenghts are equal
ncol(countData) == nrow(colData)
```

Then, I followed the steps from <https://github.com/macmanes-lab/RockDove/blob/master/parental_care/parental_analysis.Rmd>.

```{r edgeR}
# create a large DGEList with 3 elements
parentalobject <- DGEList(counts=countData, genes=geneinfo, group=colData$group)

# transform raw counts to countspermillion
cpms <- cpm(parentalobject)

# calculate number of lowly lowly expressed genes and remove them
table(rowSums(parentalobject$counts==0)==10)
keep_genes <- rowSums(cpms >= 1) >= 10
dge <- parentalobject[keep_genes, ]

# specific the design
parentaldesign <- model.matrix(~ colData$group )
colnames(parentaldesign) <- levels(colData$group)

# The TMM normalization
parentalobject <- calcNormFactors(parentalobject)
parentalobject <- estimateCommonDisp(parentalobject)
parentalobject <- estimateTagwiseDisp(parentalobject)
parentalobject <- estimateDisp(parentalobject, parentaldesign)
parentalobject <- estimateGLMCommonDisp(parentalobject, parentaldesign, verbose=TRUE)
parentalobject <- estimateGLMTrendedDisp(parentalobject, parentaldesign)
parentalobject <- estimateGLMTagwiseDisp(parentalobject, parentaldesign)

#  perform likelihood ratio test and thresholded testing
fit <- glmFit( parentalobject, parentaldesign, robust=T)
tr <- glmTreat(fit, lfc = 1)
topTags(tr)
head(tr$table)
```


# plotMDS (multidimential scaling)

```{r plotMDS}
levels(colData$treatment)
col.treatment <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6")[colData$treatment]
myfill <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6")

plotMDS(parentalobject, cex = 0.5, labels = colData$treatment, col=col.treatment)
title("Female Gonad MDS 1v2")
plotMDS(parentalobject, cex = 0.5, labels = colData$treatment, col=col.treatment, dim=c(3,4))
title("Female Gonad MDS 3v4")
plotMDS(parentalobject, cex = 0.5, labels = colData$treatment, col=col.treatment, dim=c(5,6))
title("Female Gonad MDS 5v6")
```

For color coding, I used this tutorial for guidance <https://combine-australia.github.io/RNAseq-R/06-rnaseq-day1.html>.


# specify contrasts and make MA plots

```{r MDSplots}
# view all levels
levels(colData$group)

# subset of conrasts - sex specific comparing hatch to lay
my.contrasts <- makeContrasts(
	         FG_BL = female.gonad.bldg - female.gonad.lay,
	         FG_Li3 = female.gonad.lay - female.gonad.inc.d3,
	         FG_i3i9 = female.gonad.inc.d3 - female.gonad.inc.d9,
	         FG_i9i17 = female.gonad.inc.d9 - female.gonad.inc.d17,
	         FG_i17H = female.gonad.inc.d17 - female.gonad.hatch,
	         FG_Hn5 = female.gonad.hatch -  female.gonad.n5,
	         FG_n5n9 = female.gonad.n5 - female.gonad.n9,
	         
	         FG_Bi3 = female.gonad.bldg - female.gonad.inc.d3,
	         FG_Bi9 = female.gonad.bldg - female.gonad.inc.d9,
	         FG_Bi17 = female.gonad.bldg - female.gonad.inc.d17,
	         FG_BH = female.gonad.bldg - female.gonad.hatch,
	         FG_Bn5 = female.gonad.bldg - female.gonad.n5,
	         FG_Bn9 = female.gonad.bldg - female.gonad.n9,
	         
	         FG_Li9 = female.gonad.lay - female.gonad.inc.d9,
           FG_Li17 = female.gonad.lay - female.gonad.inc.d17, 
	         FG_LH = female.gonad.lay - female.gonad.hatch,
	         FG_Ln5 = female.gonad.lay - female.gonad.n5,
	         FG_Ln9 = female.gonad.lay - female.gonad.n9,

	         FG_i3i17 = female.gonad.inc.d3 - female.gonad.inc.d17,
	         FG_i3H = female.gonad.inc.d3 - female.gonad.hatch,
	         FG_i3n5 = female.gonad.inc.d3 - female.gonad.n5,
	         FG_i3n9 = female.gonad.inc.d3 - female.gonad.n9,
	        
	         FG_i9H = female.gonad.inc.d9 - female.gonad.hatch,
	         FG_i9n5 = female.gonad.inc.d9 - female.gonad.n5,
	         FG_i9n9 = female.gonad.inc.d9 - female.gonad.n9,
	         
	         FG_i17n5 = female.gonad.inc.d17 - female.gonad.n5,
	         FG_i17n9 = female.gonad.inc.d17 - female.gonad.n9,
	         
	         FG_Hn9 = female.gonad.hatch -  female.gonad.n9,
	         
levels=parentaldesign)

colnames(my.contrasts)

# create a list with all the two way contrasts

mycontrasts <- colnames(my.contrasts)
mycontrasts

# use the printplotcontrasts function to print summary stats and a volcano plot

for(i in mycontrasts){
  printplotcontrasts(i)
}

```


```{r volcanoplots}
for(i in mycontrasts){
  plotVolcanos(i)
}
```

