---
title: "06_DESeqALL"
output: md_document
---

```{r setup, include = FALSE}

library(tidyverse)
library(DESeq2)
library(cowplot)
library(pheatmap)
library(viridis)
library(forcats)
library(caret) # LDA analysis
library(MASS) # LDA analysis
library(ggtext) # for pretty plots
library(ctsGE)

library(BiocParallel)
register(MulticoreParam(6))

source("../R/functions.R")  # load custom functions 
source("../R/themes.R")  # load custom themes and color palletes
source("../R/icons.R")  # for images

knitr::opts_chunk$set(fig.path = '../figures/DESeqAll/', cache = T,  message=F, comment=F, warning=F)
```

# Warning: This script takes a very long time to run. 

DESeq2 was not designed to run on 300 samples. But, I really like it, so I do it anyways. Some of these commands take like 15 min to run using 6 cores. 

## DEseq2 on all chaacterization and manipulations

```{r readfiles}
# import "colData" which contains sample information and "countData" which contains read counts
countData <- read.csv("../results/00_counts.csv", header = T, row.names = 1)
geneinfo <- read.csv("../metadata/00_geneinfo.csv", row.names = 1)
head(geneinfo)

# craete variable that will be critical for subset later on
colData <- read.csv("../metadata/00_samples.csv", header = T, row.names = 1)
colData$sextissue <- as.factor(paste(colData$sex, colData$tissue, sep = "_"))
colData$treatment <- factor(colData$treatment, levels = alllevels3)
colData$tissue <- factor(colData$tissue, levels = tissuelevels)
levels(colData$treatment)
```



```{r pitdfs, eval=T}
dds.pituitary <- subsetDESeq2(colData,  countData, c("female_pituitary","male_pituitary"))

```

```{r pitvsd, eval=T}
vsd <- as.data.frame(assay(vst(dds.pituitary, blind=FALSE)))
write.csv(vsd, "../results/06_pitallvsd.csv")

```


```{r eval=T}
control.bldg <- createDEGdfsave(dds.pituitary, "treatment", "bldg", "control", "pituitary")
```

```{r  eval=T}
bldg.lay <- createDEGdfsave(dds.pituitary, "treatment", "lay", "bldg", "pituitary")
```

```{r  eval=T}
lay.inc.d3 <- createDEGdfsave(dds.pituitary, "treatment", "inc.d3", "lay", "pituitary") 
```

```{r  eval=T}
inc.d3.inc.d9 <- createDEGdfsave(dds.pituitary,  "treatment", "inc.d9", "inc.d3", "pituitary") 
```

```{r  eval=T}
inc.d9.inc.d17 <- createDEGdfsave(dds.pituitary, "treatment", "inc.d17", "inc.d9", "pituitary")
```

```{r  eval=T}
inc.d17.hatch <- createDEGdfsave(dds.pituitary, "treatment", "hatch", "inc.d17", "pituitary") 
```

```{r  eval=T}
hatch.n5 <- createDEGdfsave(dds.pituitary, "treatment", "n5", "hatch", "pituitary") 
```

```{r  eval=T}
n5.n9 <- createDEGdfsave(dds.pituitary, "treatment", "n9", "n5", "pituitary") 
```

```{r eval=T}
sex <- createDEGdfsave(dds.pituitary, "sex", "male", "female", "pituitary") 
```

```{r  eval=T}
inc.d3.m.inc.d3 <- createDEGdfsave(dds.pituitary, "treatment", "m.inc.d3", "inc.d3", "pituitary")
```

```{r  eval=T}
inc.d9.m.inc.d9 <- createDEGdfsave(dds.pituitary, "treatment", "m.inc.d9", "inc.d9", "pituitary")
```

```{r  eval=T}
inc.d17.m.inc.d17 <- createDEGdfsave(dds.pituitary, "treatment", "m.inc.d17", "inc.d17", "pituitary")
```

```{r  eval=T}
hatch.m.n2 <- createDEGdfsave(dds.pituitary, "treatment", "m.n2", "hatch", "pituitary")
```

```{r  eval=T}
inc.d9.m.inc.d8 <- createDEGdfsave(dds.pituitary, "treatment", "m.inc.d8", "inc.d9", "pituitary")
```

```{r  eval=T}
hatch.m.inc.d8 <- createDEGdfsave(dds.pituitary, "treatment", "hatch", "m.inc.d8", "pituitary")
```

```{r  eval=T}
inc.d17.prolong <- createDEGdfsave(dds.pituitary, "treatment", "prolong", "inc.d17", "pituitary")
```

```{r  eval=T}
hatch.prolong <- createDEGdfsave(dds.pituitary, "treatment", "hatch", "prolong", "pituitary")
```

```{r  eval=T}
hatch.extend <- createDEGdfsave(dds.pituitary, "treatment", "extend", "hatch", "pituitary")
```

```{r  eval=T}
n5.extend <- createDEGdfsave(dds.pituitary, "treatment", "n5", "extend", "pituitary")
```

```{r volcanos-pituitary, fig.height= 6, fig.width=6}
a <- plot.volcano(sex, "sex", "male", "female", colorsvolcano)
b <- plot.volcano(control.bldg, "treatment", "bldg", "control", colorsvolcano)
c <- plot.volcano(bldg.lay, "treatment", "lay", "bldg", colorsvolcano)
d <- plot.volcano(lay.inc.d3, "treatment", "inc.d3", "lay", colorsvolcano) 
e <- plot.volcano(inc.d3.inc.d9, "treatment", "inc.d9", "inc.d3", colorsvolcano) 
f <- plot.volcano(inc.d9.inc.d17, "treatment", "inc.d17", "inc.d9", colorsvolcano)
g <- plot.volcano(inc.d17.hatch, "treatment", "hatch", "inc.d17", colorsvolcano) 
h <- plot.volcano(hatch.n5, "treatment", "n5", "hatch", colorsvolcano) 
i <- plot.volcano(n5.n9, "treatment", "n9", "n5", colorsvolcano) 

j <- plot.volcano(inc.d3.m.inc.d3 , "treatment",   "m.inc.d3", "inc.d3",   colorsvolcano)  
k <- plot.volcano(inc.d9.m.inc.d9, "treatment",  "m.inc.d9", "inc.d9" , colorsvolcano) 
l <- plot.volcano(inc.d17.m.inc.d17 , "treatment",  "m.inc.d17", "inc.d17" , colorsvolcano) 
m <- plot.volcano(hatch.m.n2 , "treatment",   "m.n2", "hatch", colorsvolcano) 

n <- plot.volcano(inc.d9.m.inc.d8 , "treatment",   "m.inc.d8", "inc.d9"  , colorsvolcano) 
o <- plot.volcano(hatch.m.inc.d8 , "treatment",    "hatch", "m.inc.d8"  , colorsvolcano)  
p <- plot.volcano(inc.d17.prolong , "treatment",   "prolong", "inc.d17",  colorsvolcano)  
q <- plot.volcano(hatch.prolong , "treatment",  "hatch", "prolong", colorsvolcano) 
r <- plot.volcano(hatch.extend , "treatment",  "extend", "hatch" , colorsvolcano)  
s <- plot.volcano(n5.extend , "treatment",  "extend", "n5", colorsvolcano)  

char <- plot_grid(
          b + theme(axis.title.x = element_blank(), axis.text.x = element_blank()),
          c + theme(axis.title = element_blank(), axis.text = element_blank()) ,
          d + theme(axis.title = element_blank(), axis.text = element_blank()), 
          f + theme(axis.title = element_blank(), axis.text = element_blank()),
          g + theme(axis.title = element_blank(), axis.text = element_blank()),
          h + theme(axis.title = element_blank(), axis.text = element_blank()),
          i + theme(axis.title = element_blank(), axis.text = element_blank()),
          nrow = 1, rel_widths = c(1.3,1,1,1,1,1,1))

remove <- plot_grid( 
          a + theme(axis.title.x = element_blank(), axis.text.x = element_blank()),
          NULL, 
          j + theme(axis.title = element_blank(), axis.text = element_blank()) , 
          k + theme(axis.title = element_blank(), axis.text = element_blank()) , 
          l + theme(axis.title = element_blank(), axis.text = element_blank()) , 
          m + theme(axis.title = element_blank(), axis.text = element_blank()), 
          NULL, nrow = 1, rel_widths = c(1.3, 1, 1,1,1,1,1))


timing <- plot_grid( 
          n , 
          o + theme(axis.title.y = element_blank(), axis.text.y = element_blank())+
            labs(x = "Log fold change,")   , 
          NULL,
          p + theme(axis.title.y = element_blank(), axis.text.y = element_blank()) +
            labs(x = "pituitary") , 
          q + theme(axis.title.y = element_blank(), axis.text.y = element_blank()) ,
           NULL,
          r + theme(axis.title.y = element_blank(), axis.text.y = element_blank()) , 
          s + theme(axis.title.y = element_blank(), axis.text.y = element_blank()),
            nrow = 1, rel_widths = c(1.3,1, 0.5, 1, 1, 0.5, 1, 1)) 

charicons <- png::readPNG("../figures/images/DoveParentsRNAseq_volcanos-char.png")
charicons <-  grid::rasterGrob(charicons, interpolate=TRUE)

removeicons <- png::readPNG("../figures/images/DoveParentsRNAseq_volcanos-removal.png")
removeicons <-  grid::rasterGrob(removeicons, interpolate=TRUE)

timingicons <- png::readPNG("../figures/images/DoveParentsRNAseq_volcanos-timing.png")
timingicons <-  grid::rasterGrob(timingicons, interpolate=TRUE)

plot_grid(charicons, char, removeicons, remove, timingicons, timing, nrow = 6, rel_heights = c(0.9,1,0.9,1,0.9,1.2))
```