---
title: "06_wrangle"
output: md_document
---
  
  
```{r setup}
library(tidyverse)
library(readr)
library(corrr)
library(forcats)

source("../R/themes.R")
source("../R/functions.R")
source("../R/genelists.R")
```

## Wrangle data for hyotheses testing

```{r data}
# col data with internal (hiloPRL) and external  hypothesese
colData <- read_csv("../metadata/04_colData.csv") %>%
  column_to_rownames(var = "V1")
tail(colData)
```

### variance stabilized gene expression  (vsd) 

```{r allvsd, message = F, warning  = F}
vsd_path <- "../results/DEseq2/treatment/"   # path to the data
vsd_files <- dir(vsd_path, pattern = "*vsd.csv") # get file names
vsd_pathfiles <- paste0(vsd_path, vsd_files)
vsd_files

## before pivoting, check names of df with
## head(names(allvsd)) and tail(names(allvsd))

allvsd <- vsd_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name")  %>% 
  dplyr::rename("gene" = "X1") %>% 
  pivot_longer(cols = L.G118_female_gonad_control:y98.o50.x_male_pituitary_inc.d3, 
               names_to = "samples", values_to = "counts") 

allvsd %>%  select(-file_name) %>% head()

colData %>% filter(tissue == "gonads", treatment == "bldg")  
  
allvsd %>% filter(samples == "blk11.x_female_gonad_bldg")
```




## All DEGs (but currently only char DEGs)

```{r allDEG}
DEG_path <- "../results/DEseq2/hypothesis/"   # path to the data
DEG_files <- dir(DEG_path, pattern = "*DEGs") # get file names
DEG_pathfiles <- paste0(DEG_path, DEG_files)
#DEG_files

allDEG <- DEG_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name") %>% 
  mutate(DEG = sapply(strsplit(as.character(file_name),'./results/DEseq2/hypothesis/'), "[", 2))  %>% 
  mutate(DEG = sapply(strsplit(as.character(DEG),'_DEGs.csv'), "[", 1))  %>% 
  mutate(sex = sapply(strsplit(as.character(sextissue),'\\_'), "[", 1)) %>%
  mutate(tissue = sapply(strsplit(as.character(sextissue),'\\_'), "[", 2)) %>%
  select(DEG, sex, tissue, direction, everything())   %>%
  mutate(down = sapply(strsplit(as.character(DEG),'\\_'), "[", 3)) %>%
  mutate(up = sapply(strsplit(as.character(DEG),'\\_'), "[", 4)) %>%
  mutate(comparison = paste(down,up, sep = "_")) %>%
  mutate(sex = sapply(strsplit(as.character(sextissue),'\\_'), "[", 1)) %>%
  mutate(tissue = sapply(strsplit(as.character(sextissue),'\\_'), "[", 2)) %>%
  dplyr::select(sex,tissue,comparison, direction, gene, lfc, padj, logpadj)  %>%
  mutate(tissue = factor(tissue)) %>% 
  drop_na()
head(allDEG)
```


## gene lists


```{r genelists}




## "internal clock" PRL genes

hilogenes <- allDEG %>%
  filter(comparison == "lo_hi")  %>%
  drop_na() %>%
  arrange(padj) %>% 
  top_n(20) %>% pull(gene)

## external environment gens 
eggchickgenes <- allDEG %>%
  filter(comparison != "lo_hi")  %>%
  drop_na() %>%
  arrange(padj)  %>% 
  top_n(20) %>% pull(gene)

```

### vsd for all and candidate, hypothesis, and data-driven genes


```{r candidatevsd}
# all list of candidate gens accumlated here

candidategenes <- c(parentalcaregenes, WGCNAgenes, hilogenes, eggchickgenes, 
                    suszynskaagenes, shaidgenes)

getcandidatevsd2 <- function(whichgenes, whichtissue, whichsex){
  candidates  <- allvsd %>%
    filter(gene %in% whichgenes) %>%
    dplyr::mutate(sextissue = sapply(strsplit(file_name, '_vsd.csv'), "[", 1)) %>%
    dplyr::mutate(sextissue = sapply(strsplit(sextissue, '../results/DEseq2/treatment/'), "[", 2)) %>%
    dplyr::mutate(sex = sapply(strsplit(sextissue, '\\_'), "[", 1),
                  tissue = sapply(strsplit(sextissue, '\\_'), "[", 2),
                  treatment = sapply(strsplit(samples, '\\_'), "[", 4)) %>%
    dplyr::mutate(treatment = sapply(strsplit(treatment, '.NYNO'), "[", 1)) %>%
    dplyr::select(sex, tissue, treatment, gene, samples, counts) %>%
    filter(tissue == whichtissue, sex %in% whichsex)  %>%
    drop_na()
  #candidates$treatment <- factor(candidates$treatment, levels = alllevels)
  return(candidates)
}

hypvsd <- getcandidatevsd2(candidategenes, "hypothalamus", sexlevels)
pitvsd <- getcandidatevsd2(candidategenes, "pituitary", sexlevels)
gonvsd <- getcandidatevsd2(candidategenes, "gonad", sexlevels)

candidatevsd <- rbind(hypvsd, pitvsd)
candidatevsd <- rbind(candidatevsd, gonvsd) 
candidatevsd <- candidatevsd %>%
  mutate(treatment = factor(treatment)) %>%
  mutate(treatment = fct_recode(treatment, "early" = "m.inc.d8" )) %>%
  mutate(treatment = factor(treatment, alllevels))
tail(candidatevsd)
```


```{r writefiles}
write.csv(candidatevsd, "../results/06_candidatevsd.csv", row.names = F)
write.csv(allDEG, "../results/06_allDEG.csv", row.names = F)
```

