---
title: "07_DESeq_ALL"
output: md_document
---

```{r setup, message=F, comment=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(DESeq2)
library(cowplot)
library(RColorBrewer)
library(pheatmap)
library(kableExtra)
library(viridis)

# load custom functions  
source("../R/functions.R") 

knitr::opts_chunk$set(fig.path = '../figures/ALL/',cache=TRUE)
```


```{r readfiles}
# import "colData" which contains sample information and "countData" which contains read counts
m.colData <- read.csv("../results/00_colData_manipluation.csv", header = T, row.names = 1)
m.countData <- read.csv("../results/00_countData_manipluation.csv", header = T, row.names = 1)

c.colData <- read.csv("../results/00_colData_characterization.csv", header = T, row.names = 1)
c.countData <- read.csv("../results/00_countData_characterization.csv", header = T, row.names = 1)  

a.colData <- rbind(m.colData, c.colData)
a.countData <- cbind(m.countData, c.countData)

a.colData$sextissue <- as.factor(paste(a.colData$sex, a.colData$tissue, sep = "_"))
```

```{r factors} 
a.colData$treatment <- factor(a.colData$treatment, levels = 
                              c("control", "bldg", "lay", "inc.d3", "inc.d9", 
                                "inc.d17", "hatch", "n5", "n9",
                                "m.inc.d3", "m.inc.d8", "m.inc.d9",
                                "m.inc.d17",  "prolong", "extend", "m.n2"))
```


```{r althings}

for (eachgroup in levels(a.colData$sextissue)){
  
  print(eachgroup)
  
  colData <- a.colData %>%
      dplyr::filter(sextissue == eachgroup) %>%
      droplevels()
  row.names(colData) <- colData$V1
  
  savecols <- as.character(colData$V1) 
  savecols <- as.vector(savecols) 

  countData <- a.countData %>% dplyr::select(one_of(savecols)) 

  # check that row and col lenghts are equal
  print(ncol(countData) == nrow(colData))

  dds <- DESeqDataSetFromMatrix(countData = countData,
                              colData = colData,
                              design = ~ treatment )
  dds <- dds[ rowSums(counts(dds)) > 2, ] ## pre-filter genes 
  dds <- DESeq(dds) # Differential expression analysis
  vsd <- vst(dds, blind=FALSE) # variance stabilized 

#create list of groups
a <- levels(colData$treatment)
b <- levels(colData$treatment)

# comapre all contrasts, save to datafrmes
dat=data.frame()
for (i in a){
  for (j in b){
    if (i != j) {
      k <- paste(i,j, sep = "") #assigns usique rownames
      dat[k,1]<-i               
      dat[k,2]<-j
      dat[k,3]<- numDEGs(i,j) #caluculates number of DEGs
    }
  }
}

head(dat)

# widen data to create table of degs
rownames(dat) <- NULL #remove row names
data_wide <- spread(dat, V2, V3)
print(data_wide) 

#dat$V1 <- factor(dat$V1, levels = 
#                              c("control", "bldg", "lay", "inc.d3", "inc.d9", 
#                                "inc.d17", "hatch", "n5", "n9",
#                                "m.inc.d3", "m.inc.d8", "m.inc.d9",
#                                "m.inc.d17",  "prolong", "extend", "m.n2"))
dat$V2 <- dat$V1

allcontrasts <- dat %>%
  ggplot( aes(V1, V2)) +
    geom_tile(aes(fill = V3)) +
    scale_fill_viridis(na.value="#FFFFFF00", 
                     limits = c(0, 6000),
                     breaks = c(0, 1000, 2000, 3000, 4000, 5000, 6000)) + 
    xlab(" ") + ylab("Timepoint") +
    labs(fill = "# of DEGs",
         subtitle = eachgroup)
plot(allcontrasts)

# create the dataframe using my function pcadataframe
pcadata <- pcadataframe(vsd, intgroup=c("treatment"), returnData=TRUE)
percentVar <- round(100 * attr(pcadata, "percentVar"))
percentVar

pca12 <- ggplot(pcadata, aes(PC1, PC2,color = treatment)) + 
  geom_point(size = 2, alpha = 1) +
  stat_ellipse(type = "t") +
  xlab(paste0("PC1: ", percentVar[1],"% variance")) +
  ylab(paste0("PC2: ", percentVar[2],"% variance")) +
  theme_cowplot(font_size = 8, line_size = 0.25) +
  labs(subtitle = eachgroup)
print(pca12)

print(summary(aov(PC1 ~ treatment, data=pcadata)))
print(TukeyHSD(aov(PC1 ~ treatment, data=pcadata), which = "treatment"))

print(summary(aov(PC2 ~ treatment, data=pcadata))) 
print(TukeyHSD(aov(PC2 ~ treatment, data=pcadata), which = "treatment")) 

pca34 <- ggplot(pcadata, aes(PC3, PC4,color = treatment)) + 
  geom_point(size = 2, alpha = 1) +
  stat_ellipse(type = "t") +
  xlab(paste0("PC3: ", percentVar[3],"% variance")) +
  ylab(paste0("PC4: ", percentVar[4],"% variance")) +
  theme_cowplot(font_size = 8, line_size = 0.25) +
  labs(subtitle = eachgroup)
print(pca34)

# see http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#heatmap-of-the-count-matrix
sampleDists <- dist(t(assay(vsd)))

sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- NULL
colnames(sampleDistMatrix) <- colData$treatment
colors <- colorRampPalette(brewer.pal(9, "Blues"))(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors,
         fontsize = 6, 
         main = eachgroup)
}
```
