---
title: "hormones"
output: md_document
---

```{r setup}
library(tidyverse)
library(cowplot)
library(readxl)
library(modelr)
library(lubridate)
library(ggsignif)
library(apaTables)

source("../R/themes.R")  # load custom themes and color palletes
source("../R/icons.R")

knitr::opts_chunk$set(fig.path = '../figures/hormones/',message=F, warning=FALSE, cache = T)
```

```{r}
colData  <- read_csv("../metadata/00_birds.csv") %>%
  mutate(RNAseq = "RNAseq",
         bird_id = bird)  %>%
   select(-X1, -bird)
colData
```



```{r wrangle-prolactin}
prolactin <- read_excel("../results/Pigeon prolactin concentrations juil 2018.xlsx", sheet = 1) %>% 
  filter(Study %in% c("Baseline", "ParentalCare")) %>%
    dplyr::mutate(sex = fct_recode(Sex,
                            "female" = "f",
                            "male" = "m"),
           treatment = fct_recode(Treatment,
                            "hatch" = "Hatch",
                            "inc.d17" = "Inc_d17",
                            "inc.d17" = "inc_d17",
                            "inc.d3" = "Inc_d3",
                             "inc.d3" = "inc_d3",
                            "inc.d9" = "Inc_d9",
                             "inc.d9" = "inc_d9",
                            "m.inc.d9" = "M_Inc9",
                            "m.inc.d9" = "M_inc9",
                            "m.inc.d3" = "M_Inc3",
                            "m.inc.d8" = "M_Inc8",
                            "m.inc.d8" = "M_inc8",
                            "m.inc.d17" = "M_Inc17",
                            "m.n2" = "M_hatch",
                            "control" = "baseline",
                            "n5" = "N5", 
                            "n9" = "N9"),
           study = fct_collapse(treatment,
                                 characterization = charlevels,
                                 manipulation = maniplevels1)) %>%
          dplyr::rename("plasma_conc" = "Prolactin ng/mL") %>%
          mutate(bird_id = gsub("[[:punct:]]", "." , ColorBands)) %>% 
          dplyr::mutate(hormone = "prolactin") %>% 
          dplyr::select(study, treatment, sex, bird_id, hormone, plasma_conc)  %>% 
          drop_na()
head(prolactin)

```



```{r wrangle-steroids}
PETC <- read_excel("../results/hormones.xlsx", sheet = 1)  %>% 
              dplyr::rename(corticosterone = cort, progesterone = p4,
                            estradiol = e2,  testosterone = t) %>% 
               dplyr::mutate(treatment = fct_recode(treatment...3,
                            "inc.d17" = "incd17",
                            "inc.d3" = "incd3",
                            "inc.d9" = "incd9",
                            "m.inc.d9" = "minc9",
                            "m.inc.d3" = "minc3",
                            "m.inc.d8" = "minc8",
                            "m.inc.d17" = "minc17",
                            "m.n2" = "m hatch",
                            "control" = "baseline")) %>%
                dplyr::filter(treatment %in% alllevels2) %>%   
                dplyr::mutate(sex = fct_recode(sex,
                            "female" = "f",
                            "male" = "m"),
                       study = fct_collapse(treatment,
                                characterization = charlevels,
                                manipulation = maniplevels1)) %>% 
              dplyr::mutate(bird_id = gsub("[[:punct:]]", "." , id)) %>% 
              dplyr::select(bird_id, treatment, sex, study, 
                            corticosterone, estradiol, testosterone, progesterone) %>% 
              pivot_longer(cols = corticosterone:progesterone,
                           names_to = "hormone", values_to = "plasma_conc",
                           values_drop_na = TRUE) %>% 
              drop_na() %>% droplevels()  
head(PETC)
```


```{r combine-clean-split}
hormones <- rbind(prolactin, PETC)

hormones$okay <- ifelse(hormones$hormone == "corticosterone" & hormones$plasma_conc > 30, "bad",
                    ifelse(hormones$hormone == "progesterone" & hormones$plasma_conc > 5, "bad", 
                           ifelse(hormones$hormone == "prolactin" & hormones$plasma_conc > 150, "bad", 
                        ifelse(hormones$hormone == "testosterone" & hormones$sex == "female", "bad",
                               ifelse(hormones$hormone == "estradiol" & hormones$sex == "male", "bad", "okay")))))
hormones <- hormones %>% filter(okay == "okay") %>% droplevels() %>% select(-okay)

write.csv(hormones, "../results/hormones.csv", row.names = F)

# make a winder one for correlations
hormoneswide <- hormones %>% pivot_wider(names_from = "hormone", values_from = "plasma_conc", 
                                         values_fn = list(plasma_conc = mean))
hormoneswide$treatment <- factor(hormoneswide$treatment, levels = alllevels)
head(hormoneswide)

# for facet wrapping
hormones <- left_join(hormones, birds)

hormones$treatment <- factor(hormones$treatment, levels = alllevels)


hormones$hormone <- factor(hormones$hormone, 
                           levels = c("prolactin", "corticosterone", "progesterone", 
                                      "estradiol", "testosterone"))
hormones$logconc <- log10(hormones$plasma_conc)
head(hormones)
```

```{r characterizationplots}
hormonecharplot <- function(myhormone, myylab){

  hormones %>% 
    filter(study == "characterization",
           hormone %in% c(myhormone))  %>% 
    droplevels() %>% 
  ggplot(aes(x = as.numeric(treatment), y = plasma_conc)) +
        geom_smooth(aes(colour = sex)) +
    geom_boxplot(aes(fill = treatment)) +
    mytheme() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
          legend.position = "none") +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = myylab, x = NULL) +
    guides(fill = guide_legend(order=1),
         color = guide_legend(order=2)) +
    scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
                       labels = charlevels)
  }

hormonecharplot("prolactin", "PRL (ng/mL)")
hormonecharplot("corticosterone", "CORT (ng/mL)")
hormonecharplot("estradiol", "e2 (ng/mL)")
hormonecharplot("testosterone", "t (ng/mL)")
hormonecharplot("progesterone", "p4 (ng/mL)")
```




```{r manipulation}
# prolactin, removal only
hormones %>% 
    filter( hormone == c("prolactin"))  %>% 
    filter(treatment %in% c("inc.d3", "m.inc.d3", "inc.d9", "m.inc.d9", "inc.d17", "m.inc.d17", "hatch","m.n2"))  %>% 
  ggplot(aes(x = treatment, y = plasma_conc, fill = treatment,  color = sex)) +
    geom_boxplot() + 
  theme_B3()  +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none",
          strip.text = element_blank()) +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = "PRL (ng/mL)", x = NULL) +
    ylim(c(-16,100)) +
  
   annotation_custom(inc, xmax = 1.6, ymin = -14, ymax = 5) +
   annotation_custom(removeegg, xmax = 3.6, ymin = -14, ymax = 5) +
   annotation_custom(inc, xmax = 5.6, ymin = -14, ymax = 5) +
   annotation_custom(removeegg, xmax = 7.6, ymin = -14, ymax = 5) +
  annotation_custom(hatch, xmax = 9.6, ymin = -14, ymax = 5) +
  annotation_custom(removeegg, xmax = 11.6, ymin = -14, ymax = 5) +
  annotation_custom(nestling, xmax = 13.6, ymin = -14, ymax = 5) +
  annotation_custom(removechick, xmax = 15.6, ymin = -14, ymax = 5) +
    
    annotate("rect", xmin = 0.6, xmax = 2.4, ymin = -16, ymax = -14, alpha = 0.25) +
    annotate("rect", xmin = 2.6, xmax = 4.4, ymin = -16, ymax = -14, alpha = 0.5) +
    annotate("rect", xmin = 4.6, xmax = 6.4, ymin = -16, ymax = -14, alpha = 0.75)  +
    annotate("rect", xmin = 6.6, xmax = 8.4, ymin = -16, ymax = -14, alpha = 1) 


hormones %>% 
    filter( hormone == c("prolactin"))  %>% 
    filter( treatment %in% c("inc.d9", "m.inc.d8", "inc.d17", "prolong", "hatch", "extend", "n5"))  %>% 
  ggplot(aes(x = treatment, y = plasma_conc, fill = treatment,  color = sex)) +
    geom_boxplot() + 
  theme_B3()  +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none",
          strip.text = element_blank()) +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = "PRL (ng/mL)", x = NULL) +
  ylim(c(-12,100)) +
   annotation_custom(inc, xmax = 1.6, ymin = -10, ymax = 10) +
   annotation_custom(maniphatch, xmax = 3.6, ymin = -10, ymax = 10) +
   annotation_custom(inc, xmax = 5.6, ymin = -10, ymax = 10) +
   annotation_custom(manipinc, xmax = 7.6, ymin = -10, ymax = 10) +
  annotation_custom(hatch, xmax = 9.6, ymin = -10, ymax = 10) +
  annotation_custom(maniphatch, xmax = 11.6, ymin = -10, ymax = 10) +
  annotation_custom(nestling, xmax = 13.6, ymin = -10, ymax = 10) +
    
  annotate("rect", xmin = 0.6, xmax = 2.4, ymin = -12, ymax = -10, alpha = 0.33) +
    annotate("rect", xmin = 4.6, xmax = 5.4, ymin = -12, ymax = -10, alpha = 0.33) +
    annotate("rect", xmin = 2.6, xmax = 5.4, ymin = -10, ymax = -8, alpha = 0.66) +
    annotate("rect", xmin = 4.6, xmax = 7.4, ymin = -8, ymax = -6, alpha = 1) 
```

```{r sexsteroids}

hormonecharplot("corticosterone", "CORT (ng/mL)")
hormonecharplot("progesterone", "PROG (ng/mL)") 
d1 <- hormonecharplot("estradiol", "E (ng/mL)")
d2 <- hormonecharplot("testosterone", "T (ng/mL)")
plot_grid(d1,d2, nrow = 1)

hormonemanipSteroids <- function(myhormone, myylab, myymax){
  
  hormones %>% 
    filter( hormone %in% c(myhormone))  %>% 
  ggplot(aes(x = treatment, y = plasma_conc, fill = treatment, color = sex)) +
    geom_boxplot() + 
    mytheme() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
         legend.position = "none",
          strip.text = element_blank()) +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = myylab, x = NULL) 
}

hormonemanipSteroids("corticosterone", "CORT (ng/mL)", 10)
hormonemanipSteroids("progesterone", "PROG (ng/mL)",2.5)

a <- hormonemanipSteroids("estradiol", "E (ng/mL)", 1)
b <- hormonemanipSteroids("testosterone", "T (ng/mL)", 3.5)
plot_grid(a,b)

```

```{r aov-char}
prl.char <- hormones %>% filter(hormone == "prolactin", treatment %in% charlevels)   %>%  droplevels()
test.char <- hormones %>% filter(hormone == "testosterone", treatment %in% charlevels)   %>%  droplevels()
est.char <- hormones %>% filter(hormone == "estradiol", treatment %in% charlevels)   %>%  droplevels()
prog.char <- hormones %>% filter(hormone == "progesterone", treatment %in% charlevels)   %>%  droplevels()
cort.char <- hormones %>% filter(hormone == "corticosterone", treatment %in% charlevels)   %>%  droplevels()


aovSexTretment <- function(mydata, whichormone){
  aov2 <- aov(data = mydata, plasma_conc ~ treatment * sex)
  print(whichormone)
  print(summary(aov2))
  #print(TukeyHSD(aov2, which = "treatment"))
}

aovTretment  <- function(mydata, whichormone){
  aov1 <- aov(data = mydata, plasma_conc ~ treatment )
  print(whichormone)
  print(summary(aov1))
  #print(TukeyHSD(aov1, which = "treatment"))
}

aovSexTretment(prl.char, "PRL") # yes, sex difference (p = 0.00256), yes treatment effect (p < 2e-16), no interaction
aovSexTretment(cort.char, "corticosterone") # no sex difference (p = 0.779 ), small treatment effect (p = 0.0238),  no interaction
aovSexTretment(prog.char, "PROG") # no sex difference or treatment effect, signifiant interacion (p = 0.0107)

aovTretment(est.char, "E") # p = 0.101
aovTretment(test.char, "T") # p = 0.609
```



# do control bird with high prolactin hormone have high PRL expression in the pituitary? yes.

```{r PRLvPRL}
PRLpit <- read_csv("../results/10_PRLpit.csv") %>% 
  filter(treatment == "control") %>% 
  arrange(desc(PRL))
head(PRLpit,2)
```



```{r sex}
hormones %>%
  filter(study == "characterization") %>%
  ggplot(aes(x = sex, y = plasma_conc, fill = sex)) +
  geom_boxplot() +
  theme_B3() +
  facet_wrap(~hormone, nrow = 1, scales = "free") +
  theme(legend.position = "none") +
  labs(y = "concentration (ng/mL")


printaovtablesex <- function(myhormone, mydescirption){
  
  aov_all = data.frame()
  for(i in alllevels){
    df <- hormones %>% filter(hormone == myhormone,
                            treatment == i) %>% droplevels()
    aovtable <- apa.aov.table(aov(plasma_conc ~ sex, data  = df))
    aovtable <- as.data.frame(aovtable$table_body)
    totaldf <- aovtable[3, 3]
    aovtable$df <- paste(aovtable$df, ", " , totaldf, sep = "")
    aovtable$ANOVA <- mydescirption
    aovtable$stages <- paste(i)
    aovtable$p <- as.numeric(as.character(aovtable$p))
    aov_all <- rbind(aov_all,aovtable)
  }

  aov_all <- aov_all %>%
    filter(Predictor == "sex")  %>%
    select(stages, ANOVA, df, "F", p) %>%
    mutate(sig = ifelse(p < 0.05, "*", " "))
  aov_all
  return(aov_all)
}

table1 <- printaovtablesex("prolactin", "PRL ~ sex")
table1
write.csv(table1, "../../parentalhormones/data/table-1.csv", row.names = F)
```

```{r cort}

hormones %>%
  filter(hormone == "corticosterone") %>%
  group_by(sex) %>%
  summarise(mean = mean(plasma_conc),
            median = median(plasma_conc))


p1 <- hormones %>%
  filter(hormone == "corticosterone",
         study == "characterization") %>%
  ggplot(aes(x = sex, y = plasma_conc, fill = sex)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = "CORT (ng/mL)", subtitle = element_blank() , x = NULL) +
  theme(legend.position = "none") +
  scale_fill_manual(values = sexcolors) +
  scale_fill_manual(values = colorscharmaip)
p1


cort <- hormones %>%
  filter(hormone == "corticosterone",
         study == "characterization")

p2 <-  ggplot(cort, aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = NULL, x = NULL, subtitle = element_blank() ) +
  theme(legend.position = "none")  +
  scale_fill_manual(values = colorscharmaip)
  
p2

p12 <- plot_grid(p1,p2, rel_widths = c(0.2,0.8), labels = c("h","i"), label_size = 8)

p3 <- hormones %>%
  filter(hormone == "corticosterone",
         treatment %in% c(controlsremoval, levelsremoval )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none") +
  labs( x = NULL, y = "CORT (ng/mL") +
  ylim(c(0,12.5))
p3

p4 <- hormones %>%
  filter(hormone == "corticosterone",
         treatment %in% c(controlstiming, levelstiming )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none") +
  labs(y = NULL, x = NULL) + 
  ylim(c(0,12.5))
p4

p34 <- plot_grid(p3,p4, rel_widths = c(0.6,0.4), labels = c("j","k"), label_size = 8 )
p34

allcortplots <- plot_grid(p12, p34, nrow = 2, rel_heights = c(0.6,0.4))
allcortplots
```


```{r PRL}
hormones %>%
  filter(hormone == "prolactin") %>%
  group_by(sex) %>%
  summarise(m = mean(plasma_conc),
            median = median(plasma_conc))

p1 <- hormones %>%
  filter(hormone == "prolactin",
         study == "characterization") %>%
  ggplot(aes(x = sex, y = plasma_conc, fill = sex)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = "Prolactin (ng/mL)", subtitle = " " , x = NULL) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = sexcolors) +
  scale_y_continuous(limits = c(0,100)) 
p1


PRLf <- hormones %>%
  filter(hormone == "prolactin",
         #study == "characterization",
         sex == "female")

PRLm <- hormones %>%
  filter(hormone == "prolactin",
         #study == "characterization",
         sex == "male")


p2a <-  ggplot(PRLf, aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot(aes(color = sex)) +
  theme_B3() +
  labs(y = NULL, x = NULL, subtitle = "females") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = sexcolors) +
  scale_y_continuous(limits = c(0,100))  +
  scale_fill_manual(values = colorscharmaip)
  
p2b <-  ggplot(PRLm, aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot(aes(color = sex)) +
  theme_B3() +
  labs(y = NULL, x = NULL, subtitle = "males") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = sexcolors) +
  scale_y_continuous(limits = c(0,100))+
  scale_fill_manual(values = colorscharmaip)
  

p12 <- plot_grid(p1,p2a,p2b, rel_widths = c(0.25,0.5, 0.5), labels = c("a","b", "c"), label_size = 8, nrow = 1, align = "hv")
p12

p3a <- hormones %>%
  filter(hormone == "prolactin",
         sex == "female", 
         treatment %in% c(controlsremoval, levelsremoval )) %>% 
  ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot(aes(color = sex)) +
  theme_B3() +
  scale_y_continuous(limits = c(0,100)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs( x = NULL, y = "Prolactin (ng/mL", subtitle = "females") +
  scale_color_manual(values = sexcolors) 
p3a

p3b <- hormones %>%
  filter(hormone == "prolactin",
         sex == "male", 
         treatment %in% c(controlsremoval, levelsremoval )) %>% 
  ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot(aes(color = sex)) +
  theme_B3() +
  scale_y_continuous(limits = c(0,100)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs( x = NULL, y = NULL, subtitle = "males") +
  scale_color_manual(values = sexcolors)
p3b

p4a <- hormones %>%
  filter(hormone == "prolactin",
         sex == "female", 
         treatment %in% c(controlstiming, levelstiming )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot(aes(color = sex)) +
  theme_B3() +
  scale_y_continuous(limits = c(0,100)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = NULL, x = NULL, subtitle = "females") +
  scale_color_manual(values = sexcolors)
p4a

p4b <- hormones %>%
  filter(hormone == "prolactin",
         sex == "male", 
         treatment %in% c(controlstiming, levelstiming )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot(aes(color = sex)) +
  theme_B3() +
  scale_y_continuous(limits = c(0,100)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = NULL, x = NULL, subtitle = "males") +
  scale_color_manual(values = sexcolors) 
  
p4b

p34 <- plot_grid(p3a , p3b,p4a, p4b, rel_widths = c(0.55,0.55, 0.45,0.45), labels = c("d","e", "f", "g"), label_size = 8, nrow = 1)

allprolactinplots <- plot_grid(p12, p34, nrow = 2, rel_heights = c(0.5,0.5))
allprolactinplots
```

## figure 2

```{r figure2, fig.width=7, fig.height=7}

plot_grid(allprolactinplots, allcortplots, nrow = 2)


```






## correlations


```{r correlations2 }

plotcorrelations <- function(i,j, myxlab, mylab, mysubtitle){
      p <- ggplot(hormoneswide, aes(x = i, y = j), na.rm = TRUE) +
       geom_point(aes(color = treatment), na.rm = TRUE) +
       geom_smooth( method = lm, color = "darkgrey", na.rm = TRUE ) +
       theme_B3() +
      #facet_wrap(~sex, scales = "free") +
        labs(x = myxlab, y = mylab, subtitle = mysubtitle) +
        theme(legend.position = "none") +
        scale_color_manual(values = colorscharmaip2)
      
      return(p)
}

hormoneswide

corrPRL <- hormoneswide %>%
  pivot_longer(cols = corticosterone:progesterone, names_to = "hormones", values_to = "conc", values_drop_na = TRUE) %>%
  filter(study == "characterization") %>%
  ggplot(aes(x = prolactin, y = conc)) +
  geom_point(aes(color = treatment)) +
  geom_smooth( color = "darkgrey", method = "lm") +
  facet_wrap(~hormones, nrow = 1, scales = "free_y")  +
  theme_B3() +
  theme(legend.position = "bottom",
        legend.title = element_blank()) +
  scale_color_manual(values = colorscharmaip2) +
  guides(color = guide_legend(nrow = 1)) +
  labs(y = "conc. (ng/mL)", x = "prolactin (ng/mL)")
corrPRL

corrCORT <- hormoneswide %>%
  pivot_longer(cols = c(prolactin, estradiol, testosterone, progesterone), names_to = "hormones", values_to = "conc", values_drop_na = TRUE) %>%
  filter(study == "characterization") %>%
  ggplot(aes(x = corticosterone, y = conc)) +
  geom_point(aes(color = treatment)) +
  geom_smooth( color = "darkgrey", method = "lm") +
  facet_wrap(~hormones, nrow = 1, scales = "free_y")  +
  theme_B3() +
  theme(legend.position = "bottom",
        legend.title = element_blank()) +
  scale_color_manual(values = colorscharmaip2) +
  guides(color = guide_legend(nrow = 1)) +
  labs(y = "conc. (ng/mL)", x = "corticosterone (ng/mL)")
corrCORT

hormoneswide %>%
  pivot_longer(cols = c(prolactin, estradiol, testosterone, progesterone), names_to = "hormones", values_to = "conc", values_drop_na = TRUE) %>%
  filter(study == "characterization") %>%
  ggplot(aes(x = corticosterone, y = conc)) +
  geom_point(aes(color = treatment)) +
  geom_smooth(color = "darkgrey", method = "lm") +
  facet_grid(hormones ~ treatment, scales = "free_y")  +
  theme_B3() +
  theme(legend.position = "bottom",
        legend.title = element_blank()) +
  scale_color_manual(values = colorscharmaip2) +
  guides(color = guide_legend(nrow = 1)) +
  labs(y = "conc. (ng/mL)", x = "corticosterone (ng/mL)")


hormoneswide %>%
  pivot_longer(cols = c(corticosterone, estradiol, testosterone, progesterone), names_to = "hormones", values_to = "conc", values_drop_na = TRUE) %>%
  filter(study == "characterization") %>%
  ggplot(aes(x = prolactin, y = conc)) +
  geom_point(aes(color = treatment)) +
  geom_smooth(color = "darkgrey", method = "lm") +
  facet_grid(hormones ~ treatment, scales = "free_y")  +
  theme_B3() +
  theme(legend.position = "bottom",
        legend.title = element_blank()) +
  scale_color_manual(values = colorscharmaip2) +
  guides(color = guide_legend(nrow = 1)) +
  labs(y = "conc. (ng/mL)", x = "prolactin (ng/mL)")

ggplot(hormoneswide, aes(x = prolactin, y = corticosterone, color = treatment)) +
  geom_point() + geom_smooth(method = "lm") +
  facet_wrap(~treatment) +
  scale_color_manual(values =  colorscharmaip) + theme(legend.position = "none")

ggplot(hormoneswide, aes(x = prolactin, y = testosterone, color = treatment)) +
  geom_point() + geom_smooth(method = "lm") +
  facet_wrap(~treatment) +
  scale_color_manual(values =  colorscharmaip) + theme(legend.position = "none")

```

## progesterone

```{r progesterone}

hormones %>%
  filter(hormone == "progesterone") %>%
  group_by(sex) %>%
  summarise(mean = mean(plasma_conc),
            median = median(plasma_conc))


p1 <- hormones %>%
  filter(hormone == "progesterone",
         study == "characterization") %>%
  ggplot(aes(x = sex, y = plasma_conc, fill = sex)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = "Progesterone (ng/mL)", subtitle = element_blank() , x = NULL) +
  theme(legend.position = "none")   +
  scale_y_continuous(limits = c(0,4.5)) +
  scale_fill_manual(values = sexcolors) 

df <- hormones %>%
  filter(hormone == "progesterone",
         study == "characterization")

p2 <-  ggplot(df, aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = NULL, x = NULL, subtitle = " ") +
  scale_y_continuous(limits = c(0,4.5)) +
  theme(legend.position = "none") 

p3 <- hormones %>%
  filter(hormone == "progesterone",
         treatment %in% c(controlsremoval, levelsremoval )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  scale_y_continuous(limits = c(0,4.5)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none") +
  labs( x = NULL, y = "Progesterone (ng/mL")

p4 <- hormones %>%
  filter(hormone == "progesterone",
         treatment %in% c(controlstiming, levelstiming )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  scale_y_continuous(limits = c(0,4.5)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none") +
  labs(y = NULL, x = NULL)


progesterone <- plot_grid(p1, p2, p3 + labs(y = NULL), p4, nrow = 1, rel_widths =   c(0.175,0.4,0.35,0.25))
progesterone
```


## estradiol and testosterone


```{r estradiol}

hormones %>%
  filter(hormone == "estradiol") %>%
  summarise(mean = mean(plasma_conc),
            median = median(plasma_conc))


p5 <- hormones %>%
  filter(hormone == "estradiol",
         study == "characterization") %>%
  ggplot(aes(x = sex, y = plasma_conc, fill = sex)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = "Estradiol (ng/mL)", subtitle = element_blank() , x = NULL) +
  theme(legend.position = "none")  +
    scale_y_continuous(limits = c(0,1)) +
  scale_fill_manual(values = sexcolors) 

df <- hormones %>%
  filter(hormone == "estradiol",
         study == "characterization")

p6 <-  ggplot(df, aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = NULL, x = NULL, subtitle = " ") +
    scale_y_continuous(limits = c(0,1)) +
  theme(legend.position = "none") 


p7 <- hormones %>%
  filter(hormone == "estradiol",
         treatment %in% c(controlsremoval, levelsremoval )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  scale_y_continuous(limits = c(0,1)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none") +
  labs( x = NULL, y = "Estradiol (ng/mL")


p8 <- hormones %>%
  filter(hormone == "estradiol",
         treatment %in% c(controlstiming, levelstiming )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  scale_y_continuous(limits = c(0,1)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none") +
  labs(y = NULL, x = NULL)

estradiol <- plot_grid(p5, p6, p7 + labs(y = NULL), p8, nrow = 1, rel_widths =   c(0.175,0.4,0.35,0.25))
estradiol
```


```{r testosterone}

hormones %>%
  filter(hormone == "testosterone") %>%
  summarise(mean = mean(plasma_conc),
            median = median(plasma_conc))


p9 <- hormones %>%
  filter(hormone == "testosterone",
         study == "characterization") %>%
  ggplot(aes(x = sex, y = plasma_conc, fill = sex)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = "Testosterone (ng/mL)", subtitle = element_blank() , x = NULL) +
  theme(legend.position = "none")  +
    scale_y_continuous(limits = c(0,8.5)) +
  scale_fill_manual(values = sexcolors) 


df <- hormones %>%
  filter(hormone == "testosterone",
         study == "characterization")

p10 <-  ggplot(df, aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  labs(y = NULL, x = NULL, subtitle = " ") +
    scale_y_continuous(limits = c(0,8.5)) +
  theme(legend.position = "none") 
  

p11 <- hormones %>%
  filter(hormone == "testosterone",
         treatment %in% c(controlsremoval, levelsremoval )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  scale_y_continuous(limits = c(0,8.5)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none") +
  labs( x = NULL, y = "concentration (ng/mL")

p12 <- hormones %>%
  filter(hormone == "testosterone",
         treatment %in% c(controlstiming, levelstiming )) %>% 
ggplot(aes(x = treatment, y = plasma_conc, fill = treatment)) +
  geom_boxplot() +
  theme_B3() +
  scale_y_continuous(limits = c(0,8.5)) +
  scale_fill_manual(values = colorscharmaip) +
  theme(legend.position = "none") +
  labs(y = NULL, x = NULL)
p12

testosterone <- plot_grid(p9, p10, p11 + labs(y = NULL), p12, nrow = 1, rel_widths =   c(0.175,0.4,0.35,0.25))
testosterone
```

```{r sexsteroids2, fig.height=8}
sexsteroids <- plot_grid(
       p9 + theme(axis.text.x = element_blank()),  
       p10 + theme(axis.text.x = element_blank()), 
       p11 + labs(y = NULL) + theme(axis.text.x = element_blank()), 
       p12 + theme(axis.text.x = element_blank()),
        p5 + theme(axis.text.x = element_blank()), 
       p6 + theme(axis.text.x = element_blank()), 
       p7 + labs(y = NULL) + theme(axis.text.x = element_blank()), 
       p8 + theme(axis.text.x = element_blank()), 
       p1 , 
       p2 + theme(axis.text.x = element_text(angle = 45, hjust = 1)), 
       p3 + labs(y = NULL)  + theme(axis.text.x = element_text(angle = 45, hjust = 1)), 
       p4  + theme(axis.text.x = element_text(angle = 45, hjust = 1)), 
        nrow = 3, 
        rel_widths =   c(0.175,0.4,0.35,0.25), align = "hv",
          label_size = 8, labels = c("A1", "A2", "A3" , "A4",
                                     "B1", "B2", "B3" , "B4",
                                     "C1", "C2", "C3" , "C3"))
sexsteroids

```

## pca of hormones

```{r PCA}

library("factoextra")
library("FactoMineR")

# char only
hormoneswidechar <- hormoneswide %>% filter(treatment %in% charlevels)
df <- hormoneswidechar %>% select(prolactin:progesterone)
res.pca <- PCA(df)

a1 <- fviz_pca_var(res.pca, col.var = "black", title = "Charactherization only") 
# Contributions of variables to PC1

b1 <- fviz_contrib(res.pca, choice = "var", axes = 1, top = 10) + labs(y = "Dim 1 contibutions (%)",
                                                                      title = element_blank())
# Contributions of variables to PC2
c1 <- fviz_contrib(res.pca, choice = "var", axes = 2, top = 10) +
  labs(y = "Dim 2 contibutions (%)") + theme(title = element_blank())

ones <- plot_grid(a1,b1,c1, nrow = 1, rel_widths = c(1,0.425,0.425), align = "hv")

# char and manip
df <- hormoneswide %>% select(prolactin:progesterone)
res.pca <- PCA(df)

a2 <- fviz_pca_var(res.pca, col.var = "black", title = "Charactherization & manipluation") 
# Contributions of variables to PC1

b2 <- fviz_contrib(res.pca, choice = "var", axes = 1, top = 10) + labs(y = "Dim 1 contibutions (%)",
                                                                      title = element_blank())
# Contributions of variables to PC2
c2 <- fviz_contrib(res.pca, choice = "var", axes = 2, top = 10) +
  labs(y = "Dim 2 contibutions (%)") + theme(title = element_blank())

twos <- plot_grid(a2 + theme(title = element_blank()),b2,c2, nrow = 1, rel_widths = c(1,0.425,0.425), align = "hv")

plot_grid(ones,twos, nrow = 2)

twos
```

```{r figure3, fig.height=8, fig.width=7}


plot_grid(twos,sexsteroids, nrow = 2, rel_heights = c(0.25,0.75), align = "hv")
```

# smooth funciton

```{r summary}
head(hormones)
ggplot(hormones, aes(x = as.numeric(treatment), y = plasma_conc, color = hormone)) +
  geom_smooth() 

box <- ggplot(hormones, aes(x = as.numeric(treatment), y = plasma_conc)) +
  geom_boxplot(aes(fill = treatment)) +
  #geom_smooth(aes(color = hormone)) +
  facet_wrap(~hormone, scales = "free_y", nrow = 5) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16),
                     labels = alllevels) +
  theme_B3() +
  theme(#strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA)) +
  labs(y = "plasma conc. (ng/mL)", x = "parental stage") +
  scale_fill_manual(values = colorscharmaip)

line <- ggplot(hormones, aes(x = as.numeric(treatment), y = plasma_conc)) +
  #geom_boxplot(aes(fill = treatment)) +
  geom_smooth(aes(color = hormone)) +
  facet_wrap(~hormone, scales = "free_y", nrow = 5) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16),
                     labels = alllevels) +
  theme_B3() +
  theme(#strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA)) +
  labs(y = "plasma conc. (ng/mL)", x = "parental stage") 
  

plot_grid(box, line, nrow = 1)
```

## stats

```{r}

P3 <- hormones %>% filter(hormone == "progesterone")
E2 <- hormones %>% filter(hormone == "estradiol")
T2 <- hormones %>% filter(hormone == "testosterone")



aov1 <- aov(PRLm$logconc ~ PRLm$treatment)
res1 <- TukeyHSD(aov1)
res1 <- as.data.frame(res1$`PRLm$treatment`)
res1$hormone <- "male PRL"
res1$sig <- ifelse(res1$`p adj` < 0.001, "***",
                   ifelse(res1$`p adj` < 0.01, "**",
                           ifelse(res1$`p adj` < 0.05, "*", "NS" )))
res1$comparison <- row.names(res1)
res1



aov2 <- aov(PRLf$logconc ~ PRLf$treatment)
res2 <- TukeyHSD(aov2)
res2 <- as.data.frame(res2$`PRLf$treatment`)
res2$hormone <- "female PRL"
res2$sig <- ifelse(res2$`p adj` < 0.001, "***",
                   ifelse(res2$`p adj` < 0.01, "**",
                           ifelse(res2$`p adj` < 0.05, "*","NS"  )))
res2$comparison <- row.names(res2)
res2


aov3 <- aov(P3$logconc ~ P3$treatment)
res3 <- TukeyHSD(aov3)
res3 <- as.data.frame(res3$`P3$treatment`)
res3$hormone <- "P3"
res3$sig <- ifelse(res3$`p adj` < 0.001, "***",
                   ifelse(res3$`p adj` < 0.01, "**",
                           ifelse(res3$`p adj` < 0.05, "*", "NS"  )))
res3$comparison <- row.names(res3)
res3

aov4 <- aov(E2$logconc ~ E2$treatment)
res4 <- TukeyHSD(aov4)
res4 <- as.data.frame(res4$`E2$treatment`)
res4$hormone <- "E2"
res4$sig <- ifelse(res4$`p adj` < 0.001, "***",
                   ifelse(res4$`p adj` < 0.01, "**",
                           ifelse(res4$`p adj` < 0.05, "*", "NS" )))
res4$comparison <- row.names(res4)
res4


aov5 <- aov(T2$logconc ~ T2$treatment)
res5 <- TukeyHSD(aov5)
res5 <- as.data.frame(res5$`T2$treatment`)
res5$hormone <- "T"
res5$sig <- ifelse(res5$`p adj` < 0.001, "***",
                   ifelse(res5$`p adj` < 0.01, "**",
                           ifelse(res5$`p adj` < 0.05, "*", "NS"  )))
res5$comparison <- row.names(res5)
res5

resall <- rbind(res3, res5, res4, res2, res1) %>% drop_na()
resall

table1 <- resall %>%
  filter(grepl('control', comparison),
         !grepl('prolong|extend|m.', comparison)) %>%
   mutate(diff = round(diff, 2)) %>% 
  mutate(diffsig = paste(diff, sig, sep = ", ")) %>% 
   select(hormone, comparison, diffsig) %>% 
  pivot_wider( names_from = hormone, values_from = diffsig)
table1

table2 <- resall %>%
  filter(!grepl('control|bldg|lay|n5', comparison),
         grepl('prolong|extend|m.', comparison)) %>%
   mutate(diff = round(diff, 2)) %>% 
  mutate(diffsig = paste(diff, sig, sep = ", ")) %>% 
   select(hormone, comparison, diffsig) %>% 
  pivot_wider( names_from = hormone, values_from = diffsig)
table2

write.csv(table1, "../../parentalhormones/data/table-1.csv")
write.csv(table2, "../../parentalhormones/data/table-2.csv")


```

