---
title: "candidate genes"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)
library(corrr)
library(ggcorrplot)
library(pheatmap)


source("../R/functions.R")  # load custom functions 
source("../R/themes.R")  # load custom themes and color palletes

knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/specificgenes/')
```

# analyses downstream of calculating tissue specific variance in gene expression

```{r getvsdandcolData}
vsd.hyp <- readvsd("../results/04_vsd_hyp.csv")
colData.hyp <- readcolData("../results/04_colData_hyp.csv")

vsd.pit <- readvsd("../results/04_vsd_pit.csv")
colData.pit <- readcolData("../results/04_colData_pit.csv")

vsd.gon <- readvsd("../results/04_vsd_gon.csv")
colData.gon <- readcolData("../results/04_colData_gon.csv")


colData.hyp <- colData.hyp %>% 
  mutate(tissue = sapply(strsplit(sample,'\\_'), "[", 3)) %>%
  mutate(bird = sapply(strsplit(sample,'\\_'), "[", 1)) %>%
  select(sample, bird, sex, tissue, treatment)

colData.pit <- colData.pit %>%  
  mutate(tissue = sapply(strsplit(sample,'\\_'), "[", 3)) %>%
  mutate(bird = sapply(strsplit(sample,'\\_'), "[", 1)) %>%
  select(sample, bird, sex, tissue, treatment)

colData.gon <- colData.gon %>%  
  mutate(tissue = sapply(strsplit(sample,'\\_'), "[", 3)) %>%
  mutate(bird = sapply(strsplit(sample,'\\_'), "[", 1)) %>%
  select(sample, bird, sex, tissue, treatment)

```


# selecting candidate genes counts from the hypothalamus


```{r geneinfo}
geneinfo <- read_csv("../metadata/00_geneinfo.csv") %>%  dplyr::select(Name, geneid, entrezid) %>% arrange(Name)
head(geneinfo)
```

```{r candidategenes, fig.width =5.5, fig.height= 4}
candidategenes <- c("PRL","PRLR", "GNRHR")

candidates.hyp <- selectcandidatevsds(candidategenes, vsd.hyp, colData.hyp)
candidates.pit <- selectcandidatevsds(candidategenes, vsd.pit, colData.pit)
candidates.gon <- selectcandidatevsds(candidategenes, vsd.gon, colData.gon)

plotcanddateexpression <- function(candidateexpression,  mysubtitle, whichgene, myylab){
  
  ggplot(candidateexpression, aes(x = as.numeric(treatment), y = whichgene)) + 
        geom_smooth(aes(colour = sex)) +
    geom_boxplot(aes(fill = treatment, alpha = sex, color = sex)) + 
    scale_alpha_manual(values = c(0.75,1)) +
     theme_B3() +
    theme(legend.position = "none") +
    theme(axis.title.y=element_text(face="italic"),
          axis.title.x = element_blank(),
          axis.text.x = element_blank()) +
    scale_color_manual(values = c("female" = "#969696", "male" = "#525252")) +
    labs(subtitle = mysubtitle, y = myylab)
  
}

a <- plotcanddateexpression(candidates.hyp,  "hypothalamus", candidates.hyp$PRL, "PRL")
b <- plotcanddateexpression(candidates.pit, "pituitary", candidates.pit$PRL, "PRL")
c <- plotcanddateexpression(candidates.gon,  "gonad", candidates.gon$PRL, "PRL")

d <- plotcanddateexpression(candidates.hyp, "hypothalamus", candidates.hyp$PRLR, "PRLR")
e <- plotcanddateexpression(candidates.pit, "pituitary", candidates.pit$PRLR, "PRLR")
f <- plotcanddateexpression(candidates.gon, "gonad", candidates.gon$PRLR, "PRLR")


g <- plotcanddateexpression(candidates.hyp, "hypothalamus", candidates.hyp$GNRHR, "GNRHR")
h <- plotcanddateexpression(candidates.pit, "pituitary", candidates.pit$GNRHR, "GNRHR")
i <- plotcanddateexpression(candidates.gon, "gonad", candidates.gon$GNRHR, "GNRHR")

abc <- plot_grid(a, d, g, nrow = 1)
def <- plot_grid(b, e, h, nrow = 1)
ghi <- plot_grid(c, f, i, nrow = 1)

plot_grid(abc, def,ghi,nrow = 3)
```



```{r PRLdf}
PRLpit <- candidates.pit %>%
  select(bird, sex,treatment,tissue, PRL)
head(PRLpit)
write.csv(PRLpit, "../results/10_PRLpit.csv", row.names = F)
```

```{r correlations-incd9-incd17}
pitcandidates <- c("ATP6AP2", "CRY1", "TMF1",
                   "EIF2AK3", "PRL", "SOCS2", "STAT5B", "XBP1",
                   "APP", "HDAC4", "NCOA1")
goncandidates <- c("AVPR2", "BMP6", "CRHR2", "DRD5", "TAC1",
                   "SOCS2", "ZBTB7B",
                   "DRD5", "NCOA2", "BRINP1", "NR3C1")

candidates.pit <- selectcandidatevsds(pitcandidates, vsd.pit, colData.pit) %>% select(-sample) %>% filter(treatment %in% c("inc.d9", "inc.d17"))
candidates.gon <- selectcandidatevsds(goncandidates, vsd.gon, colData.gon) %>% select(-sample) %>% filter(treatment %in% c("inc.d9", "inc.d17"))

candidates.pit <- candidates.pit %>% rename_at(vars(-bird,-sex, -tissue, -treatment), function(x) paste0("pit_", x)) %>% select(-tissue)
candidates.gon <- candidates.gon %>% rename_at(vars(-bird,-sex, -tissue, -treatment), function(x) paste0("gon_", x)) %>% select(-tissue)

counts <- full_join(candidates.pit, candidates.gon) %>% drop_na() %>% select(-bird, -sex, -treatment)
cols <- full_join(candidates.pit, candidates.gon) %>% drop_na() %>% select(bird, sex, treatment)
dim(counts)
dim(cols)


x <- correlate(counts)
fashion(x)
rplot(x)  + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(subtitletitle = "inc.d9 to inc.d17")

x %>% network_plot.cor_df(min_cor = .5) + 
  labs(subtitletitle = "inc.d9 to inc.d17")



cal_z_score <- function(x){
  (x - mean(x)) / sd(x)
}
 

tcounts <- t(counts)
cols <- cols %>% select(-bird)

data_subset_norm <- t(apply(tcounts, 1, cal_z_score))
row.names(cols) <- colnames(data_subset_norm)

pheatmap(data_subset_norm,  annotation_col = cols)


corr <- x
row.names(corr) <- corr$rowname 
corr$rowname <- NULL
ggcorrplot(corr, hc.order = TRUE, outline.col = "white", title = "inc.d9 to inc.d17")
```


```{r correlations-bldg-lay}
pitcandidates <- c("BMP6", "CGA", "GAL", "XBP1")
goncandidates <- c("CCND1", "NME1", "PRL", "APLP2", "CYP11A1", "CREBRF", "DBH")

candidates.pit <- selectcandidatevsds(pitcandidates, vsd.pit, colData.pit) %>% select(-sample) %>% filter(treatment %in% c("bldg", "lay"))
candidates.gon <- selectcandidatevsds(goncandidates, vsd.gon, colData.gon) %>% select(-sample) %>% filter(treatment %in% c("bldg", "lay"))

candidates.pit <- candidates.pit %>% rename_at(vars(-bird,-sex, -tissue, -treatment), function(x) paste0("pit_", x)) %>% select(-tissue)
candidates.gon <- candidates.gon %>% rename_at(vars(-bird,-sex, -tissue, -treatment), function(x) paste0("gon_", x)) %>% select(-tissue)

counts <- full_join(candidates.pit, candidates.gon) %>% drop_na() %>% select(-bird, -sex, -treatment)
cols <- full_join(candidates.pit, candidates.gon) %>% drop_na() %>% select(bird, sex, treatment)
dim(counts)
dim(cols)


x <- correlate(counts)
fashion(x)
rplot(x)  + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(subtitle = "bldg to lay")

x %>% network_plot.cor_df(min_cor = .5) + labs(subtitle = "bldg to lay")

corr <- x
row.names(corr) <- corr$rowname 
corr$rowname <- NULL
ggcorrplot(corr, hc.order = TRUE, outline.col = "white", title = "bldg to lay")
```




```{r correlations-lay-incd3}
pitcandidates <- c("PTEN", "CGA", "GAL", "XBP1")
goncandidates <- c(
  "AVPR1A", "C1QTNF1", "CRY1", "CRY2", "F2R", "GJA1", "INHBA", "RHOA", "SMAD4",
  "ATP2B2", "ATP7B", "CAV1", "EIF2AK3", "ERBB4", "GJA1", "HIF1A", "MED1", "NME1", 
  "PRLR", "VEGFA", "XBP1",  "ZBTB7B", "APLP2", "NCOA1", "NCOA2", "THRB",
  "CREBRF", "GNAQ", "NR3C1")

candidates.pit <- selectcandidatevsds(pitcandidates, vsd.pit, colData.pit) %>% select(-sample) %>% filter(treatment %in% c("inc.d3", "lay"))
candidates.gon <- selectcandidatevsds(goncandidates, vsd.gon, colData.gon) %>% select(-sample) %>% filter(treatment %in% c("inc.d3", "lay"))

candidates.pit <- candidates.pit %>% rename_at(vars(-bird,-sex, -tissue, -treatment), function(x) paste0("pit_", x)) %>% select(-tissue)
candidates.gon <- candidates.gon %>% rename_at(vars(-bird,-sex, -tissue, -treatment), function(x) paste0("gon_", x)) %>% select(-tissue)

counts <- full_join(candidates.pit, candidates.gon) %>% drop_na() %>% select(-bird, -sex, -treatment)
cols <- full_join(candidates.pit, candidates.gon) %>% drop_na() %>% select(bird, sex, treatment)
dim(counts)
dim(cols)


x <- correlate(counts)
fashion(x)
rplot(x) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(subtitle = "lay to inc.d3")

x %>% network_plot.cor_df(min_cor = .5)  + 
  labs(subtitle = "lay to inc.d3")


corr <- x
row.names(corr) <- corr$rowname 
corr$rowname <- NULL
ggcorrplot(corr, hc.order = TRUE, outline.col = "white", title = "lay to inc.d3")
```

```{r correlations-hatch-n5}
pitcandidates <- c( "ATP6AP2", "AVPR2", "CRY2", "RHOA", 
                    "EIF2AK3", "NME1", "PRL", "XBP1",
                    "APP", "NCOA1")
hypcandidates <- c("CRHBP", "CRHR2", "DRD3", "EDN1", "FAM129B", "FOXL2", "KRAS",
                   "OPRK1", "POMC", "RAB11FIP5", "RUNX1",
                   "CAV1", "ZBTB7B", "HEXB", "PGR")

candidates.pit <- selectcandidatevsds(pitcandidates, vsd.pit, colData.pit) %>% select(-sample) %>% filter(treatment %in% c("hatch", "n5"))
candidates.hyp <- selectcandidatevsds(hypcandidates, vsd.hyp, colData.hyp) %>% select(-sample) %>% filter(treatment %in% c("hatch", "n5"))

candidates.pit <- candidates.pit %>% rename_at(vars(-bird,-sex, -tissue, -treatment), function(x) paste0("pit_", x)) %>% select(-tissue)
candidates.hyp <- candidates.hyp %>% rename_at(vars(-bird,-sex, -tissue, -treatment), function(x) paste0("hyp_", x)) %>% select(-tissue)

counts <- full_join(candidates.pit, candidates.hyp) %>% drop_na() %>% select(-bird, -sex, -treatment)
cols <- full_join(candidates.pit, candidates.hyp) %>% drop_na() %>% select(bird, sex, treatment)
dim(counts)
dim(cols)


x <- correlate(counts)
fashion(x)
rplot(x) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(subtitle = "hatch to n5")

x %>% network_plot.cor_df(min_cor = .5)  + 
  labs(subtitle = "hatch to n5")


corr <- x
row.names(corr) <- corr$rowname 
corr$rowname <- NULL
ggcorrplot(corr, hc.order = TRUE, outline.col = "white", title = "hatch to n5")
```

