---
title: "favgenes"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(DESeq2)
library(cowplot)

library(BiocParallel)
register(MulticoreParam(6))

source("../R/themes.R") 
source("../R/functions.R")

knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/favegenes/', cache = T)
```

```{r pseudocounts}
pseudocounts <- read_csv("../results/01_pseudo.counts.csv")
head(pseudocounts[1:3])

geneinfo <- read.csv("../metadata/00_geneinfo.csv", row.names = 1)
head(geneinfo)

# prep col data for all samples
colData <- read.csv("../metadata/00_samples.csv", header = T, row.names = 1)
colData$treatment <- factor(colData$treatment, levels = alllevels)
colData <- colData %>% mutate(tissue = fct_recode(tissue, "gonads" = "gonad"))
colData$tissue <- factor(colData$tissue, levels = tissuelevels)
row.names(colData) <- colData$V1


# prep count data for all samples
countData <- as.data.frame(pseudocounts)
countData$entrezid <- countData$X1
countData <- left_join(geneinfo, countData)
countData <- countData %>% dplyr::distinct(Name, .keep_all = TRUE) %>%
    dplyr::select(-row.names, -geneid, -entrezid, -X1) 
countData <- as.data.frame(countData)
row.names(countData) <- countData$Name
countData$Name <- NULL
countData$entrezid <- NULL
countData <- as.data.frame(t(countData))
head(countData)

# keep names for 
favcounts <- countData %>% dplyr::select("PRL", "COX1", "GH", "CHGA", 
                                         "FOS", "EGR1", "GNRHR", "GNRH1")
# check okay to bind rather than join
row.names(countData) == row.names(colData)
favcounts <- cbind(colData, favcounts)

ggplot(favcounts, aes(x = treatment, y = PRL, fill = treatment, color = sex)) +
  geom_boxplot() + 
  mytheme() +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none",
          strip.text = element_blank()) 

ggplot(favcounts, aes(x = treatment, y = GH, fill = treatment, color = sex)) +
  geom_boxplot() + 
  mytheme() +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none",
          strip.text = element_blank()) 
```


```{r DESeq2-prep}
# untranform count data and convert all doubles to integers for DESEq2
countData <- read.csv("../results/00_counts.csv")
head(countData)
countData$entrezid <- countData$X
countData <- left_join(geneinfo, countData)
countData <- countData %>% dplyr::distinct(Name, .keep_all = TRUE) %>%
    dplyr::select(-row.names, -geneid, -entrezid, -X) 
countData <- as.data.frame(countData)
row.names(countData) <- countData$Name
countData$Name <- NULL

# create column for subsetting
colData$sextissue <- paste(colData$sex,colData$tissue, sep = "_")

colData <- subsetcolData(colData, c("female_pituitary", "male_pituitary"))
# save counts that match colData
savecols <- as.character(colData$V1) 
savecols <- as.vector(savecols) 
countData <- countData %>% dplyr::select(one_of(savecols)) 
  
ncol(countData) == nrow(colData)
colnames(countData) == rownames(colData)
  
dds <- DESeqDataSetFromMatrix(countData = countData,
                                colData = colData,
                                design = ~ treatment * sex)
  
print(dds)
ds <- dds[rowSums(counts(dds) > 1) >= 10]  # filter more than sample with less 0 counts
print(dim(dds))
  
dds <- DESeq(dds) # Differential expression analysis

vsd.pituitary <- vst(dds, blind=FALSE)

vsd.pituitary.df <- as.data.frame(assay(vsd.pituitary))
widecountdata <- as.data.frame(t(vsd.pituitary.df))
widecountdata <- cbind(colData, widecountdata)
```

```{r contrasts}
res <- results(dds, independentFiltering = T)
summary(res)

myresSig <- function(mycontrast, myfilename){
  res <- results(dds, contrast = mycontrast)
  print(summary(res))
  resSig <- subset(res, padj < 0.1)
  resSig <- as.data.frame((resSig))
  resSig <-resSig[order(resSig$padj),]
  print(head(resSig))
  write.csv(resSig, myfilename)
}

myresSig(c("sex","male","female"), "../results/contrasts/resSig.sex.male.female.csv")
myresSig(c("treatment","bldg","control"), "../results/contrasts/resSig.treatment.bldg.control.csv")
myresSig(c("treatment","lay","bldg"), "../results/contrasts/resSig.treatment.lay.bldg.csv")
myresSig(c("treatment","inc.d3","lay"), "../results/contrasts/resSig.treatment.inc.d3.lay.csv")

myresSig(c("treatment","inc.d9","inc.d3"), "../results/contrasts/resSig.treatment.inc.d9.inc.d3.csv")
myresSig(c("treatment","m.inc.d8","inc.d9"), "../results/contrasts/resSig.treatment.m.inc.d8.inc.d9.csv")
myresSig(c("treatment","m.inc.d9","inc.d9"), "../results/contrasts/resSig.treatment.m.inc.d9.inc.d9.csv")

myresSig(c("treatment","inc.d17","inc.d9"), "../results/contrasts/resSig.treatment.inc.d17.inc.d9.csv")
myresSig(c("treatment","m.inc.d17","inc.d17"), "../results/contrasts/resSig.treatment.m.inc.d17.inc.d9.csv")

myresSig(c("treatment","m.n2","hatch"), "../results/contrasts/resSig.treatment.m.n2.hatch.csv")
myresSig(c("treatment","n5","hatch"), "../results/contrasts/resSig.treatment.n5.hatch.csv")
myresSig(c("treatment","hatch","inc.d17"), "../results/contrasts/resSig.treatment.hatch.inc.d17.csv")

```

```{r DESeq2-allmanip}

plotwidedata <- function(whichgene, myylab){
p <- ggplot(widecountdata, (aes(x = treatment, y = whichgene))) +
        geom_smooth(aes(colour = sex)) +
    geom_boxplot(aes(outlier.color = treatment, fill = treatment, alpha = sex)) +
    mytheme() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(x = NULL, y = NULL, subtitle = myylab) +
    guides(fill = guide_legend(order=1),
         color = guide_legend(order=2)) +
    scale_alpha_manual(values = c(0.75,1)) 
return(p)
}

plotwidedata(widecountdata$PRL, "PRL")

a <- plotwidedata(widecountdata$PRL, "PRL")
b <- plotwidedata(widecountdata$FOSL2, "FOSL2")
c <- plotwidedata(widecountdata$COX1, "COX1")
d <- plotwidedata(widecountdata$BRCA1, "BRCA1")
e <- plotwidedata(widecountdata$CDK1, "CDK1")
f <-plotwidedata(widecountdata$MYC, "MYC")

plot_grid(a + theme(axis.text.x = element_blank()),
          b + theme(axis.text.x = element_blank()),
          c + theme(axis.text.x = element_blank()),
          d + theme(axis.text.x = element_blank()),
          e + theme(axis.text.x = element_blank()),
          f + theme(axis.text.x = element_blank()), nrow = 2)

plot_grid(a + theme(axis.text.x = element_blank()),
          d + theme(axis.text.x = element_blank()),
          e + theme(axis.text.x = element_blank()), nrow = 1)
```

```{r DESeq2-partialmanip}
PRLremove <- widecountdata %>% 
    filter( !treatment %in% c("m.inc.d8", "prolong", "extend"))  %>% 
  ggplot(aes(x = treatment, y = PRL, fill = treatment,  color = sex)) +
    geom_boxplot() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none",
          strip.text = element_blank()) +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = "PRL expression", x = NULL,
         subtitle = "PRL in female and male pituitary") +
    annotate("rect", xmin = 3.7, xmax = 5.3, ymin = 14.5, ymax = 14.6, alpha = 1) +
    annotate("rect", xmin = 5.7, xmax = 7.3, ymin = 14.5, ymax = 14.6, alpha = 1) +
    annotate("rect", xmin = 7.7, xmax = 9.3, ymin = 14.5, ymax = 14.6, alpha = 1) +
    annotate("rect", xmin = 9.7, xmax = 11.3, ymin = 14.5, ymax = 14.6, alpha = 1)

PRLtiming <- widecountdata %>% 
    filter( !treatment %in% c("m.inc.d3", "m.inc.d9", "m.inc.d17","m.n2"))  %>% 
  ggplot(aes(x = treatment, y = PRL, fill = treatment,  color = sex)) +
    geom_boxplot() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none",
          strip.text = element_blank()) +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = "PRL expression", x = NULL,
         subtitle = "PRL in female and male pituitary") +
    annotate("rect", xmin = 4.7, xmax = 6.3, ymin = 14.5, ymax = 14.6, alpha = 1, alpha = 1) +
    annotate("rect", xmin = 6.7, xmax = 8.3, ymin = 14.5, ymax = 14.6, alpha = 1, alpha = 1) +
    annotate("rect", xmin = 8.7, xmax = 10.3, ymin = 14.5, ymax = 14.6, alpha = 1, alpha = 1)

png('../figures/favegenes/PRLremove.png',width=600,height=400, units="px", res =)
print(PRLremove)
dev.off()

png('../figures/favegenes/PRLtiming.png',width=600,height=400, units="px")
print(PRLtiming)
dev.off()


removal <- widecountdata %>% 
    filter( !treatment %in% c("m.inc.d8", "prolong", "extend",  "control", "bldg" , "lay", "n5", "n9"))

plotremove <- function(whichgene, myylab){
  p <-  removal  %>% 
  ggplot(aes(x = treatment, y = whichgene, fill = treatment,  color = sex)) +
    geom_boxplot() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none",
          strip.text = element_blank()) +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = NULL, subtitle = myylab, x = NULL) 
  return(p)
}

a <- plotremove(removal$PRL, "PRL")
b <- plotremove(removal$FOSL2, "FOSL2")
c <- plotremove(removal$COX1, "COX1")
d <- plotremove(removal$BRCA1, "BRCA1")
e <- plotremove(removal$CDK1, "CDK1")
f <- plotremove(removal$MYC, "MYC")

plot_grid(a + theme(axis.text.x = element_blank()),
          d + theme(axis.text.x = element_blank()),
          e + theme(axis.text.x = element_blank()), nrow = 1)



timing <- widecountdata %>% 
    filter( !treatment %in% c("m.inc.d3", "m.inc.d9", "m.inc.d17","m.n2", 
                              "control", "bldg" , "lay", "n5", "n9"))

plottiming <- function(whichgene, myylab){
  p <-  timing  %>% 
  ggplot(aes(x = treatment, y = whichgene, fill = treatment,  color = sex)) +
    geom_boxplot() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none",
          strip.text = element_blank()) +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = NULL, subtitle = myylab, x = NULL) 
  return(p)
}

a <- plottiming(timing$PRL, "PRL")
b <- plottiming(timing$FOSL2, "FOSL2")
c <- plottiming(timing$COX1, "COX1")
d <- plottiming(timing$BRCA1, "BRCA1")
e <- plottiming(timing$CDK1, "CDK1")
f <- plottiming(timing$MYC, "MYC")

plot_grid(a + theme(axis.text.x = element_blank()),
          d + theme(axis.text.x = element_blank()),
          e + theme(axis.text.x = element_blank()), nrow = 1)


```


