---
title: "15_networks"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/favegenes/')

```

```{r}
library(tidyverse)
library(corrplot)
library(corrr)

source("../R/themes.R")

```

```{r getdata}
vsd.pituitary.df <- read.csv("../results/04_vsd_pit.csv", row.names = 1)
head(vsd.pituitary.df)

geneinfo <- read.csv("../metadata/00_geneinfo.csv", row.names = 1)
head(geneinfo)

vsd.pituitary.df$entrezid <- row.names(vsd.pituitary.df)
vsd.pituitary.df <- left_join(geneinfo, vsd.pituitary.df)
vsd.pituitary.df <- vsd.pituitary.df %>% dplyr::distinct(Name, .keep_all = TRUE) %>%
    dplyr::select(-row.names, -geneid, -entrezid) 
vsd.pituitary.df <- as.data.frame(vsd.pituitary.df)
row.names(vsd.pituitary.df) <- vsd.pituitary.df$Name
vsd.pituitary.df$Name <- NULL
head(vsd.pituitary.df)

colData <- read.csv("../metadata/00_samples.csv", header = T, row.names = 1)
colData$treatment <- factor(colData$treatment, levels = charlevels)
colData <- colData %>% filter(tissue == "pituitary")
row.names(colData) <- colData$V1

widecountdata <- as.data.frame(t(vsd.pituitary.df))
widecountdata$V1 <- row.names(widecountdata)
widecountdata <- left_join(colData, widecountdata)

head(widecountdata)
```


```{r boxplots}
# genes from website shown to be associate with oxt and prl
PRLgenes <- c("PRL", "GNRH1", "TRH", "POU1F1", "POMC", "TSHB",
              "FSHB", "GH", "PRLR", "JAK2", "SOCS1", "CISH")
OXTgenes <- c("OXT",  "AVPR1A", "AVPR1B", "TRH", 
              "HCRT", "GNRH1", "CRH", "POMC", "MC4R", "AVPR2")
CISHgenes <- c("CISH", "SOCS1", "SOCS2", "SOCS4", "SOCS5", "SOCS6")


PRLnOther <- c(PRLgenes,OXTgenes, CISHgenes)

# genes from wgcna pitutiry
PRL_associated <- read_csv("../results/08_PRL_associated.csv") %>%
  dplyr::pull(Name)
PRL_associated

# cancer genes from PRL list from  http://bioinformatics.sdstate.edu/go/
# shiny go for Gene Ontology Enrichment
cancergenes <- c("E2F1", "MYC" ,"PLK1", "BRCA1" ,"AURKA", "PRL")
cellcyclegenes <- c("E2F1", "MAD2L1", "MCM2", "PLK1", "MCM10", "BUB1", 
                    "CDC45", "CCNB3", "CCNA2", 
                      "CDK1", "CDC6", "CDC20")
replicationanddamage <- c("MCM2"  , "CDT1" , " CDC45 " , "CDC6", 
                          "E2F1" , " MYC" , "BRCA1" , "CCNB3 " , "CDK1")


## plot genes

longdata <- widecountdata %>% 
            select(V1:study, PRLnOther, PRL_associated) %>%
            gather(gene, expression, PRL:UBE2C)
head(longdata)

plotnetworkgenes <- function(whichgenes, mysubtitle){
  longdata %>%
  filter(gene %in% whichgenes) %>%
  ggplot(aes(x = as.numeric(treatment), y = expression)) +
        geom_smooth(aes(colour = sex)) +
    geom_boxplot(aes(fill = treatment, alpha = sex)) +
    mytheme() +
    theme(legend.position = "none",
          axis.text.x = element_blank()) +
    scale_fill_manual(values = colorschar) +
    scale_color_manual(values = sexcolors) +
    labs(x = NULL, subtitle = mysubtitle) +
    scale_alpha_manual(values = c(0.75,1)) +
  facet_wrap(~gene, scales = "free_y")
}

plotnetworkgenes(PRLgenes, "Known PRL associates") 
plotnetworkgenes(PRL_associated[85:93],  "in WGCNA module with PRL")
plotnetworkgenes(cancergenes, "genes in Breast Cancer WikiPathway")
plotnetworkgenes(cellcyclegenes, "genes in Cell Cycle WikiPathways ")

plotnetworkgenes(replicationanddamage, 
                 "genes in DNA Replication & Damage Response WikiPathway")

```

```{r correlations}
forcorrdata <- widecountdata %>% 
            select(cancergenes)  %>% 
            as.data.frame()
row.names(forcorrdata) <- forcorrdata$V1   
forcorrdata$V1 <- NULL
head(forcorrdata)

cormat <- cor(forcorrdata, method = c("spearman"), use = "complete.obs") 
head(cormat)

forcorrdata %>% 
  correlate() %>% 
  network_plot( colors = c("#67a9cf", "#ef8a62"))

forcorrdata %>% 
  correlate() %>% 
  rplot(shape = 15, colors = c("#67a9cf", "#ef8a62") ) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```

```{r wgcnaPRLgenes}
x <- widecountdata %>% 
            select(PRL_associated,PRLnOther) %>%
       correlate()     # Create correlation data frame (cor_df)
  
x %>% rearrange() %>%  # rearrange by correlations
       focus(POLQ:SGOL1, mirror = TRUE) %>%
     shave() %>% # Shave off the upper triangle for a clean result
       fashion()

x %>%  focus(POLQ:SGOL1, mirror = TRUE) %>%
  network_plot( colors = c("#67a9cf", "#ef8a62"))

x %>%
  focus(POLQ:SGOL1, mirror = TRUE) %>%
  shave(upper = FALSE) %>%
  rplot(shape = 15, colors = c("#67a9cf", "#ef8a62") ) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```