---
title: "plots with prolactin"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plots with Prolactin

```{r}
library(tidyverse)
library(cowplot)
library(magick)
library(png)
library(grid)
library(ggimage)
library(apaTables)

source("../R/themes.R") 
source("../R/functions.R")
source("../R/icons.R")

knitr::opts_chunk$set(fig.path = '../figures/PRL/',message=F, warning=FALSE)
```

## Circulating levels of prolactin

```{r data}
hormones <- read_csv("../results/hormones.csv")
hormones$treatment <- factor(hormones$treatment, levels = alllevels)

meanprolactin <- hormones %>% 
    filter(study == "characterization", hormone %in% c("prolactin"))  %>% 
    droplevels() %>% 
  dplyr::group_by(treatment) %>%
  dplyr::summarise(m = mean(plasma_conc), 
                   se = sd(plasma_conc)/sqrt(length(plasma_conc))) %>%
  dplyr::mutate(m = round(m,0)) 
meanprolactin <- left_join(meanprolactin, birds)
meanprolactin$treatment <- factor(meanprolactin$treatment, levels = alllevels)
meanprolactin

```



```{r hormone}
p1 <- hormones %>% 
    filter(study == "characterization", hormone %in% c("prolactin"))  %>% 
    droplevels() %>% 
  ggplot(aes(x = treatment, y = plasma_conc)) +
    geom_boxplot(aes(fill = treatment, alpha = sex, color = sex)) +
    theme_B3() +
    scale_fill_manual(values = colorscharmaip) +
    scale_color_manual(values = sexcolors) +
    labs(y = "prolactin (ng/mL)", x = NULL) +
    guides(fill = FALSE, alpha = FALSE,
         color = guide_legend(order=1)) +
    scale_alpha_manual(values = c(0.75,1)) +
    theme(legend.position = c(0.85,0.15), legend.direction = "horizontal") + 
  labs(x = "increasing time >>", y = "prolactin (ng/mL)")
p1

p1 +
  annotation_custom(control, ymin = -20, ymax = 0, xmin = -7.8) +
  annotation_custom(bldg, ymin = -20, ymax = 0, xmin = -5.8) +
  annotation_custom(lay, ymin = -20, ymax = 0, xmin = -3.8) +
  annotation_custom(inc, ymin = -20, ymax = 0, xmin = -1.8) +
  annotation_custom(inc, ymin = -20, ymax = 0, xmin = 0.6) +
  annotation_custom(inc, ymin = -20, ymax = 0, xmin = 2.4) +
  annotation_custom(hatch, ymin = -20, ymax = 0, xmin = 4.4) +
  annotation_custom(nestling, ymin = -20, ymax = 0, xmin = 6.4) +
  annotation_custom(nestling, ymin = -20, ymax = 0, xmin = 8.4) + 
  ylim(c(-10,120)) 

```


## Prolactin (_PRL_) and _BRCA1_ expression in the pituitary

```{r candidatevsds}
colData.pit <-  read.csv("../metadata/00_samples.csv", header = T, row.names = 1)
colData.pit <- colData.pit %>% filter(tissue == "pituitary")

vsd.pit <- read.csv("../results/06_pitallvsd.csv", header = T, row.names = 1)

savecols <- as.character(colData.pit$V1) 
savecols <- as.vector(savecols) 
vsd.pit <- vsd.pit %>% dplyr::select(one_of(savecols)) 
vsd.pit$genes <- row.names(vsd.pit)

candidategenes <- c("PRL", "BRCA1")
candidates.pit <- vsd.pit %>% dplyr::filter(genes %in% candidategenes)
candidates.pit <- as.data.frame(candidates.pit)
row.names(candidates.pit) <- candidates.pit$genes
candidates.pit$genes <- NULL
candidates.pit <- as.data.frame(t(candidates.pit))
candidates.pit$V1 <- row.names(candidates.pit) 
candidates.pit <- left_join(colData.pit, candidates.pit)
candidates.pit$treatment <- factor(candidates.pit$treatment, levels = alllevels)
tail(candidates.pit)
```

```{r PRL.pit}
meanPRL <- candidates.pit %>% 
    droplevels() %>% 
  dplyr::group_by(treatment, sex) %>%
  dplyr::summarise(m = mean(PRL), 
                   se = sd(PRL)/sqrt(length(PRL))) %>%
  dplyr::mutate(m = round(m,1))  %>%
  dplyr::filter(treatment %in% charlevels)
meanPRL <- left_join(meanPRL, birds)
meanPRL$treatment <- factor(meanPRL$treatment, levels = charlevels)
meanPRL


p2 <- candidates.pit %>%
  dplyr::filter(treatment %in% charlevels) %>%
  ggplot(aes(x = treatment, y = PRL)) + 
    geom_boxplot(aes(fill = treatment, alpha = sex, color = sex)) + 
    scale_alpha_manual(values = c(0.75,1)) +
    theme_B3() +
  theme(legend.position = c(0.85,0.2), legend.direction = "horizontal") + 
  scale_color_manual(values = c("female" = "#969696", "male" = "#525252")) +
  labs(y = "PRL", x = "increasing time >>", subtitle = "Pituitary" ) +
  guides(fill = FALSE, alpha = FALSE, color = guide_legend(order=1)) +
  theme(axis.title.y  = element_text(face = "italic"))  +
  annotation_custom(control, ymin = 13.5, ymax = 15, xmin = -7.5) +
  annotation_custom(bldg, ymin = 13.5, ymax = 15, xmin = -5.5) +
  annotation_custom(lay, ymin = 13.5, ymax = 15, xmin = -3.5) +
  annotation_custom(inc, ymin = 13.5, ymax = 15, xmin = -1.5) +
  annotation_custom(inc, ymin = 13.5, ymax = 15, xmin = 0.5) +
  annotation_custom(inc, ymin = 13.5, ymax = 15, xmin = 2.5) +
  annotation_custom(hatch, ymin = 13.5, ymax = 15, xmin = 4.5) +
  annotation_custom(nestling, ymin = 13.5, ymax = 15, xmin = 6.5) +
  annotation_custom(nestling, ymin = 13.5, ymax = 15, xmin = 8.5)   
p2

```

```{r hormonesandgenes}
plot_grid(p1 + theme(legend.position ="none",
                     axis.title.x = element_blank(),
                     axis.text.x = element_blank()),
          p2 + theme(legend.position = c(0.85,0.3)) +
            labs(subtitle = NULL) +
  annotation_custom(control, ymin = 13.5, ymax = 15.5, xmin = -7.5) +
  annotation_custom(bldg, ymin = 13.5, ymax = 15.5, xmin = -5.5) +
  annotation_custom(lay, ymin = 13.5, ymax = 15.5, xmin = -3.5) +
  annotation_custom(inc, ymin = 13.5, ymax = 15.5, xmin = -1.5) +
  annotation_custom(inc, ymin = 13.5, ymax = 15.5, xmin = 0.5) +
  annotation_custom(inc, ymin = 13.5, ymax = 15.5, xmin = 2.5) +
  annotation_custom(hatch, ymin = 13.5, ymax = 15.5, xmin = 4.5) +
  annotation_custom(nestling, ymin = 13.5, ymax = 15.5, xmin = 6.5) +
  annotation_custom(nestling, ymin = 13.5, ymax = 15.5, xmin = 8.5), 
          nrow = 2,rel_heights = c(0.4,0.6)) 
```



```{r PRLBRCA1}
meanBRCA <- candidates.pit %>% 
    droplevels() %>% 
  dplyr::group_by(treatment, sex) %>%
  dplyr::summarise(m = mean(BRCA1), 
                   se = sd(BRCA1)/sqrt(length(BRCA1))) %>%
  dplyr::mutate(m = round(m,1)) %>%
  dplyr::filter(treatment %in% charlevels)
meanBRCA <- left_join(meanBRCA, birds)
meanBRCA$treatment <- factor(meanBRCA$treatment, levels = alllevels)
meanBRCA

p3 <- candidates.pit %>% 
  dplyr::filter(treatment %in% charlevels) %>%
  ggplot(aes(x = treatment, y = BRCA1, fill = treatment, color = sex, alpha = sex)) +
    geom_boxplot() +
    theme_B3() +
      scale_alpha_manual(values = c(0.75,1)) +
  scale_color_manual(values = c("female" = "#969696", "male" = "#525252")) +
  theme(legend.position = "none") + 
  labs(x = "increasing time >>", y = "BRCA1", subtitle = "Pituitary") +
  annotation_custom(control, ymin = 6.65, ymax = 7, xmin = -7.8) +
  annotation_custom(bldg, ymin = 6.65, ymax = 7, xmin = -5.8) +
  annotation_custom(lay, ymin = 6.65, ymax = 7, xmin = -3.8) +
  annotation_custom(inc, ymin = 6.65, ymax = 7, xmin = -1.8) +
  annotation_custom(inc, ymin = 6.65, ymax = 7, xmin = 0.6) +
  annotation_custom(inc, ymin = 6.65, ymax = 7, xmin = 2.4) +
  annotation_custom(hatch, ymin = 6.65, ymax = 7, xmin = 4.4) +
  annotation_custom(nestling, ymin = 6.65, ymax = 7, xmin = 6.4) +
  annotation_custom(nestling, ymin = 6.65, ymax = 7, xmin = 8.4) +
  ylim(6.8,8.5) +
  guides(fill = FALSE, alpha = FALSE, color = guide_legend(order=1)) +
  theme(legend.position = c(0.85,0.2), legend.direction = "horizontal") + 
  theme(axis.title.y  = element_text(face = "italic"))
p3


```

## Manipulation of parental care and _PRL_ and _BRCA1_ expression



```{r PRL.pit.maip}

p4 <- ggplot(candidates.pit, aes(x = treatment, y = PRL)) + 
    geom_boxplot(aes(fill = treatment, alpha = sex)) +
    scale_alpha_manual(values = c(0.75,1)) +
    theme_B3() +
   theme(legend.position = "none", legend.direction = "horizontal") + 
   scale_color_manual(values = c("female" = "#969696", "male" = "#525252")) +
  labs(x = "increasing time >>", y = "PRL", subtitle = "Pituitary") +
  scale_fill_manual(values = colorscharmaip2) +
  ylim(c(13,22.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  annotation_custom(control, ymin = 13, ymax = 14, xmin = -14.8) +
  annotation_custom(bldg, ymin = 13, ymax = 14, xmin = -12.8) +
  annotation_custom(lay, ymin = 13, ymax = 14, xmin = -10.8) +
  annotation_custom(inc, ymin = 13, ymax = 14, xmin = -8.8) +
  annotation_custom(removeegg, ymin = 13, ymax = 14, xmin = -6.8) +
  annotation_custom(inc, ymin = 13, ymax = 14, xmin = -4.8) +
  annotation_custom(maniphatch, ymin = 13, ymax = 14, xmin = -2.8) +
  annotation_custom(removeegg, ymin = 13, ymax = 14, xmin = -0.8) +
  annotation_custom(inc, ymin = 13, ymax = 14, xmin = 1.4) +
  annotation_custom(removeegg, ymin = 13, ymax = 14, xmin = 3.4)  +
  annotation_custom(manipinc, ymin = 13, ymax = 14, xmin = 5.4) +
  annotation_custom(hatch, ymin = 13, ymax = 14, xmin = 7.4) +
  annotation_custom(removechick, ymin = 13, ymax = 14, xmin = 9.4) +
  annotation_custom(maniphatch, ymin = 13, ymax = 14, xmin = 11.4) +
  annotation_custom(nestling, ymin = 13, ymax = 14, xmin = 13.4) +
  annotation_custom(nestling, ymin = 13, ymax = 14, xmin = 15.4) +
    theme(axis.title.y  = element_text(face = "italic"))
p4


```



```{r BRCA.pit.maip}

p5 <- ggplot(candidates.pit, aes(x = treatment, y = BRCA1)) + 
    geom_boxplot(aes(fill = treatment, alpha = sex)) +
    scale_alpha_manual(values = c(0.75,1)) +
    theme_B3() +
   theme(legend.position = "none", legend.direction = "horizontal") + 
   scale_color_manual(values = c("female" = "#969696", "male" = "#525252")) +
  labs(x = "increasing time >>", y = "BRCA1", subtitle = "Pituitary") +
  scale_fill_manual(values = colorscharmaip2) +
  ylim(6.8,8.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  annotation_custom(control, ymin = 13, ymax = 14, xmin = -14.8) +
  annotation_custom(bldg, ymin = 13, ymax = 14, xmin = -12.8) +
  annotation_custom(lay, ymin = 13, ymax = 14, xmin = -10.8) +
  annotation_custom(inc, ymin = 13, ymax = 14, xmin = -8.8) +
  annotation_custom(removeegg, ymin = 13, ymax = 14, xmin = -6.8) +
  annotation_custom(inc, ymin = 13, ymax = 14, xmin = -4.8) +
  annotation_custom(maniphatch, ymin = 13, ymax = 14, xmin = -2.8) +
  annotation_custom(removeegg, ymin = 13, ymax = 14, xmin = -0.8) +
  annotation_custom(inc, ymin = 13, ymax = 14, xmin = 1.4) +
  annotation_custom(removeegg, ymin = 13, ymax = 14, xmin = 3.4)  +
  annotation_custom(manipinc, ymin = 13, ymax = 14, xmin = 5.4) +
  annotation_custom(hatch, ymin = 13, ymax = 14, xmin = 7.4) +
  annotation_custom(removechick, ymin = 13, ymax = 14, xmin = 9.4) +
  annotation_custom(maniphatch, ymin = 13, ymax = 14, xmin = 11.4) +
  annotation_custom(nestling, ymin = 13, ymax = 14, xmin = 13.4) +
  annotation_custom(nestling, ymin = 13, ymax = 14, xmin = 15.4) +
    theme(axis.title.y  = element_text(face = "italic"))
p5


ggplot(candidates.pit, aes(x = PRL, y = BRCA1)) +
  geom_point(aes(alpha = sex,  color = 	treatment)) +
  geom_smooth(method = "loess", se=T, color = "darkgrey") +
  scale_color_manual(values = colorscharmaip2)  +
  scale_alpha_manual(values = c(0.5,1)) +
  labs(subtitle = "Pituitary") +
  theme(axis.title  = element_text(face = "italic"),
        legend.title =  element_blank())

candidates.pit %>%
  filter(treatment %in% charlevels) %>%
ggplot( aes(x = PRL, y = BRCA1)) +
  geom_point(aes(alpha = sex,  color = 	treatment)) +
  geom_smooth(method = "loess", se=T, color = "darkgrey") +
  scale_color_manual(values = colorscharmaip2)  +
  scale_alpha_manual(values = c(0.5,1)) +
  labs(subtitle = "Pituitary") +
  theme(axis.title  = element_text(face = "italic"),
        legend.title =  element_blank())

```

## Genes an hormones (in progress, don't have all the bird ids lining up.)

```{r geneshormones}
candidates.pit$bird_id <- candidates.pit$bird
candidates.pit$X1 <- candidates.pit$V1

geneshormones <- left_join(candidates.pit, hormones) %>%
  select(-X1, -V1, -okay, - icons, -music, -iconpath) %>%
  drop_na()

head(geneshormones$bird_id)
head(hormones$bird_id)

ggplot(geneshormones, aes(x = plasma_conc, y = PRL)) +
  geom_point(aes(color = treatment)) +
  facet_wrap(~hormone, scales = "free_x") +
    geom_smooth(method = "lm", color = "grey") 


prolactin2 <- read_csv("../results/07_prolactin2.csv")
head(prolactin2)
geneshormones2 <- left_join(candidates.pit, prolactin2) %>%
  drop_na()
head(geneshormones)


ggplot(geneshormones2, aes(x = plasma_conc, y = PRL)) +
  geom_point(aes( color = treatment)) +
  geom_smooth(method = "lm", color = "grey") +
  facet_wrap(~hormone, scales = "free") 
```

## Prolactin hormone statistics

```{r}
aov_all = data.frame()
for(i in alllevels3){
  
  df <- candidates.pit %>% filter(treatment == i) %>% droplevels()
  aovtable <- apa.aov.table(aov(PRL ~ sex , data=df))
  aovtable <- as.data.frame(aovtable$table_body)
  totaldf <- aovtable[3, 3]
  aovtable$df <- paste(aovtable$df, ", " , totaldf, sep = "")
  aovtable$ANOVA <- "PRL ~ sex"
  aovtable$stages <- paste(i)
  aovtable$p <- as.numeric(as.character(aovtable$p))
  aov_all <- rbind(aov_all,aovtable)
}

aov_all <- aov_all %>%
  filter(Predictor == "sex")  %>%
  select(stages, ANOVA, df, "F", p) %>%
  mutate(sig = ifelse(p < 0.05, "*", " "))
aov_all

one <- c("m.inc.d3", "inc.d3")
two <- c("m.inc.d9", "inc.d9")
three <- c("m.inc.d17", "inc.d17")
four <- c("m.n2", "hatch")
five <- c("m.inc.d8", "inc.d9")
six <- c("m.inc.d8", "hatch")
seven <- c("prolong", "inc.d17")
eight <- c("prolong", "hatch")
nine <- c("extend", "hatch")
ten <- c("extend", "n5")

manipcomparisons <- list(one, two, three, four, five, six, seven, eight, nine, ten)

aov_manip = data.frame()
for(i in manipcomparisons){
  
  df <- candidates.pit %>% filter(treatment %in% i) %>% droplevels()
  aovtable <- apa.aov.table(aov(PRL ~ sex * treatment , data=df))
  aovtable <- as.data.frame(aovtable$table_body)
  totaldf <- aovtable[5, 3]
  aovtable$df <- paste(aovtable$df, ", " , totaldf, sep = "")
  aovtable$ANOVA <- "PRL ~ sex"
  aovtable$stages <- paste(i, collapse = " vs ")
  aovtable$p <- as.numeric(as.character(aovtable$p))
  aov_manip <- rbind(aov_manip,aovtable)
}

aov_manip  <- aov_manip %>%
  filter(Predictor %in% c( "treatment"))  %>%
  select(stages, ANOVA, Predictor, df, "F", p) %>%
  mutate(sig = ifelse(p < 0.05, "*", " "))
aov_manip
```


```{r music, fig.height=6, fig.width=6}

meanPRL <- candidates.pit %>% 
    droplevels() %>% 
  dplyr::group_by(treatment) %>%
  dplyr::summarise(m = mean(PRL), 
                   se = sd(PRL)/sqrt(length(PRL))) %>%
  dplyr::mutate(m = round(m,1))  %>%
  dplyr::filter(treatment %in% charlevels)
meanPRL <- left_join(meanPRL, birds)
meanPRL$treatment <- factor(meanPRL$treatment, levels = charlevels)

p8 <- ggplot(meanPRL, aes(treatment, m)) +
   geom_image(aes(image=music), size=.12)  +
  labs(x = "parental care stages", y = "PRL", subtitle = "Pituitary") +
  mytheme() +
  ylim(c(15,22)) +
  annotation_custom(control, ymin = 15, ymax = 16.5, xmin = -7.5) +
  annotation_custom(bldg, ymin = 15, ymax = 16.5, xmin = -5.5) +
  annotation_custom(lay, ymin = 15, ymax = 16.5, xmin = -3.5) +
  annotation_custom(inc, ymin = 15, ymax = 16.5, xmin = -1.5) +
  annotation_custom(inc, ymin = 15, ymax = 16.5, xmin = 0.5) +
  annotation_custom(inc, ymin = 15, ymax = 16.5, xmin = 2.5) +
  annotation_custom(hatch, ymin = 15, ymax = 16.5, xmin = 4.5) +
  annotation_custom(nestling, ymin = 15, ymax = 16.5, xmin = 6.5) +
  annotation_custom(nestling, ymin = 15, ymax = 16.5, xmin = 8.5)   +
  geom_hline(yintercept=17) +
  geom_hline(yintercept=18) +
  geom_hline(yintercept=19) +
  geom_hline(yintercept=20) +
  geom_hline(yintercept=21) +
  theme(axis.title.y  = element_text(face = "italic"))

p8

p9 <- ggplot(meanPRL, aes(treatment, m)) +
   geom_image(aes(image=music), size=.12)  +
  mytheme() +
  ylim(c(15,22)) +
  geom_hline(yintercept=17) +
  geom_hline(yintercept=18) +
  geom_hline(yintercept=19) +
  geom_hline(yintercept=20) +
  geom_hline(yintercept=21) +
  theme(axis.text  = element_blank(),
        axis.title = element_blank())

p9


p10 <- candidates.pit %>%
  dplyr::filter(treatment %in% charlevels) %>%
  ggplot(aes(x = treatment, y = PRL)) + 
    geom_boxplot(aes(fill = treatment)) + 
    scale_alpha_manual(values = c(0.75,1)) +
    theme_B3() +
  theme(legend.position = c(0.85,0.2), legend.direction = "horizontal") + 
  scale_color_manual(values = c("female" = "#969696", "male" = "#525252")) +
  labs(y = "Prolactin expression", x = "parental stage") +
  guides(fill = FALSE, alpha = FALSE, color = guide_legend(order=1)) 
p10

plot_grid(p10,p9, nrow = 2, align = "hv")
```


## WGCNA candidates

```{r WGCNAcandidates}

#WGCNAgenes <- read_csv("../results/08_PRL_associated.csv") %>% pull(x)
#WGCNAgenes <- c("FBXO5", "NUF2", "PTTG1", "BUB1", "PRL", "ASPM", "AURKA", "CDC20", "NEK2", "CKS2", 
#                  "MYC", "CCNB3", "FANCC", "STC1", "RACGAP1", "E2F7", "PLK1", "EXO1", "CENPI", "CDK1")
WGCNAgenes <- c("PRL", "PAX7", "ASPM", "AURKA",  "CDC20", "CENPF", "MYC",  "CDK1", "LBH", "BRCA1", "FOXM1", "FBXO5")


WGCNAgenes.pit <- vsd.pit %>% dplyr::filter(genes %in% WGCNAgenes)
WGCNAgenes.pit <- as.data.frame(WGCNAgenes.pit)
row.names(WGCNAgenes.pit) <- WGCNAgenes.pit$genes
WGCNAgenes.pit <- pivot_longer(WGCNAgenes.pit, -genes, names_to = "V1", values_to = "expression")
head(WGCNAgenes.pit)
WGCNAgenes.pit <- left_join(colData.pit, WGCNAgenes.pit) %>%
  filter(study == "charcterization")
WGCNAgenes.pit$treatment <- factor(WGCNAgenes.pit$treatment, levels = alllevels)

WGCNAgenes.pit$genes <- factor(WGCNAgenes.pit$genes)
WGCNAgenes.pit$genesnum <- round(as.numeric(WGCNAgenes.pit$genes), digits = -1)


p1 <- ggplot(WGCNAgenes.pit, aes(x = treatment, y = expression)) +
  geom_boxplot(aes(fill = treatment)) +
  facet_wrap(~genes, scales = "free_y") +
  theme_B3() +
  theme(legend.position = "none") +
  #scale_color_manual(values = sexcolors) +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        strip.background = element_blank(),
        strip.text = element_text(face = "italic")) +
  labs( x = "parental stage", y = "pituitary expression",
        subtitle = "Genes that are coexpressed with prolactin and regulate development")
p1
  

```




```{r}
write.csv(candidates.pit, "../results/16_pitPRL.csv")
write.csv(aov_all, "../results/16_aov_PRLsex.csv")
write.csv(aov_manip, "../results/16_aov_PRLsextreatment.csv")
```

