---
title: "volcanos"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
source("../R/themes.R")

knitr::opts_chunk$set(echo = TRUE, message = F, fig.path = "../figures/favegenes/")
```

## DEGs

```{r volcanobars, DEGs}

DEG_path <- "../results/"   # path to the data
DEG_files <- dir(DEG_path, pattern = "03_DEGs.*") # get file names
DEG_pathfiles <- paste0(DEG_path, DEG_files)
DEG_files

allDEG <- DEG_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name") %>% 
  mutate(DEG = sapply(strsplit(as.character(file_name),'../results/03_DEGs.'), "[", 2))  %>% 
  mutate(DEG = sapply(strsplit(as.character(DEG),'.csv'), "[", 1))  %>% 
  mutate(tissue = sapply(strsplit(as.character(DEG),'\\.'), "[", 1)) %>%
   mutate(DEG = gsub("m.inc", "m_inc", DEG)) %>%
   mutate(DEG = gsub("inc.d", "inc_d", DEG))  %>%
  mutate(down = sapply(strsplit(as.character(DEG),'\\.'), "[", 2)) %>%
  mutate(up = sapply(strsplit(as.character(DEG),'\\.'), "[", 3)) %>%
  mutate(comparison = paste(down,up, sep = ".")) %>%
  select(tissue, comparison, direction, down, up, gene, lfc, padj, logpadj) 
head(allDEG)

allDEG$tissue <- factor(allDEG$tissue , levels = tissuelevels)
allDEG$comparison <- factor(allDEG$comparison , levels = comparisonlevels)
allDEG$direction <- factor(allDEG$direction, levels = charlevels)

allDEG <- allDEG %>% drop_na()

ggplot(allDEG, aes(x = lfc, y = logpadj)) +
  geom_point(aes(color = direction), alpha = 0.75) +
  facet_grid(tissue ~ comparison)  +
  scale_color_manual(values = colorscharnew,
                       name = " ",
                       drop = FALSE) +
  theme_B3() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")  +
  guides(color = guide_legend(nrow = 1))


ggplot(allDEG, aes(x = lfc)) +
  geom_histogram(aes( fill = direction)) +
  facet_grid(tissue ~ comparison)  +
  scale_color_manual(values = colorscharnew,
                       name = " ",
                       drop = FALSE) +
  theme_B3() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")  +
  guides(fill = guide_legend(nrow = 1)) 

ggplot(allDEG, aes(x = comparison,  fill = direction)) +
  geom_bar(position = "dodge") +
  facet_wrap(~tissue, nrow = 3) +
  theme_B3() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.placement = "right")  +
  guides(fill = guide_legend(nrow = 1)) +
  labs(x = "differntial expression between sequential stages", y = "total DEGs") +
  scale_fill_manual(values = colorscharnew,
                       name = " ",
                       drop = FALSE) +
  geom_text(stat='count', aes(label=..count..), vjust=-0.5, 
            position = position_dodge(width = 1),
            size = 3) +
  ylim(0,5000)

```