---
title: "98_bilingual.Rmd"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/espanol/')

library(tidyverse)
library(cowplot)
library(datos)
```


```{r cars}
theme_rmh <- function(){ 
    theme_bw(base_size=10) +
        theme(
            panel.grid.minor.x  = element_blank(),
           panel.grid.minor.y  = element_blank(),
            strip.background = element_rect(colour="white", fill="white"),
              legend.position = "bottom",           
           legend.margin=margin(t=-0.1, r=0, b=-0.1, l=-0.1, unit="cm"),
           legend.key.size = unit(0.5, "cm"))
}

bar1 <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
labs("cut", y = NULL ,
       subtitle = "Frequency of diamond cuts") +
  coord_flip() +
  theme_rmh()


bar2 <- ggplot(data = diamantes) + 
geom_bar(
 mapping = aes(x = corte, fill = corte), 
 show.legend = FALSE,
 width = 1
) + 
theme(aspect.ratio = 1) +
labs(x = "corte", y = NULL ,
     subtitle = "Frecuencia de cortes de diamante") + coord_flip()  +
  theme_rmh()




plot_grid(bar2)


```
