

## Treatment specific DEGs 

```{r suppltables}
allDEG <- read_csv("../results/03_allDEG.csv") %>%
  mutate(tissue = factor(tissue, levels = tissuelevel),
         direction = factor(direction, levels = alllevels))

# for figure
DEGchar <- allDEG %>% 
  filter(comparison %in% comparisonlevelschar) %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelschar))

# for suppl figures
DEGcontrol <- allDEG %>% 
  filter(grepl("control", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelscontrol))

DEGbldg <- allDEG %>% 
  filter(grepl("bldg", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelsbldg))  %>%
  drop_na()
```

## Sex and Tissue -related DEGs

```{r DEGs, message=F}

## other DEG stuff

pitsex <- read_csv("../results/DEseq2/sex/pituitary_female_male_DEGs.csv")
gonsex <- read_csv("../results/DEseq2/sex/gonad_female_male_DEGs.csv")

hyppit <- read_csv("../results/DEseq2/tissue/hypothalamus_pituitary_DEGs.csv") 
hypgon <- read_csv("../results/DEseq2/tissue/hypothalamus_gonad_DEGs.csv")
pitgon <- read_csv("../results/DEseq2/tissue/pituitary_gonad_DEGs.csv")

hyppit$direction <- factor(hyppit$direction, levels = c("hypothalamus", "pituitary"))
hypgon$direction <- factor(hypgon$direction, levels = c("hypothalamus",  "gonad"))
pitgon$direction <- factor(pitgon$direction, levels = c( "pituitary", "gonad"))

```

```{r barplots}

b2 <- sexbarplots(hyppit, 0, 8100) + labs(subtitle = " ", y = "DEGs w/ + LFC") +
  theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
  scale_x_discrete(labels=c("hypothalamus" = "hyp", "pituitary" = "pit" ))
b3 <- sexbarplots(hypgon, 0, 8100) + labs(subtitle = " " ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(), 
        axis.ticks = element_blank(), axis.title.y = element_blank()) +
    scale_x_discrete(labels=c("hypothalamus" = "hyp",  "gonad" = "gon"))
b4 <- sexbarplots(pitgon, 0, 8100) + labs(subtitle = " " ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank()) +
    scale_x_discrete(labels=c(  "pituitary" = "pit", "gonad" = "gon"))

    

c3 <- sexbarplots(pitsex, 0, 8100) + labs(subtitle = "pituitary" ) + 
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank())
c4 <- sexbarplots(gonsex, 0, 8100) + labs(subtitle = "gonads" ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank())
bc <- plot_grid(b1,b2,b3,b4, c1,c2,c3,c4, nrow = 1, rel_widths = c(1.5,1.1,0.9,0.9,1.5,1.1,0.9,0.9),
                labels = c("A", "", "", "", "B"), label_size = 8)
```


## suppl fig 1 controls versus bldg

```{r supplfig-1, fig.width=5, fig.height=5}


s1c <- makebargraphsuppl(DEGcontrol, "pituitary","DEGs w/ + LFC", 0, 5000)  +  
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        strip.text.x = element_blank())    + 
  labs(subtitle = "pituitary") 
s1e <- makebargraphsuppl(DEGcontrol, "gonad","DEGs w/ + LFC", 0, 5000) +  
  theme(strip.text.x = element_blank()) +
  scale_x_discrete(labels = comparisonlabelscontrol) +
  labs(subtitle = "gonads") 
  

 
s1d <- makebargraphsuppl(DEGbldg, "pituitary",NULL, 0, 1000)  +  
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        strip.text.x = element_blank())   
s1f <- makebargraphsuppl(DEGbldg, "gonad",NULL, 0, 1000) +  
  theme(strip.text.x = element_blank()) +
  scale_x_discrete(labels = comparisonlabelsbldg) 

s1 <- plot_grid(s1a, s1b, 
          s1c, s1d, 
          s1e, s1f, nrow = 3,
          rel_heights = c(1,0.9,1.3),
          labels = c("A", "B"), label_size = 8, rel_widths = c(1.1,1))


sa <- png::readPNG("../figures/images/fig_supplfig-1.png")
sa <- ggdraw() +  draw_image(sa, scale = 1)

supplfig1 <- plot_grid(s1, sa, ncol = 1, rel_heights = c(2,0.7))
supplfig1

# for volcano plots

pitinc <- DEGchar %>% filter(tissue == "pituitary", comparison == "inc.d9_inc.d17") 
goninc <- DEGchar %>% filter(tissue == "gonad", comparison == "lay_inc.d3") 

s2a <- plot.volcano("hypothalamus", sexlevels,  "hatch_n5") + facet_wrap(~sex) + 
  labs(subtitle = "hypothalamus", title = "Volcano plots") 
s2c <- plot.volcano("pituitary", sexlevels,  "inc.d9_inc.d17") + 
  facet_wrap(~sex) + 
  labs(subtitle = "pitutiary") + 
  theme(legend.title = element_blank(), strip.text = element_blank())
s2e <- plot.volcano("gonad", sexlevels,  "lay_inc.d3") + facet_wrap(~sex) + 
  labs( x = "Log-fold change (LFC)", subtitle = "gonads") + 
  theme(legend.title = element_blank(), strip.text = element_blank())

s2b <- makebargraph(hyphatch, "hypothalamus","Total DEGs with +LFC", 0, 1800)  + 
  labs(subtitle = " ", title = "Bar graphs") + scale_x_discrete(labels = "hatch\nvs n5")
s2d <- makebargraph(pitinc, "pituitary","Total DEGs with +LFC", 0, 1800) + 
  labs(subtitle = " ") + scale_x_discrete(labels = "inc.d9 vs\ninc.d17") + 
  theme(strip.text = element_blank())
s2f <- makebargraph(goninc, "gonad","Total DEGs with +LFC", 0, 1800) + 
  labs(subtitle = " ", x = "stages compared") + scale_x_discrete(labels = "lay vs\ninc.d3") + 
  theme(strip.text = element_blank())
supplfig2 <- plot_grid(s2a, s2b, s2c, s2d, s2e, s2f,
          rel_widths = c(2,1), rel_heights = c(1.1,1,1.1), ncol = 2,
          labels = c("A", "B"), label_size = 8)
supplfig2
```

```{r}
suppltable1 <- DEGchar %>%
  arrange( tissue, sex, direction, gene)
head(suppltable1)
write_csv(suppltable1, "../results/suppltable1.csv")

suppltable2 <- rbind(DEGcontrol, DEGbldg)  %>%
  arrange( tissue, sex, direction, gene)
head(suppltable2)
write_csv(suppltable2, "../results/suppltable2.csv")

```


```{r}
## prlpit
PRLpit <- candidatevsd %>% 
  filter(gene == "PRL", tissue == "pituitary")

# list of pvalue and DEGs
allDEG <- read_csv("../results/06_allDEG.csv")  %>%
  mutate(direction = factor(direction, levels = hypothesislevels))

# DEGs infor for PRL and external
hilodf <- allDEG %>%
  filter(comparison == "lo_hi")  %>%
  arrange(padj) 
hilogenes <- hilodf %>%  top_n(20) %>% pull(gene)

eggchickdf <- allDEG %>%
  filter(!comparison %in% c("lo_hi", "nest_eggs", "nest_chicks"))  %>%
  arrange(padj)  
eggchickgenes <- eggchickdf %>%  top_n(20) %>% pull(gene)


## data-driven PRL genes
pithilo <- makecorrdf("female", "pituitary", hilogenes)
pitWGCNA <- makecorrdf("female", "pituitary", WGCNAgenes[32:52])


## https://www.gynecologiconcology-online.net/article/S0090-8258(19)30069-1/fulltext
cancergenes <- makecorrdf("female", "pituitary", c(shaidgenes,suszynskaagenes, "PRL"))


## for scatter correlation (not currently usesed)
candidatevsdwide <- candidatevsd  %>%
    pivot_wider(names_from = gene, values_from = counts) 
pitwide <- subsetcandidatevsdwide(sexlevels, "pituitary")

## number of genes total vs plotted

eggchickdf %>% filter(tissue == "pituitary") %>% nrow()
hilodf %>% filter(tissue == "pituitary") %>% nrow()
length(WGCNAgenes)


b1 <- png::readPNG("../figures/images/fig_fig3b.png")
b1 <- ggdraw() +  draw_image(b1, scale = 1)

b2 <- makenewbargraph("pituitary", "female","eggs_chicks", 0, 4000) + labs(subtitle = "female")  + labs(title = " ") +
  scale_x_discrete(labels = "eggs vs. chicks")
b3 <- makenewbargraph("pituitary", "male", "eggs_chicks", 0, 4000)  + labs(subtitle = "male")  + labs(title = " ") +
  theme(axis.title.y = element_blank(), axis.ticks.y = element_blank(), 
        axis.text.y = element_blank(), axis.line.y = element_blank()) +
  scale_x_discrete(labels = "eggs vs. chicks")
b4 <- makenewbargraph("pituitary", "male", "lo_hi", 0, 4000)  +
  scale_x_discrete(labels = "lo vs. hi PRL")
b5 <- makenewbargraph("pituitary", "female", "lo_hi", 0, 4000)   + 
  theme(axis.title.y = element_blank(), axis.ticks.y = element_blank(), 
        axis.text.y = element_blank(), axis.line.y = element_blank()) +
  scale_x_discrete(labels = "lo vs. hi PRL")
b25 <- plot_grid(b2,b3,b4,b5, nrow = 2, rel_widths = c(1.2,1), rel_heights = c(1.2,1))

b6 <-  plottopDEGs(eggchickdf, "female",  "LFC eggs vs. chicks", "Top 10 female DEGs") + labs(title = " ")
b7 <-  plottopDEGs(eggchickdf, "male",  "LFC eggs vs. chicks", "Top 10 male DEGs") + labs(title = " ")
b8 <-  plottopDEGs(hilodf, "female",  "LFC lo vs. hi PRL", NULL)
b9 <-  plottopDEGs(hilodf, "male",  "LFC lo vs. hi PRL", NULL)
b15 <- plot_grid(b1,b25,nrow = 1, rel_widths = c(1.2,1))
b69 <- plot_grid(b6,b7,b8,b9, align = "v" , rel_heights = c(1.2,1))
b <- plot_grid(b15,b69, labels = c("C"), label_size = 8, rel_widths = c(1.2,1))

c1 <- plotcorrplot(pithilo, NULL) + theme(legend.position = "none") + labs(subtitle = "Top 20 DEGs, low vs. high PRL") 
c2 <- plotcorrplot(pitWGCNA, NULL) + theme(legend.position = "none") + labs(subtitle = "20 genes in WGCNA module with PRL") 
c3 <- plotcorrplot(cancergenes, NULL) + theme(legend.position = "right") + labs(subtitle = "Breast, ovary, & piuitary cancer genes", color = "Correlation")
c <- plot_grid(c1,c2,c3, nrow = 1, labels = c("D"), label_size = 8, rel_widths = c(1,1,1.3))

fig3 <- plot_grid(a, b, c, nrow = 3, rel_heights = c(1.2,2,1.8))
fig3
```


## tsne


```{r tSNE}

# removal
hyptsne <- subsetmaketsne("hypothalamus", removallevels, sexlevels)
pittsne <- subsetmaketsne("pituitary", removallevels, sexlevels)
gontsne <- subsetmaketsne("gonads", removallevels, sexlevels)

pittsne <- addgroupings(pittsne)

t4 <- plottsneelipsev2(pittsne, pittsne$treatment, allcolors) +  labs(title = "pituitary ", subtitle = "parental stage and manipulations") +
  facet_wrap(~sex) 
t5 <- plottsneelipsev2(pittsne, pittsne$extint, colorhypothesis) +  labs(title = "  ", subtitle = "external enviornment")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank())
t6 <- plottsneelipsev2(pittsne, pittsne$earlylate, colorhypothesis) +  labs(title = "  ", subtitle = "internal clock")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank())
t456 <- plot_grid(t4, t5, t6, nrow = 1, rel_widths = c(1.1,1,1))
t456

# replacement
hyptsne <- subsetmaketsne("hypothalamus", timinglevels, sexlevels)
pittsne <- subsetmaketsne("pituitary", timinglevels, sexlevels)
gontsne <- subsetmaketsne("gonads", timinglevels, sexlevels)

pittsne <- addgroupings(pittsne)

t4 <- plottsneelipsev2(pittsne, pittsne$treatment, allcolors) +  labs(title = "pituitary ", subtitle = "parental stage and manipulations") +
  facet_wrap(~sex) 
t5 <- plottsneelipsev2(pittsne, pittsne$extint, colorhypothesis) +  labs(title = "  ", subtitle = "external enviornment")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank())
t6 <- plottsneelipsev2(pittsne, pittsne$earlylate, colorhypothesis) +  labs(title = "  ", subtitle = "internal clock")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank())
t456 <- plot_grid(t4, t5, t6, nrow = 1, rel_widths = c(1.1,1,1))
t456

```



## DEGs

```{r allDEGs}
DEG_path <- "../results/DEseq2/treatment/"   # path to the data
DEG_files <- dir(DEG_path, pattern = "*DEGs") # get file names
DEG_pathfiles <- paste0(DEG_path, DEG_files)
#DEG_files

allDEG <- DEG_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name") %>% 
  mutate(DEG = sapply(strsplit(as.character(file_name),'./results/DEseq2/treatment/'), "[", 2))  %>% 
  mutate(DEG = sapply(strsplit(as.character(DEG),'_diffexp.csv'), "[", 1))  %>% 
  mutate(tissue = sapply(strsplit(as.character(DEG),'\\.'), "[", 1)) %>%
  mutate(down = sapply(strsplit(as.character(DEG),'\\_'), "[", 3)) %>%
  mutate(up = sapply(strsplit(as.character(DEG),'\\_'), "[", 4)) %>%
  mutate(comparison = paste(down,up, sep = "_")) %>%
  mutate(sex = sapply(strsplit(as.character(sextissue),'\\_'), "[", 1)) %>%
  mutate(tissue = sapply(strsplit(as.character(sextissue),'\\_'), "[", 2)) %>%
  dplyr::select(sex,tissue,comparison, direction, gene, lfc, padj, logpadj) # %>%
 # mutate(tissue = factor(tissue, levels = tissuelevel),
  #       comparison = factor(comparison , levels = comparisonlevelsremoval),
  #       direction = factor(direction, levels = alllevels))
head(allDEG)



candidateDEGS <- allDEG %>%
  filter(gene %in% parentalcaregenes) %>%
  mutate(posneg = ifelse(lfc >= 0, "+", "-"),
         sex = recode(sex, "female" = "F", "male" = "M" ),
         tissue = recode(tissue, 
                         "hypothalamus" = "H",
                         "pituitary" = "P", 
                         "gonad" = "G", "gonads" = "G")) %>%
  mutate(res = paste(sex, tissue, posneg, sep = "")) %>%
  select(gene, res, comparison)  %>%
  group_by(gene,  comparison) %>%
  summarize(res = str_c(res, collapse = " ")) %>%
  pivot_wider(names_from = comparison, values_from = res) %>%
  select(gene, inc.d3_m.inc.d3, inc.d9_m.inc.d9, inc.d17_m.inc.d17, hatch_m.n2,
         inc.d17_prolong, hatch_prolong,extend_hatch, n5_extend, 
         early_inc.d9 ,hatch_early)
head(candidateDEGS[1:5])
```





## suppl fig 1

```{r supplfig-4}

comparisonlevelsmanip <- c("inc.d3_m.inc.d3", "inc.d9_m.inc.d9", "inc.d17_m.inc.d17", "hatch_m.n2",
         "early_inc.d9" ,"hatch_early", "inc.d17_prolong", "hatch_prolong","extend_hatch", "n5_extend")

# for fig 1
DEGmanip <- allDEG %>% 
  filter(comparison %in% comparisonlevelsmanip) %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelsmanip))

DEGmanip %>% 
  group_by(comparison, sex, tissue) %>%
  summarize(totalDEGs = n())  %>%
  arrange(desc(totalDEGs))

s1a <- makebargraph(DEGmanip, "hypothalamus","DEGs w/ + LFC", 0, 3200, DEGmanip$comparison) + 
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank()) + 
  labs(subtitle = "hypothalamus") + geom_vline(xintercept = 4.5, linetype = "dashed", color = "grey") 

s1b <- makebargraph(DEGmanip, "pituitary","DEGs w/ + LFC", 0, 3200, DEGmanip$comparison) + 
  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), strip.text = element_blank()) + 
  labs(subtitle = "pituitary")  + geom_vline(xintercept = 4.5, linetype = "dashed", color = "grey") 


s1c <- makebargraph(DEGmanip, "gonad","DEGs w/ + LFC", 0, 3200, DEGmanip$comparison) + 
  theme(strip.text = element_blank()) + 
  labs(subtitle = "gonad", x = "Comparison of parental stage and manipulation groups") + geom_vline(xintercept = 4.5, linetype = "dashed", color = "grey") + 
  scale_x_discrete(breaks= comparisonlevelsmanip,
                      labels= comparisonlevelsmanip,
                   drop=FALSE)

contrasts <- png::readPNG("../figures/images/fig_fig4sup1.png")
contrasts <- ggdraw() +  draw_image(contrasts, scale = 1)


supplfig3 <- plot_grid(contrasts, s1a, s1b, s1c, ncol = 1, rel_heights = c(0.5, 1,1,1.5))
supplfig3

pdf(file="../figures/supplfig-3-1.pdf", width=5, height=5)
plot(supplfig3)
dev.off()



write.csv(candidateDEGS, "../results/table2.csv", row.names = F)
```
