---
title: "Fig3"
author: "Rayna M Harris"
date: "3/26/2020"
output: md_document
---

# all things box plots


## candidate genes

```{r}
library(tidyverse)
library(ggtext)
library(cowplot)
library(ggpubr)

source("../R/themes.R")

knitr::opts_chunk$set(echo = TRUE, message = F, fig.path = "../figures/")

candidategenes <- c("OXT", "AVP", "GNRH1", "GNRHR", "CGNRH-R",
                    "AR", "POMC", "AGRP", 
                       "CRH", "AVPR1A", "AVPR1B", "AVPR2","VIP",
                       "CYP19A1", "DRD1", "DRD2", "PRL", "PRLR", "SOX9", 
                    "ESR1","ESR2", "LBH", "CDK1", "BRCA1",
                    "PTEN", "CREBBP", "FOS", "JUN", "EGR1",
                     "BDNF", "GRM2","GRIA1",
                    "KCNJ5", "CISH", "PTGER3", "CEBPD", "ZBTB16", 
                    "DIO3", "DIO2", "DIO1",
                    
                     "VIPR1", "VIPR2", "NPY", "LH", "FSH", "FSHB",
                    "JAK2", "HCRT", "TRH", "TSHB",
                    "MC3R", "MC4R", "MC5R",  "NR3C1", "NR3C2",
                    "STAT5B","NPVF") 

candidategenesslim <- c("OXT", "AVP", "GNRH1", "GNRHR", 
                    "AR",  "CYP19A1", 
                    "AVPR1A", "AVPR1B", "AVPR2","VIP",
                    "DRD1", "DRD2", 
                    "PRL", "PRLR",  
                    "ESR1","ESR2", "LBH",  
                    "FOS", "JUN", "EGR1", "BDNF") 

# candidategenesslim: AR, AVP, AVPR1A, AVPR1B, AVPR2, BDNF, CYP19A1, DRD1, EGR1, ESR1, ESR2, FOS, GNRH1, GNRHR, JUN, LBH, OXT, PRL, PRLR, VIP
# DEG candidategenesslim: AR, AVPR1A, AVPR1B, AVPR2, BDNF, CYP19A1, DRD1, ESR1, FOS, GNRHR, LBH, PRL, PRLR, 
# non-DEG candidategenesslim: AVP, AVPR1B, ESR2,  GNRH1, JUN, OXT, VIP



hormonepapergenes <- c("GNRH1", "CGNRH-R", "GNRHR",  
                       "FSHB", "FSHR", "LHCGR", # no LSH
                       "VIP", "VIPR1",
                       "ESR1", "AR", "CYP19A1", "HSD17B1", # receptors synthesis
                       "PGR" , "HSD3B2", 
                       "PRL", "PRLR")
```

## variance stabilized gene expression  (vsd)

```{r }
geneids <- read_csv("../metadata/00_geneinfo.csv") %>% select(-X1)

vsd_path <- "../results/DEseq2/"   # path to the data
vsd_files <- dir(vsd_path, pattern = "*vsd.csv") # get file names
vsd_pathfiles <- paste0(vsd_path, vsd_files)
vsd_files


allvsd <- vsd_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name")  %>% 
  dplyr::rename("gene" = "X1") %>% 
  pivot_longer(cols = L.G118_female_gonad_control:y98.o50.x_male_pituitary_inc.d3, 
               names_to = "samples", values_to = "counts") 

getcandidatevsd <- function(whichgenes, whichtissue, whichsex){
  candidates  <- allvsd %>%
    filter(gene %in% whichgenes) %>%
    dplyr::mutate(sextissue = sapply(strsplit(file_name, '_vsd.csv'), "[", 1)) %>%
    dplyr::mutate(sextissue = sapply(strsplit(sextissue, '../results/DEseq2/'), "[", 2)) %>%
    dplyr::mutate(sex = sapply(strsplit(sextissue, '\\_'), "[", 1),
                tissue = sapply(strsplit(sextissue, '\\_'), "[", 2),
                treatment = sapply(strsplit(samples, '\\_'), "[", 4)) %>%
    dplyr::mutate(treatment = sapply(strsplit(treatment, '.NYNO'), "[", 1)) %>%
    dplyr::select(sex, tissue, treatment, gene, samples, counts) %>%
    filter(tissue == whichtissue, sex %in% whichsex)  %>%
    drop_na()
  candidates$treatment <- factor(candidates$treatment, levels = alllevels)
  return(candidates)
}

hypvsd <- getcandidatevsd(hormonepapergenes, "hypothalamus", sexlevels)
pitvsd <- getcandidatevsd(hormonepapergenes, "pituitary", sexlevels)
gonvsd <- getcandidatevsd(hormonepapergenes, "gonad", sexlevels)
head(hypvsd)
tail(gonvsd)

candidatevsd <- rbind(hypvsd, pitvsd)
candidatevsd <- rbind(candidatevsd, gonvsd)

unique(candidatevsd$gene)
```

## Figs 


```{r fig3, fig.width = 7}
# summary DEG results from DESeq2
candidateDEGS <- read_csv("../../musicalgenes/data/allDEG.csv") %>%
  select(-X1) %>%
  filter(gene %in% hormonepapergenes)
head(candidateDEGS)

# get genes to plot
candidateDEGS %>% filter(tissue == "hypothalamus", sex == "female", comparison != "control_bldg") 
candidateDEGS %>% filter(tissue == "hypothalamus", sex == "male", comparison != "control_bldg") 
candidateDEGS %>% filter(tissue == "pituitary", sex == "male", comparison != "control_bldg") 
candidateDEGS %>% filter(tissue == "pituitary", sex == "female", comparison != "control_bldg") 
candidateDEGS %>% filter(tissue == "gonad", sex == "female", comparison != "control_bldg") 

# summarize all differences
candidateDEGtable <- candidateDEGS %>%
  mutate(posneg = ifelse(lfc >= 0, "+", "-")) %>%
  mutate(geneposneg = paste(gene, posneg, sep = "")) %>%
  select(sex, tissue, comparison, geneposneg) %>%
  group_by(sex, tissue, comparison) %>%
   arrange(geneposneg) %>%
  summarize(genes = str_c(geneposneg, collapse = " ")) %>% 
  pivot_wider(names_from = comparison, values_from = genes)  %>% 
  ungroup(tissue) %>%
  mutate(tissue = factor(tissue, levels =  tissuelevel))  %>% 
  arrange(sex, tissue)  %>% 
  select(sex, tissue, bldg_lay, lay_inc.d3, inc.d9_inc.d17, hatch_n5, control_bldg)
candidateDEGtable

newboxplot <- function(df, mygenes, whichsex, whichstage){
  
  p <- df %>%
    filter(gene %in% mygenes, 
           sex %in% whichsex,
           treatment %in% whichstage) %>%
    droplevels() %>%
    mutate(tissue = factor(tissue, levels = tissuelevel)) %>%
    ggplot(aes(x = treatment, y = counts, fill = treatment, color = sex)) +
    geom_boxplot() +
    geom_jitter(size = 0.5, width = 0.1) +
    facet_grid(tissue~gene, scales = "free_y") +
    theme_B3() +
    scale_color_manual(values = allcolors) +
    scale_fill_manual(values = allcolors) +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 45, hjust = 1),
          strip.text.x = element_text(face = "italic"),
          axis.title.x = element_blank())  +
    labs(x = "Parental stage",
         y = "variance stabilized expression")
  return(p)
}

a1 <- newboxplot(hypvsd, c("PGR",  "CYP19A1", "LHCGR" ), "female", c( "hatch", "n5")) + 
  theme(strip.text.y = element_blank()) + labs(subtitle = "Females")
a2 <- newboxplot(hypvsd, c("AR"), "male", c( "hatch", "n5")) + 
  theme(axis.title.y = element_blank()) + labs(subtitle = "Males")

b1 <- newboxplot(gonvsd, c("HSD3B2"), "female", c( "bldg", "lay"))  +
  theme(strip.text.y = element_blank(),
        axis.title.y = element_blank()) + labs(subtitle = "Females")
b2 <- newboxplot(gonvsd, c("VIPR1",  "PRLR" ), "female", c( "lay", "inc.d3"))  + 
  theme(axis.title.y = element_blank()) + labs(subtitle = " ")

ab <- plot_grid(a1,a2,b1,b2, rel_widths = c(6,2.5,2,4), labels = c("a", " ", "b", " "), label_size = 8, nrow = 1)

c1 <- newboxplot(pitvsd, c( "ESR1", "GNRHR"), "female", c("bldg", "lay",  "inc.d3")) 
c2 <- newboxplot(pitvsd, c( "PRL"), "female", c("inc.d9", "inc.d17", "hatch", "n5")) 
c3 <- newboxplot(pitvsd, c("VIPR1",  "PRL" ), "male", c( "inc.d9", "inc.d17")) 


c <- plot_grid(c1 + theme(strip.text.y = element_blank()) + labs(subtitle = "Females"),
          c2 + theme(strip.text.y = element_blank(),
                    axis.title.y = element_blank()) + labs(subtitle = " ") ,
          c3 + theme(axis.title.y = element_blank()) + labs(subtitle = "Males"), 
          nrow = 1, rel_widths = c(6,4,4),
          labels = c("c"), label_size = 8)

plot_grid(ab,c, nrow = 2)

# correlations
library(corrr)


hormones <- read_csv("../results/07_hormoneswide.csv") %>%
  select(-study, -treatment, -sex)
head(hormones)

head(candidatevsd)

vsdhormones <- candidatevsd %>%
  pivot_wider(names_from = gene, values_from = counts) %>%
  mutate(bird_id = sapply(strsplit(samples,"\\_"), "[", 1)) %>%
  left_join(.,hormones, by =  "bird_id")
vsdhormones


vsdhormoneshyp <- vsdhormones %>% filter(tissue == "hypothalamus" )
vsdhormonespit <- vsdhormones %>% filter(tissue == "pituitary" )
vsdhormonesgon <- vsdhormones %>% filter(tissue == "gonad" )

plotcorrs <- function(whichtissue, whichsex){
  
  x <- vsdhormones  %>%
    filter(tissue == whichtissue, 
           sex == whichsex) %>%
    select(-sex, - tissue, - treatment, -samples, -bird_id, -moltbin) %>%
    correlate()
  print(fashion(x))
  
  p <-rplot(x, colors = c("#0571b0", "#92c5de", "#f7f7f7","#f7f7f7","#f7f7f7", "#f4a582", "#ca0020")) +
    theme_B3() +
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 45, hjust = 1),
          axis.text = element_text(face = "italic")) +
    labs(subtitle = whichtissue)
  return(p)
}

a <- plotcorrs("hypothalamus", "female") + theme(legend.position = "none")
b <- plotcorrs("pituitary", "female") + theme(axis.text.y = element_blank()) + theme(legend.position = "none")
c <- plotcorrs("gonad", "female") + theme(axis.text.y = element_blank()) + theme(legend.position = "none")

d <- plotcorrs("hypothalamus", "male") 
e <- plotcorrs("pituitary", "male") + theme(axis.text.y = element_blank())
f <- plotcorrs("gonad", "male") + theme(axis.text.y = element_blank())

plot_grid(a,b,c, d,e,f, nrow = 2, rel_widths = c(1.2,1,1), rel_heights = c(1,1.2))

plotspecificcorrs <- function(df, myx, myy, myxlab, myylab){
  p <- df %>%
    mutate(tissue = factor(tissue, levels = tissuelevel)) %>%
    ggplot(aes(x = myx, y = myy)) +
    geom_point(aes(color = treatment)) +
    geom_smooth(method = "lm", aes(color = sex)) +
    facet_wrap(~sex, scales = "free", nrow = 2) +
    scale_color_manual(values = allcolors) +
    labs(x = myxlab, y = myylab) +
    theme_B3() +
    theme(legend.position = "none",
          axis.title = element_text(face = "italic"))
  return(p)
}


a <- plotspecificcorrs(vsdhormoneshyp, vsdhormoneshyp$FSHB, vsdhormoneshyp$PRL, "FSHB", "PRL") + labs(subtitle = "Hypothalamus")
b <- plotspecificcorrs(vsdhormonespit, vsdhormonespit$prolactin, vsdhormonespit$PRL, "circulating prolactin", "PRL") +
  theme(axis.title.x = element_text(face = "plain")) + labs(subtitle = "Pituitary")
c <- plotspecificcorrs(vsdhormonesgon, vsdhormonesgon$ESR1, vsdhormonesgon$PGR, "ESR1", "PGR")  + labs(subtitle = "Gonads")

plot_grid(a,b,c,nrow = 1, labels = "auto", label_size = 8)
```

```{r writefiles}
#write.csv(candidatevsd, "../../musicalgenes/data/candidatecounts.csv")
#write.csv(candidatevsd, "../results/candidatecounts.csv")
write.csv(candidateDEGtable, "../results/candidateDEGtable.csv")

```