---
title: "Fig1"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)
library(Rtsne)
library(kableExtra) 
library(ggtext) # for italic fonts


source("../R/themes.R")
source("../R/functions.R")

knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/')
```

#  Experimental design, tSNE analysis, and bar chars


## import limma counts and sample info

```{r data}
countData <- read_csv("../results/01_limma.csv") %>%
  column_to_rownames(var = "X1")
countData <- as.data.frame(t(countData))
head(countData[1:3])

colData <- read_csv("../metadata/00_colData.csv") %>%
  mutate(treatment = factor(treatment, levels = alllevels),
         tissue = factor(tissue, levels = tissuelevels)) %>% 
  column_to_rownames(var = "X1") 
head(colData)
# check ready for analysis
# row.names(countData) == row.names(colData)
head(row.names(countData) == row.names(colData))
```


## tsne

```{r tSNE-df}

# uses count data from limma

# prep for tsne
chartsne <- subsetmaketsne(tissuelevels, charlevels, sexlevels)
hyptsne <- subsetmaketsne("hypothalamus", charlevels, sexlevels)
pittsne <- subsetmaketsne("pituitary", charlevels, sexlevels)
gontsne <- subsetmaketsne("gonads", charlevels, sexlevels)

ftsne <-  subsetmaketsne(tissuelevels, charlevels, "female")
mtsne <-  subsetmaketsne(tissuelevels, charlevels, "male")
```


## Treatment specific DEGs 

```{r suppltables}
allDEG <- read_csv("../results/03_allDEG.csv") %>%
  mutate(tissue = factor(tissue, levels = tissuelevel),
         direction = factor(direction, levels = alllevels))

# for fig 1
DEGchar <- allDEG %>% 
  filter(comparison %in% comparisonlevelschar) %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelschar))

# for supple fig 1
DEGcontrol <- allDEG %>% 
  filter(grepl("control", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelscontrol))

DEGbldg <- allDEG %>% 
  filter(grepl("bldg", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelsbldg))  %>%
  drop_na()


suppltable1 <- DEGchar %>%
  arrange( tissue, sex, direction, gene)
head(suppltable1)
write_csv(suppltable1, "../results/suppltable1.csv")

suppltable2 <- rbind(DEGcontrol, DEGbldg)  %>%
  arrange( tissue, sex, direction, gene)
head(suppltable2)
write_csv(suppltable2, "../results/suppltable1.csv")

```



## Sex and Tissue -related DEGs

```{r DEGs, message=F}

## other DEG stuff
hypsex <- read_csv("../results/DEseq2/sex/hypothalamus_female_male_DEGs.csv")
pitsex <- read_csv("../results/DEseq2/sex/pituitary_female_male_DEGs.csv")
gonsex <- read_csv("../results/DEseq2/sex/gonad_female_male_DEGs.csv")

hyppit <- read_csv("../results/DEseq2/tissue/hypothalamus_pituitary_DEGs.csv") 
hypgon <- read_csv("../results/DEseq2/tissue/hypothalamus_gonad_DEGs.csv")
pitgon <- read_csv("../results/DEseq2/tissue/pituitary_gonad_DEGs.csv")

hyppit$direction <- factor(hyppit$direction, levels = c("hypothalamus", "pituitary"))
hypgon$direction <- factor(hypgon$direction, levels = c("hypothalamus",  "gonad"))
pitgon$direction <- factor(pitgon$direction, levels = c( "pituitary", "gonad"))

```

## Figure 1

```{r fig1, fig.width=7.25, fig.height=7.25}

a <- png::readPNG("../figures/images/fig_fig1a.png")
a <- ggdraw() +  draw_image(a, scale = 1)

b1 <- plottsneelipse(chartsne, chartsne$tissue, allcolors)  + labs(y = "tSNE 2 ", subtitle = " ")  
b2 <- sexbarplots(hyppit, 0, 8100) + labs(subtitle = " ", y = "DEGs w/ + LFC") +
  theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
  scale_x_discrete(labels=c("hypothalamus" = "hyp", "pituitary" = "pit" ))
b3 <- sexbarplots(hypgon, 0, 8100) + labs(subtitle = " " ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(), 
        axis.ticks = element_blank(), axis.title.y = element_blank()) +
    scale_x_discrete(labels=c("hypothalamus" = "hyp",  "gonad" = "gon"))
b4 <- sexbarplots(pitgon, 0, 8100) + labs(subtitle = " " ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank()) +
    scale_x_discrete(labels=c(  "pituitary" = "pit", "gonad" = "gon"))
c1 <- plottsneelipse(chartsne, chartsne$sex, allcolors)   + labs(y = "tSNE 2 ", subtitle = " ")    
c2 <- sexbarplots(hypsex, 0, 8100) + labs(y = "DEGs w/ + LFC", subtitle = "hypothalamus" ) +
  theme(axis.text.y = element_blank(), axis.ticks = element_blank())
c3 <- sexbarplots(pitsex, 0, 8100) + labs(subtitle = "pituitary" ) + 
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank())
c4 <- sexbarplots(gonsex, 0, 8100) + labs(subtitle = "gonads" ) +
  theme(axis.text.y = element_blank(), axis.line.y = element_blank(),  
        axis.ticks = element_blank(), axis.title.y = element_blank())
bc <- plot_grid(b1,b2,b3,b4, c1,c2,c3,c4, nrow = 1, rel_widths = c(1.5,1.1,0.9,0.9,1.5,1.1,0.9,0.9),
                labels = c("B", "", "", "", "C"), label_size = 8)

d1 <- plottsneelipsev2(hyptsne, hyptsne$treatment, allcolors) + 
  labs(x = NULL, subtitle = "hypothalamus")  + 
  facet_wrap(~sex, scales = "free")
d3 <- plottsneelipsev2(pittsne, pittsne$treatment, allcolors ) + 
  labs(x = NULL, subtitle = "pituitary") + 
  facet_wrap(~sex, scales = "free") +
  theme(strip.text = element_blank())
d5 <- plottsneelipsev2(gontsne, gontsne$treatment, allcolors ) + 
   facet_wrap(~sex, scales = "free") +
  theme(strip.text = element_blank()) +
  labs(x = "tSNE1 \n \n DEGs = differentially expressed genes \n + LFC = positive log fold change", 
       subtitle = "gonads")
d2 <- makebargraph(DEGchar, "hypothalamus","DEGs w/ + LFC", 0, 1800) + 
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())  
d4 <- makebargraph(DEGchar, "pituitary","DEGs w/ + LFC", 0, 1800)  +  
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        strip.text.x = element_blank())   
d6 <- makebargraph(DEGchar, "gonad","DEGs w/ + LFC", 0, 1800) +  
  theme(strip.text.x = element_blank()) +
  scale_x_discrete(labels = comparisonlabelschar)
d <- plot_grid(d1,d2,d3,d4,d5,d6, ncol = 2, rel_heights = c(1,0.9,1.3), rel_widths = c(1,2),
                  labels = c("D"), label_size = 8)

fig1 <- plot_grid(a,bc, d, nrow = 3, rel_heights = c(0.7,0.7,2),
                  labels = c("A"), label_size = 8)
fig1

pdf(file="../figures/fig1-1.pdf", width=7.25, height=7.25)
plot(fig1)
dev.off()
```

## suppl fig 1 controls versus bldg

```{r supplfig-1, fig.width=5, fig.height=5}

sa <- png::readPNG("../figures/images/fig_supplfig-1.png")
sa <- ggdraw() +  draw_image(sa, scale = 1)

s1a <- makebargraphsuppl(DEGcontrol, "hypothalamus","DEGs w/ + LFC", 0, 5000) + 
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank()) + 
  labs(subtitle = "hypothalamus") 
s1c <- makebargraphsuppl(DEGcontrol, "pituitary","DEGs w/ + LFC", 0, 5000)  +  
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        strip.text.x = element_blank())    + 
  labs(subtitle = "pituitary") 
s1e <- makebargraphsuppl(DEGcontrol, "gonad","DEGs w/ + LFC", 0, 5000) +  
  theme(strip.text.x = element_blank()) +
  scale_x_discrete(labels = comparisonlevelscontrol) +
  labs(subtitle = "gonads") 
  

s1b <- makebargraphsuppl(DEGbldg, "hypothalamus", NULL, 0, 1000) + 
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank())  
s1d <- makebargraphsuppl(DEGbldg, "pituitary",NULL, 0, 1000)  +  
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        strip.text.x = element_blank())   
s1f <- makebargraphsuppl(DEGbldg, "gonad",NULL, 0, 1000) +  
  theme(strip.text.x = element_blank()) +
  scale_x_discrete(labels = comparisonlevelsbldg) 

s1 <- plot_grid(s1a,s1b,s1c,s1d,s1e,s1f, ncol = 2, rel_heights = c(1,0.9,1.3),
                labels = c("B", "C"), label_size = 8)

supplfig1 <- plot_grid(sa, s1, ncol = 1, rel_heights = c(0.75,2), labels = c("A"), label_size = 8)
supplfig1

pdf(file="../figures/supplfig-1-1.pdf", width=5, height=5)
plot(supplfig1)
dev.off()
```



```{r eval = F}
# save file for musical genes https://raynamharris.shinyapps.io/musicalgenes/
#write.csv(allDEG, "../../musicalgenes/data/allDEG.csv")

# tsne files too big to save
#write.csv(chartsne, "../../musicalgenes/data/tsne.csv")
```




