---
title: "Removal only"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)
library(Rtsne)
library(ggsignif)

source("../R/themes.R")
source("../R/functions.R")
source("../R/genelists.R")

knitr::opts_chunk$set(echo = TRUE, message = F, warning = F,
                      fig.path = '../figures/', fig.width = 7.25, fig.height = 7.25)
```

# Figure 4. What is the effect of removal


## import limma counts and sample info

```{r data}
countData <- read_csv("../results/01_limma.csv") %>%
  column_to_rownames(var = "X1")
countData <- as.data.frame(t(countData))
head(countData[1:3])

colData <- read_csv("../metadata/00_colData.csv") %>%
  mutate(treatment = factor(treatment, levels = alllevels),
         tissue = factor(tissue, levels = tissuelevels)) %>% 
  column_to_rownames(var = "X1") 
head(colData)
# check ready for analysis
# row.names(countData) == row.names(colData)
head(row.names(countData) == row.names(colData))
```

## tsne


```{r tSNE-df}

# prep for tsne
hyptsne <- subsetmaketsne("hypothalamus", removallevels, sexlevels)
pittsne <- subsetmaketsne("pituitary", removallevels, sexlevels)
gontsne <- subsetmaketsne("gonads", removallevels, sexlevels)

addgroupings <- function(df){
  
  df <- df %>% mutate(earlylate = fct_collapse(treatment, 
                                  early = c("early", "m.inc.d3", "m.inc.d9", "inc.d3", 
                                         "inc.d9",  "bldg"),
                                  late = c("inc.d17",   "m.inc.d17", "prolong" ,  "hatch" , 
                                         "m.n2", "extend", "n5"),
                                  reference = "control"),
                extint = fct_collapse(treatment, 
                                  nest = c("m.inc.d3", "m.inc.d9", "m.n2", "m.inc.d17", "bldg"),
                                  eggs = c("inc.d3", "inc.d9", "inc.d17", "prolong"),
                                  chicks = c("early", "hatch", "extend", "n5"),
                                  reference = "control")) 
  return(df)
}
  
hyptsne <- addgroupings(hyptsne)
pittsne <- addgroupings(pittsne)
gontsne <- addgroupings(gontsne)
head(gontsne)


t1 <- plottsneelipsev2(hyptsne, hyptsne$treatment, allcolors) +  labs(subtitle = "Hypothalamus ") +
  facet_wrap(~sex) + theme(axis.title.x = element_blank())
t2 <- plottsneelipsev2(hyptsne, hyptsne$extint, colorhypothesis) +  labs(subtitle = "  ")   +
  facet_wrap(~sex) + theme(axis.title = element_blank())
t3 <- plottsneelipsev2(hyptsne, hyptsne$earlylate, colorhypothesis) +  labs(subtitle = "  ")   +
  facet_wrap(~sex) + theme(axis.title = element_blank())
t123 <- plot_grid(t1, t2, t3, nrow = 1, rel_widths = c(1.1,1,1))


t4 <- plottsneelipsev2(pittsne, pittsne$treatment, allcolors) +  labs(subtitle = "Pituitary ") +
  facet_wrap(~sex) + theme(axis.title.x = element_blank(), strip.text = element_blank())
t5 <- plottsneelipsev2(pittsne, pittsne$extint, colorhypothesis) +  labs(subtitle = "  ")   +
  facet_wrap(~sex) + theme(axis.title = element_blank(), strip.text = element_blank())
t6 <- plottsneelipsev2(pittsne, pittsne$earlylate, colorhypothesis) +  labs(subtitle = "  ")   +
  facet_wrap(~sex) + theme(axis.title = element_blank(), strip.text = element_blank())
t456 <- plot_grid(t4, t5, t6, nrow = 1, rel_widths = c(1.1,1,1))

t7 <- plottsneelipsev2(gontsne, gontsne$treatment, allcolors) +  labs(subtitle = "Gonads ") +
  facet_wrap(~sex) + theme(strip.text = element_blank())
t8 <- plottsneelipsev2(gontsne, gontsne$extint, colorhypothesis) +  labs(subtitle = "  ")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank(), strip.text = element_blank())
t9 <- plottsneelipsev2(gontsne, gontsne$earlylate, colorhypothesis) +  labs(subtitle = "  ")   +
  facet_wrap(~sex) + theme(axis.title.y = element_blank(), strip.text = element_blank())
t789 <- plot_grid(t7, t8, t9, nrow = 1)

tsneplots <- plot_grid(t123, t456,t789, ncol = 1, rel_widths = c(1.1,1,1))
tsneplots
```


## variance stabilized gene expression  (vsd)

```{r vsd}
vsd_path <- "../results/DEseq2/hypothesis/"   # path to the data
vsd_files <- dir(vsd_path, pattern = "*vsd.csv") # get file names
vsd_pathfiles <- paste0(vsd_path, vsd_files)
vsd_files


## before pivoting, check names of df with
## head(names(allvsd)) and tail(names(allvsd))

allvsd <- vsd_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name")  %>% 
  dplyr::rename("gene" = "X1") %>% 
  pivot_longer(cols = blk.s061.pu.y_female_gonad_inc.d9:y98.o50.x_male_pituitary_inc.d3, 
               names_to = "samples", values_to = "counts") 
allvsd <- as_tibble(allvsd)

head(allvsd)
```

```{r candidatevsd}

# for plotting gene expression over time
getcandidatevsdmanip <- function(whichgenes, whichtissue){
  
  candidates  <- allvsd %>%
    filter(gene %in% whichgenes) %>%
    dplyr::mutate(sextissue = sapply(strsplit(file_name, '_vsd.csv'), "[", 1),
                  sextissue = sapply(strsplit(sextissue, '../results/DEseq2/hypothesis/'), "[", 2),
                  sex = sapply(strsplit(sextissue, '\\_'), "[", 1),
                tissue = sapply(strsplit(sextissue, '\\_'), "[", 2),
                treatment = sapply(strsplit(samples, '\\_'), "[", 4),
                treatment = sapply(strsplit(treatment, '.NYNO'), "[", 1),
                treatment = recode(treatment, "m.hatch" = "m.n2", "extend.hatch" = "m.n2",
                                                   "inc.prolong" = "prolong", "m.inc.d8" = "early"),
                treatment =  factor(treatment, levels = alllevels),
                earlylate = fct_collapse(treatment, 
                                  early = c("early", "m.inc.d3", "m.inc.d9", "inc.d3", 
                                         "inc.d9",  "bldg"),
                                  late = c("inc.d17",   "m.inc.d17", "prolong" ,  "hatch" , 
                                         "m.n2", "extend", "n5"),
                                  reference = "control"),
                extint = fct_collapse(treatment, 
                                  nest = c("m.inc.d3", "m.inc.d9", "m.n2", "m.inc.d17", "bldg"),
                                  eggs = c("inc.d3", "inc.d9", "inc.d17", "prolong"),
                                  chicks = c("early", "hatch", "extend", "n5"),
                                  reference = "control"))  %>%
    dplyr::select(gene, counts, sex, tissue, treatment, earlylate, extint, samples)  
  return(candidates)
}

candidatevsd <- getcandidatevsdmanip(candidategenes)
hypvsd <- candidatevsd %>% filter(tissue %in% "hypothalamus") %>% drop_na()
pitvsd <- candidatevsd %>% filter(tissue %in% "pituitary")%>% drop_na()
gonvsd <- candidatevsd %>% filter(tissue %in% "gonad")%>% drop_na()

```


```{r timingfigure, fig.height= 7.25in}

plotcandidateremoval <- function(df, whichgene, whichtissue){
  
  p <- df %>%
    dplyr::filter(gene  == whichgene, treatment %in% removallevels)  %>%
    ggplot(aes(y =  counts, x = treatment, fill = treatment, color = sex)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(size = 0.25, aes(color = sex)) +
    theme_B3() +
    theme(legend.position = "none",
          axis.title.x = element_blank(),
          plot.subtitle = element_text(face = "italic")) +
    scale_color_manual(values = allcolors) +
    scale_fill_manual(values = allcolors)  +
    labs(title = paste(whichtissue, sep = " "), subtitle = whichgene, y = "gene expression") +
    #facet_wrap(~sex)  +
    geom_signif(comparisons = list(c( "inc.d3", "m.inc.d3"),
                                   c( "inc.d9", "m.inc.d9"),
                                   c( "inc.d17", "m.inc.d17"),
                                   c( "hatch", "m.n2")),
                map_signif_level=TRUE,
                textsize = 3, family = 'Helvetica',
                vjust = 1.5, size = 0.5)
  return(p)
  
}

a <- plotcandidateremoval(hypvsd, "DRD1", "hypothalamus") + theme(axis.title.x = element_blank())
b <- plotcandidateremoval(pitvsd, "PRL", "pituitary")+ theme(axis.title.x = element_blank())
c <- plotcandidateremoval(gonvsd, "CRHBP", "gonads")

plot_grid(a,b,c, nrow = 3)

```



## DEGs

```{r allDEGs}
DEG_path <- "../results/DEseq2/manip/"   # path to the data
DEG_files <- dir(DEG_path, pattern = "*DEGs") # get file names
DEG_pathfiles <- paste0(DEG_path, DEG_files)
#DEG_files

allDEG <- DEG_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name") %>% 
  mutate(DEG = sapply(strsplit(as.character(file_name),'./results/DEseq2/manip/'), "[", 2))  %>% 
  mutate(DEG = sapply(strsplit(as.character(DEG),'_diffexp.csv'), "[", 1))  %>% 
  mutate(tissue = sapply(strsplit(as.character(DEG),'\\.'), "[", 1)) %>%
  mutate(down = sapply(strsplit(as.character(DEG),'\\_'), "[", 3)) %>%
  mutate(up = sapply(strsplit(as.character(DEG),'\\_'), "[", 4)) %>%
  mutate(comparison = paste(down,up, sep = "_")) %>%
  mutate(sex = sapply(strsplit(as.character(sextissue),'\\_'), "[", 1)) %>%
  mutate(tissue = sapply(strsplit(as.character(sextissue),'\\_'), "[", 2)) %>%
dplyr::select(sex,tissue,comparison, direction, gene, lfc, padj, logpadj) 
head(allDEG)

allDEG$tissue <- factor(allDEG$tissue , levels = tissuelevel)
allDEG$comparison <- factor(allDEG$comparison , levels = comparisonlevels)
allDEG$direction <- factor(allDEG$direction, levels = alllevels)
head(allDEG)

candidateDEGS <- allDEG %>%
  filter(gene %in% candidategenes) %>%
  mutate(posneg = ifelse(lfc >= 0, "+", "-"),
         sex = recode(sex, "female" = "F", "male" = "M" ),
         tissue = recode(tissue, 
                         "hypothalamus" = "H",
                         "pituitary" = "P", "gonad" = "G")) %>%
  mutate(res = paste(sex, tissue, posneg, sep = "")) %>%
  select(gene, res, comparison)  %>%
  group_by(gene,  comparison) %>%
  summarize(res = str_c(res, collapse = " ")) %>%
  pivot_wider(names_from = comparison, values_from = res) %>%
  select(gene, contains("m.")) 
candidateDEGS

hypothesisDEGStable <- allDEG %>%
  filter(gene %in% hypothesisDEGs) %>%
  mutate(posneg = ifelse(lfc >= 0, "+", "-"),
         sex = recode(sex, "female" = "F", "male" = "M" ),
         tissue = recode(tissue, 
                         "hypothalamus" = "H",
                         "pituitary" = "P", "gonad" = "G")) %>%
  mutate(res = paste(sex, tissue, posneg, sep = "")) %>%
  select(gene, res, comparison)  %>%
  group_by(gene,  comparison) %>%
  summarize(res = str_c(res, collapse = " ")) %>%
  pivot_wider(names_from = comparison, values_from = res) %>%
  select(gene, contains("m.")) 
hypothesisDEGStable
```



## make figure

```{r fig4, fig.width=7.25, fig.height=7.25}

a <- png::readPNG("../figures/images/fig_fig4a.png")
a <- ggdraw() +  draw_image(a, scale = 1)

b1 <- plotcandidatemanipquad(candidatevsd, "hypothalamus", c("DRD1")) 
b2 <- plotcandidatemanipquad(candidatevsd,"pituitary", c("PRL")) 
b3 <- plotcandidatemanipquad(candidatevsd,"gonad", c("PGR")) 

b <- plot_grid(b1,b2,b3, ncol = 1)

c1 <- plottsneelipsev2(hyptsne, hyptsne$treatment, allcolors) + 
  labs(subtitle = "Hypothalamus ", x = NULL)  
c2 <- plottsneelipsev2(hyptsne, hyptsne$extint, allcolors ) + 
  labs(subtitle = " ", x = NULL) + 
  theme(axis.text.y = element_blank(), axis.title.y = element_blank())
c3 <- plottsneelipsev2(hyptsne, hyptsne$earlylate, allcolors ) + 
  labs(subtitle = " ", x = NULL) + 
  theme(axis.text.y = element_blank(), axis.title.y = element_blank()) 
c4 <- plottsneelipsev2(pittsne, pittsne$treatment, allcolors ) + 
  labs(subtitle = "Pituitary ", x = NULL) 
c5 <- plottsneelipsev2(pittsne, pittsne$extint, allcolors ) + 
  labs(subtitle = " ", x = NULL) + 
  theme(axis.text.y = element_blank(), axis.title.y = element_blank()) 
c6 <- plottsneelipsev2(pittsne, pittsne$earlylate, allcolors ) + 
  labs(subtitle = " ", x = NULL) + 
  theme(axis.text.y = element_blank(), axis.title.y = element_blank())
c7 <- plottsneelipsev2(gontsne, gontsne$treatment, allcolors ) + 
  labs(subtitle = "Ggonads ")  
c8 <- plottsneelipsev2(gontsne, gontsne$extint, allcolors ) + 
  labs(subtitle = " " )    +
  theme(axis.text.y = element_blank(), axis.title.y = element_blank())
c9 <- plottsneelipsev2(gontsne, gontsne$earlylate, allcolors ) + 
  labs(subtitle = " " ) + 
  theme(axis.text.y = element_blank(), axis.title.y = element_blank())

c <- plot_grid(c1,c2,c3,c4,c5,c6,c7,c8,c9, nrow = 3)

bc <- plot_grid(b, c, nrow = 1, labels = c("", "C"), label_size = 8)
 
fig4 <- plot_grid(a, bc, ncol = 1, rel_heights  = c(0.25,1),
          labels = "AUTO", label_size = 8)
fig4

pdf(file="../figures/fig4-1.pdf", width=7.25, height=7.25)
plot(fig4)
dev.off()





candidatevsd <- candidatevsd %>%
  dplyr::mutate(treatment = fct_collapse(treatment,
                                         "m.n2" = c("m.n2",  "m.hatch" ),
                                         "prolong" = c("prolong", "inc.prolong") ,
                                         "extend" = c("extend", "extend.hatch")
                                         ))  %>%
  dplyr::mutate(day = fct_collapse(treatment,
                                    "0" = c("control", "bldg"),
                                    "1" = c("lay"),
                                     "3" = c("inc.d3", "m.inc.d3" ),
                                     "9" = c("inc.d9", "m.inc.d9", "early"  ),
                                     "17" = c("inc.d17", "m.inc.d17", "prolong"  ),
                                     "18" = c("hatch", "m.n2" ),
                                     "22" = c("n5",  "extend" ),
                                     "26" = c("n9"  )
                                     )) %>%
   mutate(treatment = factor(treatment, levels = alllevels)) %>%
  dplyr::mutate(day = factor(day, levels = c("0", "1", "3", "9", "17", "18", "22", "26")))

candidatevsd %>%
    filter(tissue == "hypothalamus", sex == "female") %>%
    filter(gene %in% "DRD1") %>%
    drop_na()  %>%
    ggplot(aes(y =  counts, x = day, fill = treatment, color = sex)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(size = 0.25, aes(color = sex)) +
    theme_B3() +
    theme(legend.position = "bottom",
          #axis.text.x = element_blank(),
          #axis.title.x = element_blank(),
          strip.text = element_text(face = "italic")) +
    scale_color_manual(values = allcolors) +
    scale_fill_manual(values = allcolors)  +
    labs(subtitle = paste("female", "hypothalamus", sep = " "), y = "DRD1")


candidatevsd %>%
    filter(tissue == "pituitary", sex == "female") %>%
    filter(gene %in% "PRL") %>%
    drop_na()  %>%
    ggplot(aes(y =  counts, x = day, fill = treatment, color = sex)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(size = 0.25, aes(color = sex)) +
    theme_B3() +
    theme(legend.position = "bottom",
          #axis.text.x = element_blank(),
          #axis.title.x = element_blank(),
          strip.text = element_text(face = "italic")) +
    scale_color_manual(values = allcolors) +
    scale_fill_manual(values = allcolors)  +
    labs(subtitle = paste("female", "pituitary", sep = " "), y = "PRL")

```





