---
title: "Fig5"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)
source("../R/themes.R")

knitr::opts_chunk$set(echo = TRUE, message = F, fig.path = "../figures/")
```

## DEGs

```{r fig5, fig.width=7, fig.height=7}

DEG_path <- "../results/DEseq2/manip/"   # path to the data
DEG_files <- dir(DEG_path, pattern = "*DEGs") # get file names
DEG_pathfiles <- paste0(DEG_path, DEG_files)
DEG_files

allDEG <- DEG_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name") %>% 
  mutate(DEG = sapply(strsplit(as.character(file_name),'./results/DEseq2/manip/'), "[", 2))  %>% 
  mutate(DEG = sapply(strsplit(as.character(DEG),'_diffexp.csv'), "[", 1))  %>% 
  mutate(tissue = sapply(strsplit(as.character(DEG),'\\.'), "[", 1)) %>%
  mutate(down = sapply(strsplit(as.character(DEG),'\\_'), "[", 3)) %>%
  mutate(up = sapply(strsplit(as.character(DEG),'\\_'), "[", 4)) %>%
  mutate(comparison = paste(down,up, sep = "_")) %>%
  mutate(sex = sapply(strsplit(as.character(sextissue),'\\_'), "[", 1)) %>%
  mutate(tissue = sapply(strsplit(as.character(sextissue),'\\_'), "[", 2)) 
  
allDEG <- allDEG %>%
dplyr::select(sex,tissue,comparison, direction, gene, lfc, padj, logpadj)  

allDEG %>% distinct(comparison)

comparisonlevels <-  c(	 "inc.d3_m.inc.d3",			
                             "inc.d9_m.inc.d9",	
                             "inc.d17_m.inc.d17",		
                           "hatch_m.n2",				
                          		
                           "inc.d9_m.inc.d8",	

                         "m.inc.d9_m.n2",
                         "m.inc.d9_m.inc.d8",
                         
                         "m.inc.d8_extend",
                         "prolong_extend",
                           "hatch_extend",
                         "m.n2_extend",
                         
                         "m.inc.d8_prolong",
                            "inc.d17_prolong",	
                           "m.inc.d17_prolong",
                         
                           "m.inc.d3_m.inc.d9",
                           "m.inc.d3_m.inc.d17",
                         "m.inc.d3_m.n2",
                         "m.inc.d9_m.inc.d17")

levelsreplace <- c( "m.inc.d8" , "prolong" , "extend")
levelsremoval <- c( "m.inc.d3" ,    "m.inc.d9" , "m.inc.d17" , "m.n2")
controlsremovalreplace <- c( "inc.d3" ,    "inc.d9" , "inc.d17" , "hatch")

manipulationsandcontrols <- c(controlsremoval, levelsreplace, levelsremoval)



allDEG$tissue <- factor(allDEG$tissue , levels = tissuelevel)
allDEG$comparison <- factor(allDEG$comparison , levels = comparisonlevels)
allDEG$direction <- factor(allDEG$direction, levels = manipulationsandcontrols)


allDEG %>%
  group_by(sex, tissue, comparison) %>%
  summarize(n = n())

expdesign <- png::readPNG("../figures/images/fig5a_fig5a.png")
expdesign <- ggdraw() +  draw_image(expdesign, scale = 1)

replacementplots <- allDEG %>%
  filter(comparison %in% c("inc.d9_m.inc.d8", "inc.d17_prolong", "hatch_extend" ))  %>%
ggplot(aes(x = comparison,  fill = direction)) +
  geom_bar(position = "dodge") +
  facet_grid(tissue~sex) +
  theme_B3() +
  theme(#axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.text.y =  element_blank())  +
  guides(fill = guide_legend(nrow = 1)) +
  labs(x = "Offspring replacement", y = "Total differentially expressed genes") +
  scale_fill_manual(values = allcolors,
                       name = "increased in", drop = FALSE) +
  scale_color_manual(values = sexcolors) +
  geom_text(stat='count', aes(label=..count..), vjust =-0.5, 
            position = position_dodge(width = 1),
            size = 2.5, color = "black") +
  guides(fill =  guide_legend(nrow =2)) +
  ylim(0,3500) 

mylegend <- get_legend(replacementplots)

removalplots <- allDEG %>%
  filter(comparison %in% c("inc.d3_m.inc.d3" ,  "inc.d9_m.inc.d9", 
                        "inc.d17_m.inc.d17", "hatch_m.n2" ))  %>%
ggplot(aes(x = comparison,  fill = direction)) +
  geom_bar(position = "dodge") +
  facet_grid(tissue~sex) +
  theme_B3() +
  theme(#axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.x = element_blank(),
         axis.text.y = element_blank(),
        legend.position = "none",
        strip.placement = "right")  +
  guides(fill = guide_legend(nrow = 1)) +
  labs(x = "Offspring removal", y = NULL) +
  scale_fill_manual(values = allcolors,
                       name = "increased in", drop = FALSE) +
  scale_color_manual(values = sexcolors) +
  geom_text(stat='count', aes(label=..count..), vjust =-0.5, 
            position = position_dodge(width = 1),
            size = 2.5, color = "black") +
  ylim(0,3500) 

barplots <- plot_grid( replacementplots + theme(legend.position = "none"),  removalplots,  ncol = 2, rel_widths = c(1,1.2))

fig5 <- plot_grid(expdesign, barplots, ncol =1, rel_heights = c(0.5,1))
fig5


```

```{r writefiles}
write_csv(allDEG, "../results/DEGs-manip.csv")
```

## subset. examine for E, T, hyp, and gonad hypotheses


```{r subset}

subsetDEGs <- function(whichsex, whichtissue, whichcomparison) {
df <- allDEG %>%
  filter(sex %in% whichsex,
         tissue %in% whichtissue,
         comparison %in% whichcomparison)  %>%
  group_by(sex, tissue, comparison) #%>%
  #summarize(DEGs = n()) %>%
  #arrange(desc(DEGs)) %>%
  #drop_na()
print(df)
}


subsetDEGs(c("male","female"), c("hypothalamus", "pituitary", "gonad"), comparisonlevels)
fhyphatchext <- subsetDEGs("female", "hypothalamus", "hatch_extend") %>% arrange (gene)
mhyphatchext <- subsetDEGs("male", "hypothalamus", "hatch_extend") %>% arrange (gene)

ggplot(fhyphatchext, aes(x = lfc, y = logpadj)) + geom_point() + xlim(-5,5) + ylim(0,7)
ggplot(mhyphatchext, aes(x = lfc, y = logpadj)) + geom_point() + xlim(-5,5) + ylim(0,7)

```

