---
title: "Fig X"
author: "Rayna M Harris"
date: "2/20/2020"
output: html_document
---


# all things box plots


## candidate genes

```{r}
candidategenes <- c("OXT", "AVP", "GNRH1",  "AR", "POMC", "AGRP",
                       "CRH", "AVPR1A", "AVPR1B", "AVPR2",
                       "CYP19A1", "DRD1", "DRD2", "PRL", "PRLR", "SOX9") 


```

## variance stabilized gene expression  (vsd)

```{r vsd}
geneids <- read_csv("../metadata/00_geneinfo.csv")

vsd_path <- "../results/DEseq2/"   # path to the data
vsd_files <- dir(vsd_path, pattern = "*vsd.csv") # get file names
vsd_pathfiles <- paste0(vsd_path, vsd_files)
vsd_files


allvsd <- vsd_pathfiles %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x), .id = "file_name")  %>% 
  dplyr::rename("gene" = "X1") %>% 
  pivot_longer(cols = L.G118_female_gonad_control:y98.o50.x_male_pituitary_inc.d3, 
               names_to = "samples", values_to = "counts") 

getcandidatevsd <- function(whichgenes, whichtissue, whichsex){
  candidates  <- allvsd %>%
    filter(gene %in% whichgenes) %>%
    dplyr::mutate(sextissue = sapply(strsplit(file_name, '_vsd.csv'), "[", 1)) %>%
    dplyr::mutate(sextissue = sapply(strsplit(sextissue, '../results/DEseq2/'), "[", 2)) %>%
    dplyr::mutate(sex = sapply(strsplit(sextissue, '\\_'), "[", 1),
                tissue = sapply(strsplit(sextissue, '\\_'), "[", 2),
                treatment = sapply(strsplit(samples, '\\_'), "[", 4)) %>%
    dplyr::mutate(treatment = sapply(strsplit(treatment, '.NYNO'), "[", 1)) %>%
    dplyr::select(sex, tissue, treatment, gene, samples, counts) %>%
    filter(tissue == whichtissue, sex %in% whichsex)  %>%
    drop_na()
  candidates$treatment <- factor(candidates$treatment, levels = alllevels)
  return(candidates)
}

hypvsd <- getcandidatevsd(candidategenes, "hypothalamus", sexlevels)
pitvsd <- getcandidatevsd(candidategenes, "pituitary", sexlevels)
gonvsd <- getcandidatevsd(candidategenes, "gonad", sexlevels)
head(hypvsd)
head(pitvsd)
head(gonvsd)
```

## Figs 

```{r}
makeboxplots <- function(df, whichgene, myylab, whichsex){
  p <- df %>%
    filter(treatment %in% charlevels,
           gene %in% whichgene,
           sex %in% whichsex) %>%
    filter(treatment != "control") %>%
    ggplot(aes(x = treatment, y = counts, fill = treatment, color = sex)) +
    geom_boxplot() + 
    #geom_point() +
    facet_wrap(~sex) +
    theme_B3() +
    scale_fill_manual(values = allcolors) +
    scale_color_manual(values = allcolors) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none") +
    labs(y = myylab , x = "Parental stage", subtitle = "") +
    theme(axis.title.y = element_markdown())
  return(p)
}

## hyp 
p2 <- makeboxplots(hypvsd, "AR","*AR* expression", "male") +
              geom_signif(comparisons=list(c("inc.d9", "inc.d17")), annotations= "*", 
              y_position = 8, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) +
              theme(axis.text.x = element_blank(), axis.title.x = element_blank())

p3 <- makeboxplots(hypvsd, "DRD1","*DRD1* expression", "female") +
              geom_signif(comparisons=list(c("hatch", "n5")), annotations= "*", 
              y_position = 10, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) +
              #geom_signif(comparisons=list(c("control", "bldg")), annotations= "*", 
              #y_position = 10, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) + 
              theme(axis.text.x = element_blank(), axis.title.x = element_blank())

p23 <- plot_grid(p3,p2, labels = c("b", "c"), label_size = 12)

## pit 


p5 <- makeboxplots(pitvsd, "PRL","*PRL* expression", "male") +  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), strip.text = element_blank())+
              #geom_signif(comparisons=list(c("control", "bldg")), annotations= "*", 
              #y_position = 21.5, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) +
              geom_signif(comparisons=list(c("inc.d9", "inc.d17")), annotations= "*", 
              y_position = 21.5, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) 
p6 <- makeboxplots(pitvsd, "PRL","*PRL* expression", "female")  +  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), strip.text = element_blank()) +
              geom_signif(comparisons=list(c("inc.d9", "inc.d17")), annotations= "*", 
              y_position = 21, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) +
              #geom_signif(comparisons=list(c("control", "bldg")), annotations= "*", 
              #y_position = 21, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) +
              geom_signif(comparisons=list(c("hatch", "n5")), annotations= "*", 
              y_position = 21, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 )

p56 <- plot_grid(p6,p5, labels = c("e", "f"), label_size = 12)

## gon

p8 <- makeboxplots(gonvsd, "SOX9","*SOX9* expression", "male")  +  theme(strip.text = element_blank()) +
              geom_signif(comparisons=list(c("lay", "inc.d3")), annotations= "*", 
              y_position = 7.5, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 )
p9 <- makeboxplots(gonvsd, "AVPR1A","*AVPR1A* expression", "female") +  theme(strip.text = element_blank()) +
              #geom_signif(comparisons=list(c("control", "bldg")), annotations= "*", 
              #y_position = 9.5, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) +
              geom_signif(comparisons=list(c("lay", "inc.d3")), annotations= "*", 
              y_position = 9.5, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 ) +
              geom_signif(comparisons=list(c("inc.d3", "inc.d9")), annotations= "*", 
              y_position = 9.5, tip_length = 0.005, vjust = 0.5, color= "black" , textsize = 3 )

p89 <- plot_grid(p9,p8, labels = c("h", "i"), label_size = 12)

```

