---
title: "Fig 2"
output: md_document
---

# Fig 2

```{r setup, include=T}
library(tidyverse)
library(cowplot)
library(ggsignif)

source("../R/themes.R")
source("../R/functions.R")

knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/')
```

## Treatment specific DEGs 

```{r suppltables}
allDEG <- read_csv("../results/03_allDEG.csv") %>%
  mutate(tissue = factor(tissue, levels = tissuelevel),
         direction = factor(direction, levels = alllevels),
         label = gsub("_","\nvs. ", comparison)) %>%
  filter(lfc > 1.1 | lfc < -1.1 )
head(allDEG)

# for suppl figures
DEGcontrol <- allDEG %>% 
  filter(grepl("control", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelscontrol)) %>%
  group_by(sex, tissue, comparison, direction, label) %>%
    summarise(n = n()) %>%
    mutate(n = ifelse(direction == "control", n*-1, n*1 ))


DEGbldg <- allDEG %>% 
  filter(grepl("bldg", comparison),
         !grepl("m.|early|extend|prolong|control", comparison))  %>%
  drop_na() %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelsbldg))  %>%
  group_by(sex, tissue, comparison, direction, label) %>%
    summarise(n = n()) %>%
    mutate(n = ifelse(direction == "bldg", n*-1, n*1 ))

DEGchar <- allDEG %>% 
  filter(comparison %in% comparisonlevelschar,
         !grepl("control|bldg", comparison)) %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelschar)) %>%
  mutate(updown = ifelse(lfc > 0, 1, -1)) %>%
  group_by(sex, tissue, comparison, direction, label, updown) %>%
  summarise(n = n()) %>%
  mutate(n = n*updown ) %>%
  select(-updown)
  
```


```{r fig2-new, fig.width=7.25, fig.height=7.25}
a <- plot.volcano("hypothalamus", sexlevels,  "control_bldg") + 
  facet_wrap(~sex) 

b <- makebargraphv3(DEGcontrol, "hypothalamus","No. of DEGs\n(-) decreased  increased (+)", comparisonlabelscontrol) +
  labs(title = "Control versus all other reproductive and parental stages",
       subtitle = "hypothalamus") +
  geom_rect(mapping=aes(xmin=0.5, xmax=1.5, ymin=-1000, ymax = 350, fill = F), color="black", alpha=0.5) +
  annotate("text", x = 1, y = -1075, label = "B", size = 2.5)   

c <- makebargraphv3(DEGbldg, "hypothalamus", "No. of DEGs\n (-)decreased  increased (+)", comparisonlabelsbldg) +
  labs(title = "Nest-building versus all other parental stages",
       subtitle = "hypothalamus")
d <- makebargraphv3(DEGchar, "hypothalamus", NULL,  comparisonlabelscharnobldg) +
  labs(title = "Comparison of sequential parental stages",
       subtitle = "hypothalamus")

e <- makebargraphv3(DEGbldg, "pituitary", "No. of DEGs\n (-)decreased  increased (+)", comparisonlabelsbldg) +
  labs(subtitle = "pituitary")
f <- makebargraphv3(DEGchar, "pituitary", NULL,comparisonlabelscharnobldg) +
  labs(subtitle = "pituitary")

g <- makebargraphv3(DEGbldg, "gonad", "No. of DEGs\n (-)decreased  increased (+)", comparisonlabelsbldg) +
  labs(subtitle = "gonads")
h <- makebargraphv3(DEGchar, "gonad", NULL, comparisonlabelscharnobldg) +
  labs(subtitle = "gonads")

ab <- plot_grid(b,a,rel_widths = c(2.5,1), 
                labels = c("A", "B"), label_size = 8, hjust = 0)
cd <- plot_grid(c,d,rel_widths = c(1.1,1), align = "h",
                labels = c("C", "D"), label_size = 8, hjust = 0)
ef <- plot_grid(e,f,rel_widths = c(1.1,1), align = "h")
gh <- plot_grid(g,h,rel_widths = c(1.1,1), align = "h")

fig <- plot_grid(ab,cd,ef, gh, ncol = 1)
fig

```

## Save files

```{r write}
pdf(file="../figures/fig2-new-1.pdf", width=7, height=7)
plot(fig)
dev.off()

png("../figures/fig2-new-1.png", width = 7, height = 7, 
    units = 'in', res = 300)
plot(fig) 
dev.off()

sessionInfo()
```