---
title: "Gonad"
output: md_document
---

# Gonad

```{r setup, include=T}
library(tidyverse)
library(cowplot)
library(ggsignif)

source("../R/themes.R")
source("../R/functions.R")

knitr::opts_chunk$set(echo = TRUE, fig.path = '../figures/')
```

## Treatment specific DEGs in the Hypothalamsu

```{r suppltables}
allDEG <- read_csv("../results/03_allDEG.csv") %>%
  mutate(tissue = factor(tissue, levels = tissuelevel),
         direction = factor(direction, levels = alllevels),
         label = gsub("_","\nvs. ", comparison)) %>%
  filter(tissue == "gonad")
allDEG


# for suppl figures
DEGcontrol <- allDEG %>% 
  filter(grepl("control", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelscontrol))


DEGbldg <- allDEG %>% 
  filter(grepl("bldg", comparison),
         !grepl("m.|early|extend|prolong", comparison))  %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelsbldg))  %>%
  drop_na()

DEGchar <- allDEG %>% 
  filter(comparison %in% comparisonlevelschar,
         !grepl("control|bldg", comparison)) %>%
  mutate(comparison = factor(comparison, levels = comparisonlevelschar))


candidatevsd <- read_csv("../results/03_candidatevsd.csv") %>% 
  select(-X1) %>%
  filter(treatment %in% charlevels) %>%
  mutate(treatment = factor(treatment, levels = charlevels)) %>%
  drop_na() %>%
    mutate(external = fct_collapse(treatment, 
                                   "none" = c("control", "bldg"),
                                   "eggs" = c("lay" , "inc.d3", 
                                              "inc.d9", "inc.d17"),
                                   "chicks" = c("hatch", "n5", "n9")))
```


```{r gonad, fig.width=7, fig.height=7}

a <- plot.volcano("gonad", sexlevels,  "control_bldg") + 
  facet_wrap(~sex) +  labs(title = "Gonad") 
b <- makebargraph(DEGcontrol, "gonad","DEGs w/ + LFC", 0, 4200, comparisonlabelscontrol) 
  labs(title = " ") 
  
c <- makebargraph(DEGbldg, "gonad", "DEGs w/ + LFC", 0, 2200, comparisonlabelsbldg) 
d <- makebargraph(DEGchar, "gonad","DEGs w/ + LFC", 0, 1500, comparisonlabelscharnobldg) 

e <- candidateboxplot("gonad",  c("ESR1"), sexlevels)
f <- candidateboxplot("gonad",  c("PGR"), sexlevels)

ab <- plot_grid(a,b,rel_widths = c(1,3), labels = c("A", "B"), label_size = 8)
cd <- plot_grid(c,d,rel_widths = c(1,1), labels = c("C", "D"), label_size = 8)
ef <- plot_grid(e,f,rel_widths = c(1,1), labels = c("E", "F"), label_size = 8)

goncharfig <- plot_grid(ab,cd,ef, ncol = 1)
goncharfig
```

## Save files

```{r write}
pdf(file="../figures/pitcharfig.pdf", width=7, height=7)
plot(goncharfig)
dev.off()

png("../figures/pitcharfig.png", width = 7, height = 7, 
    units = 'in', res = 300)
plot(goncharfig) # Make plot
dev.off()

sessionInfo()
```